### ISSUE TITLE
Cannot shallow render a component containing hooks

### ISSUE THREAD

**Issue by ChibiBlasphem** [facebook/react#14091]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
An error is thrown:
Invariant Violation: Hooks can only be called inside the body of a function component.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
App.js
```javascript
import React, { useState } from 'react'

const App = () => {
  const [name, setName] = useState('Chris')
  return (
    <div>Hello { name }</div>
  )
}

export default App
```

Test.js
```javascript
import React from 'react'
import ShallowRenderer from 'react-test-renderer/shallow'
import App from './components/App'

const renderer = new ShallowRenderer()
renderer.render(<App />)
```

**What is the expected behavior?**
We should be able to shallow render a component with hooks like any other component (Enzyme too)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.7.0-alpha.0

**Comment by gaearon** [comment]
Yeah. We haven't added support to shallow renderer yet.

**Comment by ChibiBlasphem** [comment]
Do you know when it will be scheduled ? I don't like really much to full mount my application.

**Comment by gaearon** [comment]
It's definitely a prerequisite to considering Hooks stable. Can't give you any dates though.

**Comment by ChibiBlasphem** [comment]
Ok, that's good to know. Thank you for the answers =)

**Comment by jamesseanwright** [comment]
For now, I'm working around this by injecting the hooks I require into my components, [as per this example](https://github.com/jamesseanwright/react-observable-state/blob/98346ddbbc08430d6203069fcefcd3b3dbe8f0fd/src/components/MessageForm.tsx#L6); this allows me to use mocks in my tests, [upon which I set expectations](https://github.com/jamesseanwright/react-observable-state/blob/2951617966c829b912432168d2b90f7f1a571a8b/src/components/__tests__/MessageForm.test.tsx#L28).

It's important to highlight that this is a temporary workaround; it would be far better to assert the props resulting from a hook-derivative re-render, as they are an implementation detail. This probably also demonstrates why they shouldn't be used in the wild just yet! 😁

**Comment by juniusfree** [comment]
+1

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/14567

**Comment by jamesvsshark** [comment]
Thanks for the fix! When will this be released into alpha? Sorry for the noob question.

**Comment by jamesseanwright** [comment]
@jamesvsshark [Within a couple of weeks](https://github.com/facebook/react/pull/14567#issuecomment-456125384), it would seem!

**Comment by Kyle-Mendes** [comment]
I'm still getting this issue in React 16.8 release.  Is there a corresponding jest upgrade that needs to happen to allow shallow testing on hooks?

**Comment by gaearon** [comment]
File a new issue with a reproducing case. Shallow rendering Hooks should work. 

You’re sure you didn’t forget to update test renderer?

**Comment by Kyle-Mendes** [comment]
I'll double check that, thanks @gaearon.

If it is still not working, I'll make a new issue :)

**Comment by LukasBombach** [comment]
Where is the new issue? I too have that problem. I got this _string_:

```js
    const React = require('react');
      module.exports = function ExpectedClass () {
          const [greeting, setgreeting] = React.useState("World");
          return React.createElement("div", {  }, [`Hello ${greeting}`]);
        }
```

which I import via [require-from-string](https://www.npmjs.com/package/require-from-string). This has never been an issue with React classes so I would not assume it's that library's fault. I just switched from class syntax to this syntax and I get that Invariant Error.

**Comment by gaearon** [comment]
@LukasBombach What "this" problem? You didn't provide any details about the error you're seeing. :-)

I'll lock this issue because it seems to attract low-quality reports. If you experience a problem with shallow rendering Hooks, please file a new issue with the exact error you were seeing and a reproducing project. We'd be happy to investigate it then. Thank you!
