### ISSUE TITLE
Hooks don't work with yarn link

### ISSUE THREAD

**Issue by andy9775** [facebook/react#14257]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When developing an external library locally and using `yarn link` to link the library to a local react app the "hooks can only be called inside the body of a function component" error comes up. However, after publishing to npm and using the published version in the local react app everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Create a library that's built with hooks (my-hooks-lib)
2. Create a local app that uses the library (my-react-app) using CRA
3. `yarn link` in my-hooks-lib and in my-react-app run `yarn link my-hooks-lib`

**What is the expected behavior?**
`yarn start` in the react app should use hooks and render normally

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react and react-dom `16.7.0-alpha.2`
OSX

**Comment by gaearon** [comment]
It's not expected that it would work unless you link `react` back from your module to your app.

This has actually always been the case (React apps are subtly broken when there are two copies of React module). Hooks surface this immediately which I guess is good.

We do have another issue tracking a better error message for this case.

**Comment by andy9775** [comment]
My mistake - first time using `yarn link` with react. Thanks for addressing @gaearon

**Comment by corysimmons** [comment]
Is there a workaround for this? How can people locally test react components they want to turn into libraries? :\

**Comment by dcecile** [comment]
If your React app is bundled with Webpack, you can use a [Webpack alias](https://webpack.js.org/configuration/resolve/#resolvealias) to force all React references to resolve to a single module. In your `webpack.config.js`:

```js
{
    /* ... */
    module: {
        rules: [ /* ... */ ],
    },
    resolve: {
        alias: { react: require.resolve("react") }
    },
```

**Comment by maciekgrzybek** [comment]
@dcecile just to clarify, do you resolve that in the library you're working? or in the demo app?

**Comment by dcecile** [comment]
@maciekgrzybek I resolve it in the demo app

**Comment by maciekgrzybek** [comment]
Hey @dcecile thanks for a quick answer, sadly, that doesn't work for me as well.

**Comment by amsterdamharu** [comment]
I don't understand how you end up with 2 copies of react when the module package.json has react as peer dependency and dev dependency so the actual build should not have react included in it whatsoever.

**Comment by LucidityDesign** [comment]
I still get this error message even though I linked react and react-dom (via `yarn link`) and set react and react-dom as alias in my `webpack.config`:
```
'react': require.resolve('./node_modules/react'),
'react-dom': require.resolve('./node_modules/react-dom'),
```

**Comment by Blkc** [comment]
Currently there are like 3 ways you can install local dependencies, 
1) yarn link 
2) yarn add <repository name>
3) yarn add .tgz file

npm pack on the library repository and yarn add .tgz file in the other repo seems to work for me

**Comment by JerryGreen** [comment]
Workaround:

```bash
cd PACKAGE_YOU_DEBUG_LOCALLY
yarn link
yarn install
cd node_modules/react
yarn link
cd YOUR_PROJECT
yarn link PACKAGE_YOU_DEBUG_LOCALLY
yarn link react
```

I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)

**Comment by kas** [comment]
If you're having this issue when developing a package that exports a React component, and you have a folder structure like this:
```
react-component-package/
  package.json
web-application/
  package.json
```

Assuming react-component-package has React as a dev and peer dependency, you can run this command from the react-component-package folder:
`npm link ../web-application/node_modules/react`

The same command should work with Yarn:
`yarn link ../web-application/node_modules/react`

https://stackoverflow.com/a/58612244

**Comment by danantal** [comment]
Will this be addressed somehow? I guess there is an workaround - but when you use create react app you can't really do any hacks in the webpack.config.js 😄

**Comment by brennick** [comment]
Btw we fixed this issue with the steps here: https://robkendal.co.uk/blog/2019-12-22-solving-react-hooks-invalid-hook-call-warning

**Comment by jsmapr1** [comment]
For those coming to the issue via a monorepo such as lerna, you can solve the problem by hoisting the dependencies to the root level.

https://github.com/facebook/react/issues/15097

**Comment by hugomallet** [comment]
React is great for components but it looks like everything around react is preventing you from creating components.
Configuring bundlers and npm dependencies to work with external components is really a hell. And with CRA this is almost impossible.
I beg you, please find a solution to this ! Maybe from webpack 5 module federation ?

**Comment by DLCnow** [comment]
> Workaround:
> 
> ```shell
> cd PACKAGE_YOU_DEBUG_LOCALLY
> yarn link
> yarn install
> cd node_modules/react
> yarn link
> cd ../../node_modules/react-dom
> yarn link
> cd YOUR_PROJECT
> yarn link PACKAGE_YOU_DEBUG_LOCALLY
> yarn link react
> yarn link react-dom
> ```
> 
> I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)

It works! Tks!

**Comment by adamrneary** [comment]
Thanks @JerryGreen!

For future explorers, the above solution didn't happen to work in my case. Not sure if it had to do with the use of NextJS, but that is possible!

A slight tweak worked, though: making the package link to my project's `react` and `react-dom`. 

If you are in the same situation, perhaps try:
```
cd YOUR_PROJECT
cd node_modules/react
yarn link
cd ../react-dom
yarn link

cd PACKAGE_YOU_DEBUG_LOCALLY
yarn link
yarn install
yarn link react
yarn link react-dom

cd YOUR_PROJECT
yarn link PACKAGE_YOU_DEBUG_LOCALLY
``` 

This did the trick for us!

**Comment by jaguardo** [comment]
does yalc help solve this. or complicate it more? I still seem to have the error, even with the work around.

**Comment by aud** [comment]
@jaguardo in my experience Yalc removed a ton of the complexity that you would otherwise have to manage with symlinks yourself. Have been using it for a year or so now and the quality is very high. Worth giving it a shot for your use case.

**Comment by eric-burel** [comment]
For googlers, this issue can also be encountered for project using Webpack 4 and transitionning to Webpack 5. If I sum it up, `yalc link` does the reverse of `yarn link` regarding `node_modules`, favouring those of the project that rely on the package to avoid duplicates? By the way Meteor works this way when using `METEOR_PACKAGE_DIRS`, which has always been extremely more intuitive than `link`.
If yes that would solve the issue more elegantly.

**Comment by regalstreak** [comment]
Nothing worked but yalc for me

**Comment by L0rdH4x0r** [comment]
Nothing from the above was needed! I got mine fixed by **just keeping react and react-dom only as peerDependencies** and delete all other occurrences. After that **delete node_modules and package-lock.json and install again**. Then in should work.

**Comment by eric-burel** [comment]
> Nothing from the above was needed! I got mine fixed by **just keeping react and react-dom only as peerDependencies in package.json** and delete all other occurrences. After that **delete node_modules and package-lock.json and install again**. Then in should work.

Most often, you cannot do this during development though, as you may need React for unit testing or 3rd party tools like Storybook. In a mono-repo, even if React is a peer-dependency of your package, it will fetch the "closest" version, so from your monorepo main `node_modules` instead of those from the app.
I've tested Yalc, with some success at the moment, though I am still not sure of the precise differences with a "normal" npm install.

**Comment by Omrilu-ma** [comment]
Those who still struggling with the issue and work with react-scripts without eject do the following to solve the issue:
1. `yarn add @craco/craco`
2. Change the package.json `start` script

**From:**
``` json
   "start": "react-scripts start",
``` 
**To**
``` json
   "start": "craco start",
``` 

3. Add `craco.config.js` file to your root application with the following content:
```js
const path = require('path')

module.exports = {
    webpack: {
        alias: {
            react: path.resolve(__dirname, './node_modules/react'),
            'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
        },
    },
}
```

**Comment by alex-ds** [comment]
In YOUR_PROJECT's package.json add into a jest config section:

```json
...
  "jest": {
    "moduleNameMapper": {
        "^react$": "<rootDir>/node_modules/react",
        "^react-dom$": "<rootDir>/node_modules/react-dom"
    }
  }
...
```

It worked for me

**Comment by ramyNiranjan** [comment]
> > Workaround:
> > ```shell
> > cd PACKAGE_YOU_DEBUG_LOCALLY
> > yarn link
> > yarn install
> > cd node_modules/react
> > yarn link
> > cd ../../node_modules/react-dom
> > yarn link
> > cd YOUR_PROJECT
> > yarn link PACKAGE_YOU_DEBUG_LOCALLY
> > yarn link react
> > yarn link react-dom
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)
> 
> It works! Tks!

**Comment by ramyNiranjan** [comment]
This solution worked for me, Thanks a lot

**Comment by jquintozamora** [comment]
I configured this in webpack 5 and it's working for me:
```
module.exports = {
  //...
  resolve: {
    symlinks: false,
  },
}
```

**Comment by muratx10** [comment]
> Workaround:
> 
> ```shell
> cd PACKAGE_YOU_DEBUG_LOCALLY
> yarn link
> yarn install
> cd node_modules/react
> yarn link
> cd ../../node_modules/react-dom
> yarn link
> cd YOUR_PROJECT
> yarn link PACKAGE_YOU_DEBUG_LOCALLY
> yarn link react
> yarn link react-dom
> ```
> 
> I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)

@jerrygreen thanks dude. You saved us. Works like a charm!

**Comment by zopelee** [comment]
> > Workaround:
> > ```shell
> > cd PACKAGE_YOU_DEBUG_LOCALLY
> > yarn link
> > yarn install
> > cd node_modules/react
> > yarn link
> > cd ../../node_modules/react-dom
> > yarn link
> > cd YOUR_PROJECT
> > yarn link PACKAGE_YOU_DEBUG_LOCALLY
> > yarn link react
> > yarn link react-dom
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)
> 
> @jerrygreen thanks dude. You saved us. Works like a charm!

Yes. Works like a charm, currently.

But someday, when you `rm -rf node_modules` or move the folder,

you will find, wow, something is screwed like a ****!

**Comment by DaviDevMod** [comment]
> > > Workaround:
> > > ```shell
> > > cd PACKAGE_YOU_DEBUG_LOCALLY
> > > yarn link
> > > yarn install
> > > cd node_modules/react
> > > yarn link
> > > cd ../../node_modules/react-dom
> > > yarn link
> > > cd YOUR_PROJECT
> > > yarn link PACKAGE_YOU_DEBUG_LOCALLY
> > > yarn link react
> > > yarn link react-dom
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I find it easier than some webpack setup or using yet another package manager (yapm? yanc? yalc? wut?)
> > 
> > 
> > @jerrygreen thanks dude. You saved us. Works like a charm!
> 
> Yes. Works like a charm, currently.
> 
> But someday, when you `rm -rf node_modules` or move the folder,
> 
> you will find, wow, something is screwed like a ****!

What about a `postinstall` script that creates the links? So that once you delete node_modules and run `npm install` you get you links back?

**Comment by DaviDevMod** [comment]
I had the same problem in a Next.js app and solved the issue with the approach suggested by [dcecile](https://github.com/facebook/react/issues/14257#issuecomment-508808246). I added this entry in `next.config.js`:

```javascript
webpack: (config) => {
  config.resolve.alias = {
    ...config.resolve.alias,
    react: path.resolve(__dirname, './node_modules/react'),
  };
  // Important: return the modified config
  return config;
},
```

Here are the [docs](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) for modifying Next.js webpack configuration.

**Comment by sickdyd** [comment]
> ```
> cd YOUR_PROJECT
> cd node_modules/react
> yarn link
> cd ../react-dom
> yarn link
> 
> cd PACKAGE_YOU_DEBUG_LOCALLY
> yarn link
> yarn install
> yarn link react
> yarn link react-dom
> 
> cd YOUR_PROJECT
> yarn link PACKAGE_YOU_DEBUG_LOCALLY
> ```

I had problems using this workaround with React 18. The error was:
```
Module not found: Error: Can't resolve 'react-dom/client'
```

To make it work I had to downgrade to a previous React version.

Here the steps I followed:
- go to `package.json`, and change the versions of both `react` and `react-dom` to:
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
```
- change `index.js` to:
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

```
- `yarn install`

I hope this can help in case someone ends up having the same issue.

**Comment by jakebanks** [comment]
Yalc worked for me also, seems like a great tool

**Comment by valdemarrolfsen** [comment]
I created a small command line tool that solved this issue for me by watching the build folder of a project when developing locally and installing it in the node_modules of a destination project: https://github.com/valdemarrolfsen/herd.js.

Its a quite simple tool but it worked perfectly for me at least :)

**Comment by harpreetkhalsagtbit** [comment]
> npm pack

perfect

**Comment by harpreetkhalsagtbit** [comment]
> Currently there are like 3 ways you can install local dependencies,
> 
> 1. yarn link
> 2. yarn add
> 3. yarn add .tgz file
> 
> npm pack on the library repository and yarn add .tgz file in the other repo seems to work for me. The other two give me the hook error.


perfect

**Comment by Sassar88** [comment]
> Those who still struggling with the issue and work with react-scripts without eject do the following to solve the issue:
> 
> 1. `yarn add @craco/craco`
> 2. Change the package.json `start` script
> 
> **From:**
> 
> ```json
>    "start": "react-scripts start",
> ```
> 
> **To**
> 
> ```json
>    "start": "craco start",
> ```
> 
> 3. Add `craco.config.js` file to your root application with the following content:
> 
> ```js
> const path = require('path')
> 
> module.exports = {
>     webpack: {
>         alias: {
>             react: path.resolve(__dirname, './node_modules/react'),
>             'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
>         },
>     },
> }
> ```

based on @Omrilu-ma solution, i got the following error, "craco Module not found: Error: You attempted to import /node_modules/react which falls outside of the project src/ directory."

I Solved this problem with the following additional configuration in Craco:

```
module.exports = {
  webpack: {
    alias: {
      react: path.resolve(__dirname, './node_modules/react'),
      'react-dom': path.resolve(__dirname, './node_modules/react-dom')
    },
    configure: (config, { env, paths }) => {

      const ModuleScopePlugin = config.resolve.plugins.find((plugin) => plugin instanceof ModuleScopePlugin);
      ModuleScopePlugin.allowedPaths.push(path.resolve(__dirname, './node_modules/react'));
      ModuleScopePlugin.allowedPaths.push(path.resolve(__dirname, './node_modules/react-dom'));

      return config;
    }
  },
};

```
