### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by sethandleah** [facebook/react#15315]
Hi all, I am new to react and  I am trying to create a react library of components and I came across this problem because one of the components I am creating uses [REACT HOOKS](https://reactjs.org/docs/hooks-intro.html).

**Disclaimer: this is my first time creating an issue, so please bear with me.**

So I am trying to create an accordion component which toggles between these classes ```accordion__item--open``` and ```accordion__item``` to open and close.

**package.json**

```
{
  "name": "react-lib",
  "version": "0.3.0",
  "description": "A simple UI library of react components",
  "main": "dist/index.js",
  "publishConfig": {
    "registry": ""
  },
  "scripts": {
    "login": "",
    "build": "webpack --mode=production",
    "develop": "webpack --mode=development --watch"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "homepage": "",
  "dependencies": {
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.5",
    "eslint": "^5.15.1",
    "eslint-loader": "^2.1.2",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.2.3",
    "webpack-node-externals": "^1.7.2"
  },
  "devDependencies": {
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-hooks": "^1.6.0"
  }
}
```

**webpack.config.js**

```
const path = require('path');
const webpack = require('webpack');

module.exports =  {

  mode: 'development',
  optimization: {
    minimize: true,
  },
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'index.js',
    library: '',
    libraryTarget: 'commonjs'
  },
  target: 'node',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env', '@babel/react']
        }
      }
    ]
  } 
};
```

**This is the accordion container:**

 ```
import React from 'react'; 

function Accordion({ children }) {

  return (
    <div className="accordion">
      { children }
    </div>
  ); 

}
 
export default Accordion;

```
**This is the accordion item that will live inside the container:** 

```
import React, { useState } from 'react'; 

function AccordionItem({header, content}) { 

const [ isActive, toggleActive ] = useState(false);
  
return (
    <div className={ `accordion__item ${ isActive ? 'accordion__item--open' : '' }` }>

      <button
        className="accordion__item-header"
        onClick={ () => isActive ? toggleActive(false) : toggleActive(true) }
      >
       { header }
       <svg className="icon icon--debit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
         <path className="icon__path" d="M22.37,22.33V2.67a2.63,2.63,0,0,1,5.26,0V47.24a2.63,2.63,0,0,1-5.26.09V27.58H2.71a2.63,2.63,0,0,1,0-5.25Zm11.92,5.25a2.63,2.63,0,0,1,0-5.25h13a2.63,2.63,0,0,1,0,5.25Z">
         </path>
       </svg>
     </button>

     <div className="accordion__item-content">
       { children }
     </div>

   </div>
 )

};

export default AccordionItem;

```

Now inside of a [create-react-app](https://github.com/sethandleah/myapp) I import these components

My [library](https://github.com/sethandleah/react-lib) and the [create-react-app](https://github.com/sethandleah/myapp) are relative to each other and I am using ```npm link```

```
import React from 'react'; 

import {AccordionItem} from 'react-lib'
import {Accordion} from 'react-lib';

function App ({props}) {

  return (
    
      <Accordion>
        <AccordionItem header={"Hello"} content={"World"}/>
      </Accordion> 
  )

}

export default App;
```
I have followed all of these [instructions](https://reactjs.org/warnings/invalid-hook-call-warning.html) and I still get the same error.

**Current behavior?**

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Steps to reproduce**

- clone [https://github.com/sethandleah/react-lib](https://github.com/sethandleah/react-lib)
- clone [https://github.com/sethandleah/myapp](https://github.com/sethandleah/myapp)
- ```cd react-lib```
- ```npm install```
- ```npm link```
- ```cd ../myapp```
- ```npm i```
- ```npm link react-lib```
- ```npm start```

**Expected behavior**

- It should show a button with a "plus" svg sign and the words "Hello" and "World" respectively
- Open devtools and go to elements
- When clicking on the button the class ```accordion_item--open``` should toggle

**To see the above, do the following:**

- Uncomment these lines at ```myapp/src/App.js```
```
import Accordion  from './Accordion';
import AccordionItem from './AccordionItem';
```

- The comment out these line, alse at ```myapp/src/App.js```:

```
import { Accordion } from 'react-lib';
import { AccordionItem } from 'react-lib';
```

**Versions of React, Browser / OS are affected by this issue:**

- React and React-Dom: both are ```^16.8.6``` on  both [react-lib](https://github.com/sethandleah/react-lib) and the [myapp](https://github.com/sethandleah/myapp)
- Browser: Brave ```Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)```
- OS: MacOS High Siera ``` Version 10.13.6 (17G5019)```

**Comment by threepointone** [comment]
I think you're facing the same issue as the folks in https://github.com/facebook/react/issues/13991 Could you have a look at some of the workaround presented at the very bottom of the issue and see of they work for you?

**Comment by revskill10** [comment]
This happens if i use hook inside a HOC.

```js
const HOC = Component => {
  return (props) => {
    const [val] = useState();
    return <div>{val}</div>
  }
}
```

**Comment by threepointone** [comment]
@revskill10 please make a separate issue with a codesandbox repro.

**Comment by ashuanindian** [comment]
I will recommend you to use https://www.npmjs.com/package/webpack-bundle-analyzer.

It happens we often forgot to link react and react-dom to parent application in case of libraries which add two builds of react and leads to this issue. 

If that's the case than just npm link react and react-dom to parent version of react and react-dom.

**Comment by gaearon** [comment]
>My library and the create-react-app are relative to each other and I am using npm link

Did you read this part?

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

It directly addresses the `link` workflow:

<img width="677" alt="Screen Shot 2019-04-04 at 09 28 47" src="https://user-images.githubusercontent.com/810438/55541034-118ffc00-56bc-11e9-9cc0-f04c0f7c3260.png">

**Comment by gaearon** [comment]
(Let me know if this doesn't help and we can reopen. I appreciate the detailed writeup.)

**Comment by sethandleah** [comment]
**Thanks, everyone for pitching in**

@gaearon I had already tried  and retried resolving this according to the recommendations from the React page:

> I have followed all of these [instructions](https://reactjs.org/warnings/invalid-hook-call-warning.html) and I still get the same error.

@threepointone funny enough so many people have found solutions to this at  [#13991](https://github.com/facebook/react/issues/13991)  and I have spent the rest of yesterday implementing  them  with no success.

**Comment by gaearon** [comment]
Ok, if this didn’t help let’s leave it open so somebody can debug your issue and help you. The problem _is_ the same (the way you link packages causes them to be duplicated in the bundle) but I’m not sure why the suggestion didn’t work for you.

**Comment by sethandleah** [comment]
@gaearon you can now close it, the solution above worked.

**Comment by xeastcrast** [comment]
I just call hook in a very very basic way.

`
import React, {useState} from 'react'
import ReactDOM from 'react-dom'

function App() {
const [number, setNumber] = useState(0);
const increase = () => {
    setNumber(number+1);
}
return <div>
<h1>Counting: {number}</h1>
<button onClick={increase} >Increase</button>
</div>
}

const selector = document.getElementById('app');

ReactDOM.render(<App />, selector);

`

I get Error
`Hooks can only be called inside of the body of a function component.`
I have create a lot of react project from sketch but I never get this error before.
I understand all rules of hook.
I spend a time for 12 hours to debug and solve it, But unfortunately I can't, Now I have no idea.

**Comment by carlosriveros** [comment]
@xeastcrast were you able to solve the issue?

**Comment by xeastcrast** [comment]
@carlosriveros 
Case 1:
You might be check your index.html that only have one script tag bundle

If you get the same error after you check index.html
Case 2:
If you use Webpack html, In plugins property inside webpack.config file
And not have {reject: true} in option of new HTMLWebpackPlugin();

You must remove script tag that src to your bundle in index.html

Because HTMLWebpackPlugin will add script tag that include your bundle file automatically.

**Comment by B4BIPIN** [comment]
Hi there, I am new to React Hooks. I just used Material-UI for creating Search Bar in my project. I wrote this code, but this is not working and giving the same issue. I read React Hooks docs but not got nothing regarding this.
**REACTJS CODE**
```import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
import InputBase from '@material-ui/core/InputBase';
import IconButton from '@material-ui/core/IconButton';
import SearchIcon from '@material-ui/icons/Search';

const useStyles = makeStyles({
  root: {
    padding: '2px 4px',
    display: 'flex',
    alignItems: 'center',
    width: 400,
  },
  input: {
    marginLeft: 8,
    flex: 1,
  },
  iconButton: {
    padding: 10,
  },
  divider: {
    width: 1,
    height: 28,
    margin: 4,
  },
});

function Feature() {
    const classes = useStyles();

  return (
    <Paper className={classes.root}>
      <InputBase className={classes.input} placeholder="Search Google Maps" />
      <IconButton className={classes.iconButton} aria-label="Search">
        <SearchIcon />
      </IconButton>
    </Paper>
  );
}

export default Feature;
```
**PACKAGE.JSON**
```{
  "name": "builder-frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.0.1",
    "@material-ui/docs": "^3.0.0-alpha.9",
    "@material-ui/icons": "^4.0.0",
    "@material-ui/styles": "^4.0.1",
    "react": "^16.8.5",
    "react-dom": "^16.8.5",
    "react-redux": "^6.0.1",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "redux": "^4.0.1",
    "styled-components": "^4.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
**VERSION**

- Node -- v10.15.3
- React -- ^16.8.5
- Material-UI -- ^4.0.1

**EXPECTED RESULT**
- Built-in VS CODE and expected _A search bar_
**OUTPUT**
_TypeError: Object(...) is not a function_
_Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:_

**TRY**
_Try to run in **CODESANDBOX**, everything runs fine_ [Check it](https://codesandbox.io/s/material-demo-9me6x).

**Comment by stupidsongshu** [comment]
> Hi there, I am new to React Hooks. I just used Material-UI for creating Search Bar in my project. I wrote this code, but this is not working and giving the same issue. I read React Hooks docs but not got nothing regarding this.
> **REACTJS CODE**
> 
> ```
> import { makeStyles } from '@material-ui/core/styles';
> import Paper from '@material-ui/core/Paper';
> import InputBase from '@material-ui/core/InputBase';
> import IconButton from '@material-ui/core/IconButton';
> import SearchIcon from '@material-ui/icons/Search';
> 
> const useStyles = makeStyles({
>   root: {
>     padding: '2px 4px',
>     display: 'flex',
>     alignItems: 'center',
>     width: 400,
>   },
>   input: {
>     marginLeft: 8,
>     flex: 1,
>   },
>   iconButton: {
>     padding: 10,
>   },
>   divider: {
>     width: 1,
>     height: 28,
>     margin: 4,
>   },
> });
> 
> function Feature() {
>     const classes = useStyles();
> 
>   return (
>     <Paper className={classes.root}>
>       <InputBase className={classes.input} placeholder="Search Google Maps" />
>       <IconButton className={classes.iconButton} aria-label="Search">
>         <SearchIcon />
>       </IconButton>
>     </Paper>
>   );
> }
> 
> export default Feature;
> ```
> 
> **PACKAGE.JSON**
> 
> ```
>   "name": "builder-frontend",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@material-ui/core": "^4.0.1",
>     "@material-ui/docs": "^3.0.0-alpha.9",
>     "@material-ui/icons": "^4.0.0",
>     "@material-ui/styles": "^4.0.1",
>     "react": "^16.8.5",
>     "react-dom": "^16.8.5",
>     "react-redux": "^6.0.1",
>     "react-router-dom": "^5.0.0",
>     "react-scripts": "2.1.8",
>     "redux": "^4.0.1",
>     "styled-components": "^4.2.0"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": [
>     ">0.2%",
>     "not dead",
>     "not ie <= 11",
>     "not op_mini all"
>   ]
> }
> ```
> 
> **VERSION**
> 
> * Node -- v10.15.3
> * React -- ^16.8.5
> * Material-UI -- ^4.0.1
> 
> **EXPECTED RESULT**
> 
> * Built-in VS CODE and expected _A search bar_
>   **OUTPUT**
>   _TypeError: Object(...) is not a function_
>   _Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:_
> 
> **TRY**
> _Try to run in **CODESANDBOX**, everything runs fine_ [Check it](https://codesandbox.io/s/material-demo-9me6x).

I also meet this question when using material-ui.

**Comment by B4BIPIN** [comment]
@stupidsongshu, so how you solved it?

**Comment by vcibel** [comment]
> Hi there, I am new to React Hooks. I just used Material-UI for creating Search Bar in my project. I wrote this code, but this is not working and giving the same issue. I read React Hooks docs but not got nothing regarding this.
> **REACTJS CODE**
> 
> ```
> import { makeStyles } from '@material-ui/core/styles';
> import Paper from '@material-ui/core/Paper';
> import InputBase from '@material-ui/core/InputBase';
> import IconButton from '@material-ui/core/IconButton';
> import SearchIcon from '@material-ui/icons/Search';
> 
> const useStyles = makeStyles({
>   root: {
>     padding: '2px 4px',
>     display: 'flex',
>     alignItems: 'center',
>     width: 400,
>   },
>   input: {
>     marginLeft: 8,
>     flex: 1,
>   },
>   iconButton: {
>     padding: 10,
>   },
>   divider: {
>     width: 1,
>     height: 28,
>     margin: 4,
>   },
> });
> 
> function Feature() {
>     const classes = useStyles();
> 
>   return (
>     <Paper className={classes.root}>
>       <InputBase className={classes.input} placeholder="Search Google Maps" />
>       <IconButton className={classes.iconButton} aria-label="Search">
>         <SearchIcon />
>       </IconButton>
>     </Paper>
>   );
> }
> 
> export default Feature;
> ```
> 
> **PACKAGE.JSON**
> 
> ```
>   "name": "builder-frontend",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@material-ui/core": "^4.0.1",
>     "@material-ui/docs": "^3.0.0-alpha.9",
>     "@material-ui/icons": "^4.0.0",
>     "@material-ui/styles": "^4.0.1",
>     "react": "^16.8.5",
>     "react-dom": "^16.8.5",
>     "react-redux": "^6.0.1",
>     "react-router-dom": "^5.0.0",
>     "react-scripts": "2.1.8",
>     "redux": "^4.0.1",
>     "styled-components": "^4.2.0"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": [
>     ">0.2%",
>     "not dead",
>     "not ie <= 11",
>     "not op_mini all"
>   ]
> }
> ```
> 
> **VERSION**
> 
> * Node -- v10.15.3
> * React -- ^16.8.5
> * Material-UI -- ^4.0.1
> 
> **EXPECTED RESULT**
> 
> * Built-in VS CODE and expected _A search bar_
>   **OUTPUT**
>   _TypeError: Object(...) is not a function_
>   _Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:_
> 
> **TRY**
> _Try to run in **CODESANDBOX**, everything runs fine_ [Check it](https://codesandbox.io/s/material-demo-9me6x).

This happend to me today and I just run npm install --save react-dom@latest

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by miguelmota** [comment]
WhaI followed the instructions provided in the [help page](https://reactjs.org/warnings/invalid-hook-call-warning.html) but it still didn't resolve the problem

**Comment by mikeaustin** [comment]
For me, we solved it for now by simply passing React around as a prop. This is a app and separate modules that we have full control of thought, so I don't know if it applies to everyone.

**Comment by Barathwaja** [comment]
It didn't help me out too..
Using React & React-DOM = 16.8.0 and Material-UI = 4.1.3

**Comment by tquiroga** [comment]
I have been testing all solutions about this hooks problem, any import of a component from an external lib using hooks will crash as there is 2 reacts instances (one from the lib, one from my app). 

I've followed all suggestions, nothing has been working so far. I'm gonna make component with a state until it gets clarified further ...

**Comment by rlech** [comment]
Same Issue here. We have a Project with two react instances. One as `lib` and one `app` that is consuming the `lib`.

**Comment by gtgalone** [comment]
I solve with removing `yarn-lock.json`, `node_modules`, `package-lock.json`, `dist`, kind of cache and build files and then run `yarn` or `npm install` for install libraries again. Now it works!

**Comment by xyj404** [comment]
I solve this by change
```
                <Route key={index} render={route.component} path={route.path} />
```
to
```
                <Route key={index} component={route.component} path={route.path} />
```
but I don't know why :(

**Comment by MikeQin** [comment]
Fixed by using component instead of render by mistake. The official guide didn't mention this scenario.
Thanks, xyj404
`<Route path="/login" exact component={LoginForm} />`

**Comment by raza-jamil-harvest** [comment]
I had the same problem but the cause was different. For anyone using auto-import plugins or snippets make sure you import from the same case react.

If you have mix of  `import {useEffect} from 'react'` and `import {useEffect} from 'React'` you will run into this issue.

**Comment by AnimeManna** [comment]
I also have this problem, though everything works fine for me in the storybook, but when used in the application it gives the same error

**Comment by hugo-integrate** [comment]
same problem too working fine in storybook , but using the app throws this error

**Comment by simonepizzamiglio** [comment]
Same error, I get it when I run `npm test` but the app works fine.
Here's my `package.json`, any suggestion? I am really stuck and wasting time dealing with this error

```
{
  "name": "park-here-dashboard-3",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@date-io/moment": "1.0.1",
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.1",
    "animate.css": "^3.7.0",
    "aws-amplify": "^0.4.8",
    "aws-amplify-react": "^0.1.54",
    "axios": "^0.18.0",
    "file-saver": "^2.0.0",
    "ics-js": "^0.10.2",
    "material-ui-pickers": "2.1.1",
    "moment": "^2.23.0",
    "normalize.css": "^8.0.1",
    "react": "^16.8.6",
    "react-app-polyfill": "^1.0.0",
    "react-date-range": "^1.0.0-beta",
    "react-dom": "^16.8.6",
    "react-google-maps": "^9.4.5",
    "react-jss": "^8.6.1",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "3.0.1",
    "recharts": "^1.3.5",
    "redux": "^4.0.1",
    "styled-components": "^4.2.0",
    "sweetalert2": "^7.33.1",
    "sweetalert2-react-content": "^1.0.1"
  },
  "scripts": {
    "start:dev": "node  -r dotenv/config ./node_modules/react-scripts/bin/react-scripts start dotenv_config_path=./env/development.env",
    "start:stage": "node -r dotenv/config ./node_modules/react-scripts/bin/react-scripts start dotenv_config_path=./env/stage.env",
    "start:prod": "node -r dotenv/config ./node_modules/react-scripts/bin/react-scripts start dotenv_config_path=./env/production.env",
    "build:stage": "node --max_old_space_size=2048 --max_old_space_size=1024 -r dotenv/config ./node_modules/.bin/react-scripts build dotenv_config_path=./env/stage.env",
    "build:dev": "node --max_old_space_size=2048 -r dotenv/config ./node_modules/react-scripts/bin/react-scripts build dotenv_config_path=./env/development.env",
    "build:prod": "node --max_old_space_size=2048 -r dotenv/config ./node_modules/react-scripts/bin/react-scripts build dotenv_config_path=./env/production.env",
    "test": "node -r dotenv/config ./node_modules/.bin/react-scripts test dotenv_config_path=./env/development.env --runInBand",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^4.0.0",
    "@testing-library/react": "^8.0.5",
    "@testing-library/react-hooks": "^1.1.0",
    "dotenv": "^6.0.0",
    "prettier": "^1.15.3",
    "react-test-renderer": "^16.8.6"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Comment by pmjonesg** [comment]
Ran into this situation as well using react and react-dom both v16.8.6, using the `makeStyles` hook from `@material-ui/core` in a separate app linked using npm link.

After upgrading the main app to react and react-dom v16.9.0, and relinking the app that was using the hooks causing the issue, everything started working again.

**Comment by bachphuc** [comment]
Yeah, I had same issue when I use @material-ui. It takes more time to figure out this issue. Then I searched google and found a solution for this. It's here http://putridparrot.com/blog/react-material-ui-invalid-hook-call-hooks-can-only-be-called-inside-of-the-body-of-a-function-component/

```
const SampleFab = () => {
   const classes = useStyles();
   return <Fab color="primary" aria-label="Add" className={classes.fab}><AddIcon /></Fab>;
}
 
export default class SampleComponent extends Component<{}, {}> {
   public render() {
      return (
         <div>
            <SampleFab />
         </div>
      );
   }
}
```

It's crazy but It's working well. Hope this can help.

**Comment by sourcesoft** [comment]
If you're using lerna or a monorepo like me, add this to your Webpack resolve config
```
...
    alias: {
      'react-dom': path.join(process.cwd(), 'path/to/main-package/node_modules/react-dom'),
      react: path.join(process.cwd(), 'path/to/main-package/form/node_modules/react'),
	}
...
```
If you're getting it in Storybook, add it to custom Webpack config there too.

A side note, if this fixes the issue for you, your webpack built bundle also had 2 versions of react in it (use sth like webpack bundle analyzer to inspect it). In my case, I had a separate package in my monorepo that took care of bundling and all the tooling so I had to add an alias.

**Comment by mysteryven** [comment]
> If you're using lerna or a monorepo like me, add sth like this to your Webpack resolve config
> 
> ```
> ...
>     alias: {
>       'react-dom': 'path/to/main-package/node_modules/react-dom',
>       react: 'path/to/main-package/form/node_modules/react',
> 	}
> ...
> ```
> 
> If you're getting it in Storybook, add it to custom Webpack config there too.
> 
> A side note, if this fixes the issue for you, your webpack built bundle also had 2 versions of react in it (use sth like webpack bundle analyzer to inspect it). In my case, I had a separate package in my monorepo that took care of bundling and all the tooling so I had to add an alias.

Thank you, that's solved my problem, I installed another React in my `docs` dictory, which caused this problem.

**Comment by jafartke** [comment]
> I just call hook in a very very basic way.
> 
> ```
> import React, {useState} from 'react'
> import ReactDOM from 'react-dom'
> 
> function App() {
> const [number, setNumber] = useState(0);
> const increase = () => {
>     setNumber(number+1);
> }
> return <div>
> <span>Counting: {number}</span>
> <button onClick={increase} >Increase</button>
> </div>
> }
> 
> const selector = document.getElementById('app');
> 
> ReactDOM.render(<App />, selector);
> ```
> 
> I get Error
> `Hooks can only be called inside of the body of a function component.`
> I have create a lot of react project from sketch but I never get this error before.
> I understand all rules of hook.
> I spend a time for 12 hours to debug and solve it, But unfortunately I can't, Now I have no idea.
> 
> ```
> // Add this in node_modules/react-dom/index.js
> window.React1 = require('react');
> 
> // Add this in your component file
> require('react-dom');
> window.React2 = require('react');
> console.log(window.React1 === window.React2); // I get true
> ```

You might have mismatching versions of React and React DOM.
I had same issue solved by making change in React version

**Comment by abdulmoizshaikh** [comment]
I have face this issue when I try to change my component from functional to classfull component and I also get this error so here is my solution regarding this error hope it helps on your case also.

you should use higher order component in this case

import React from 'react';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/styles';
import Button from '@material-ui/core/Button';

const styles = theme => ({
  root: {
    background: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
    border: 0,
    borderRadius: 3,
    boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .3)',
    color: 'white',
    height: 48,
    padding: '0 30px',
  },
});

class HigherOrderComponent extends React.Component {

  render(){
    const { classes } = this.props;
    return (
      <Button className={classes.root}>Higher-order component</Button>
      );
  }
}

HigherOrderComponent.propTypes = {
  classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(HigherOrderComponent);

**Comment by fabd** [comment]
I am learning React and FWIW, I also saw the issue when trying to render App() like this:

    ReactDOM.render(App(), $("#root"));

My reasoning was that `<App />`would implicitly create a mini template just to insert the App component, so instead I just called App directly, which returns the JSX template.

However, once I started using setState(), it caused the aforementioned issue. Changing to `<App />` solved this.

**Comment by dbeaudway** [comment]
For those who are still encountering this error after troubleshooting all the proposed fixes, double-check that you are using the correct directory casing when running your project. I continued to have problems on my PC and discovered this was the reason why.

[https://stackoverflow.com/questions/58365151/hooks-error-invalid-hook-call-using-nextjs-or-reactjs-on-windows/58365152#58365152](Stackoverflow post)

**Comment by joselcc** [comment]
I was getting that error when running test after updating `react-dom` to version `16.10.2`. Upgrading `enzyme-adapter-react-16` to version `1.15.1` fixed it

**Comment by rockneverdies55** [comment]
Oh man I'm on react v16.10.2. I already spent couple of hours trying fighting this but I won't continue this battle anymore since I have more important things to do. I'm ok with staying on react-final-form 4.1.0 for now. What a frustration.

**Comment by DanielAllt** [comment]
This solved my problem:

[https://github.com/facebook/create-react-app/issues/7676#issuecomment-531543375](https://github.com/facebook/create-react-app/issues/7676#issuecomment-531543375)

**Comment by pluma** [comment]
I've had the same problem just now after upgrading dependencies and spent hours trying to nail this down.

`npm ls react` showed the following:

```
├─┬ @storybook/addon-info@5.2.6
│ └── react@16.9.0
└── react@16.12.0
```

Pinning `react` and `react-dom` to `16.9.0` made the error go away because it made the transient dependency go away. I first thought this meant there was a regression in `16.10.0` until I noticed the problem also occurred in `16.8.6` (because the transient dependency was apparently pinned).

Turns out yarn's [`resolutions` field](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) is a bit finicky to get to work right, especially in lerna monorepos, but eliminating the second copy of React did the trick. I still have no idea how it even ended up in the bundle but that's what caused the problem.

I'm now considering dropping `@storybook/addon-info` completely as it also relies on another dependency that has a dependency on React 0.14 (yes), although that one somehow hasn't caused problems yet.

**Comment by Neeraj-swarnkar** [comment]
> This happens if i use hook inside a HOC.
> 
> ```js
> const HOC = Component => {
>   return (props) => {
>     const [val] = useState();
>     return <div>{val}</div>
>   }
> }
> ```

I am also facing the same issue. 

https://stackoverflow.com/questions/59173968/react-error-hooks-can-only-be-called-inside-the-body-of-a-function-component?noredirect=1#comment104570333_59173968

can you please guide me ?

**Comment by pluma** [comment]
@Neeraj-swarnkar Try reducing your problem to a minimal example that still results in the error.

It almost always boils down to one of two problems:

* you think you're passing a component but it's actually a render prop (i.e. a the "component" is being called as a function, not a component)
* you've somehow bundled more than one version of React via your transient dependencies and they step on each others' toes

Sadly the stack traces tend to be misleading in this case but the error messages generally give you the right idea.

**Comment by Neeraj-swarnkar** [comment]
> @Neeraj-swarnkar Try reducing your problem to a minimal example that still results in the error.
> 
> It almost always boils down to one of two problems:
> 
> * you think you're passing a component but it's actually a render prop (i.e. a the "component" is being called as a function, not a component)
> * you've somehow bundled more than one version of React via your transient dependencies and they step on each others' toes
> 
> Sadly the stack traces tend to be misleading in this case but the error messages generally give you the right idea.

Thanks for the pointer, can you guide me what could be done better or what should i do to fix this ?

**Comment by pluma** [comment]
@Neeraj-swarnkar try commenting out code and replacing it with placeholders until you have a minimal example that still results in the same error.

If you don't have a colleague or peer you can ask to assist you in debugging this further, see if you can find a local meetup, study group or a company that does open office hours and ask them for help. If all else fails, hire someone to look into it for you.

**Comment by ladifire** [comment]
> > My library and the create-react-app are relative to each other and I am using npm link
> 
> Did you read this part?
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
> 
> It directly addresses the `link` workflow:
> 
> <img alt="Screen Shot 2019-04-04 at 09 28 47" width="677" src="https://user-images.githubusercontent.com/810438/55541034-118ffc00-56bc-11e9-9cc0-f04c0f7c3260.png">

This work like a charm!

**Comment by ladifire** [comment]
> > My library and the create-react-app are relative to each other and I am using npm link
> 
> Did you read this part?
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
> 
> It directly addresses the `link` workflow:
> 
> <img alt="Screen Shot 2019-04-04 at 09 28 47" width="677" src="https://user-images.githubusercontent.com/810438/55541034-118ffc00-56bc-11e9-9cc0-f04c0f7c3260.png">

This work like a charm!

**Comment by ZeldaYuan** [comment]
I solved this problem yesterday, it bothered me for half month.Yesterday I short the code to very little (just add <Provider store={store}>)and still got this invalid hook call problem.And it made me suddenly realized what mistake I did here, I didn't install the react-redux software in that folder. I have installed this software in the other project folder,so I didn't realized this one also need it.After I install it, it PASS this ERROR. Hope this advice may help someone who has the same mistake as I did before.

**Comment by qtwwyl** [comment]
> I solve this by change
> 
> ```
>                 <Route key={index} render={route.component} path={route.path} />
> ```
> 
> to
> 
> ```
>                 <Route key={index} component={route.component} path={route.path} />
> ```
> 
> but I don't know why :(

It does work for me, but I dont know why either.

**Comment by benlinton** [comment]
If you're coming here because you're using a HOC + `makeStyles` from Material UI, 
here is your answer:  https://stackoverflow.com/questions/56329992/invalid-hook-call-hooks-can-only-be-called-inside-of-the-body-of-a-function-com

**Comment by pluma** [comment]
> > I solve this by change
> > ```
> >                 <Route key={index} render={route.component} path={route.path} />
> > ```
> > 
> > 
> > to
> > ```
> >                 <Route key={index} component={route.component} path={route.path} />
> > ```
> > 
> > 
> > but I don't know why :(
> 
> It does work for me, but I dont know why either.

The "component" prop expects a React component, the "render" prop expects a function that will be invoked as a function. Function components are components, invoking them as normal functions doesn't work if they use hooks and generally isn't a good idea.

**Comment by jaisonjjames** [comment]
> I solve this by change
> 
> ```
>                 <Route key={index} render={route.component} path={route.path} />
> ```
> 
> to
> 
> ```
>                 <Route key={index} component={route.component} path={route.path} />
> ```
> 
> but I don't know why :(

Thanks, Dear, Its worked me, Still, I am confused, why?

**Comment by pluma** [comment]
@jaisonjjames see my reply. There are some explanations on StackOverflow if you have trouble understanding the difference: https://stackoverflow.com/questions/48150567/react-router-difference-between-component-and-render

**Comment by Rolando-Barbella** [comment]
In my case, I had `let match = useRouteMatch("/user/:id");` outside the component, which is a hook from react-router, so the error was right.

**Comment by gabrielyangzon** [comment]
from  
<Route path="/component" **render**={myComponent} />

to
<Route path="/component" **component**={myComponent} />

**Comment by ammoradi** [comment]
from
```js
<Route path="/component" component={myComponent} />
```
to
```js
<Route path="/component"><myComponent /></Route>
```
-_-

**Comment by AbreezaSaleem** [comment]
In my case I was referring to a library from the `window` object which had a different React version. I ended up using the `externals` configuration option from webpack which helped me refer to that library's `react` and `react-dom` and made the error go away. 

So I believe the reason I was getting this error was because `You might have more than one copy of React in the same app`.

**Comment by Myrdden** [comment]
> In my case I was referring to a library from the `window` object which had a different React version. I ended up using the `externals` configuration option from webpack which helped me refer to that library's `react` and `react-dom` and made the error go away.
> 
> So I believe the reason I was getting this error was because `You might have more than one copy of React in the same app`.

How did you accomplish this? I'm having the same issue, using a library which has `react` as an external is somehow showing up as a different version...

**Comment by JuanIrache** [comment]
I created a somewhat minimal example to reproduce this. In my case the problem happens on ElectronJS with electron-webpack and react-dropzone

https://github.com/JuanIrache/dropzone-test

**Comment by Yolantele** [comment]
a webpack solution was to add a resolutions inside the app that is using the 'to be npm module' 
inside webpack.config.js, add alias to react - so it uses that one react instance : 
```
module.exports = {
**resolve: {
    alias: {
      react: path.resolve('./node_modules/react')
    }
  },**
 // other webpack settings
}
```

**Comment by rettgerst** [comment]
lerna can cause this problem, as I've learned (lerned?) today.

lerna users, if you are developing a component library, do not include react in your library's dependencies, put it in your peerDependencies and @types/react in your devDependencies.

**Comment by jasondarwin** [comment]
For anyone using lerna, you may come across this problem when running tests in one package, where the code references components in another package.

The problem that we experienced in this case was due to react being imported in the spec, and also being imported in a component in the component tree that was using [Material UI's withStyles](https://material-ui.com/styles/api/#withstyles-styles-options-higher-order-component), which is implemented using hooks in Material UI.

It seems that react internally manages state in a `ReactCurrentDispatcher.current` variable, and this ends up getting set in one instance of react, but used in the other instance of react -- when it's empty, it throws the `Invalid hook call ...` message.

We were already using [Craco](https://github.com/gsoft-inc/craco) to override Create React App's webpack config at build time:

```
  webpack: {
    alias: {
      react: path.resolve(__dirname, './node_modules/react'),
    },
  },
```

However, this webpack override is only used at build time -- when running the tests, the code isn't built, but instantiated from source -- so our solution was to make use of [CracoAlias](https://github.com/risenforces/craco-alias) in our `craco.config.js` to specify the react path during the tests:

```
  plugins: [
    {
      plugin: CracoAlias,
      options: {
        source: 'options',
        baseUrl: './',
        aliases: {
          // We need to alias react to the one installed in the desktop/node_modules
          // in order to solve the error "hooks can only be called inside the body of a function component"
          // which is encountered during desktop jest unit tests,
          // described at https://github.com/facebook/react/issues/13991
          // This is caused by two different instances of react being loaded:
          // * the first at packages/desktop/node_modules (for HostSignUpDownloadComponent.spec.js)
          // * the second at packages/components/node_modules (for packages/components/Modal)
          react: './node_modules/react',
        },
      },
    },
  ],
```

**Comment by Ksound22** [comment]
I get invalid Hook call problem only when i use material ui, with the number one possible reason being you might have mismatching versions of react and the renderer (such as React DOM). Its been happening every time for a month now and i have no clue on a solution. I've browsed through a lot on stackoverflow but no luck.

**Comment by MeenakshiSundaram-MS** [comment]
> > My library and the create-react-app are relative to each other and I am using npm link
> 
> Did you read this part?
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
> 
> It directly addresses the `link` workflow:
> 
> <img alt="Screen Shot 2019-04-04 at 09 28 47" width="677" src="https://user-images.githubusercontent.com/810438/55541034-118ffc00-56bc-11e9-9cc0-f04c0f7c3260.png">

Thanks a lot for saving my ass <3

**Comment by mlancaster-endpointclosing** [comment]
For anyone else that end up here, I had the same issue after linking `@ui-lib` with `projectA`.

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

After arriving https://github.com/facebook/react/issues/15315#issuecomment-479802153, my first test to confirm the linking issue by removing the link `yarn unlink @ui-lib` in `projectA` and `yarn install --force` then copying the `dist` folder from `@ui-lib` into the `projectA/node_modules/@ui-lib/dist` and everything worked as expected.

So now instead of copying and pasting I can use something like https://github.com/wclr/yalc

**Comment by adderly** [comment]
I had this problem, and solved it with this:
https://github.com/facebook/react/issues/13991#issuecomment-830308729

Not so sure on the why, but it was mainly a library using expo version of rn (react-native-web was the issue i think).

**Comment by Minsoo-web** [comment]
Hello, everyone.
I hope no one makes the same mistake as me and leave this issue.

```js
import React, { useEffect } from "react";
import {useSelector} from "react-redux";

const myComponents = () => {
  useEffect(()=>{
    useSelctor(state => state.etc);
  },[]);

  return <></>;
}

export default myComponents;
```

By writing the code like this, I got into the same issue.
In my case, the problem was not the version issue of react, but the incorrect way Hooks called.

solving like this


```js
import React from "react";
import {useSelector} from "react-redux";

const myComponents = () => {
  const { etc2 } = useSelctor(state => state.etc);

  return <></>;
}

export default myComponents;
```

If you encounter the error code as above, I recommend you to check how to use Hooks again. 🙇

**Comment by dipankar08** [comment]
just delete the node_module/react from your lib and try again.

**Comment by jkalberer** [comment]
While @Yolantele's solution works when you only have a single peer dependency, you would need to do this for every peer dependency to make this work.

```javascript
const path = require('path');
const fs = require('fs');

// It would be best if you could just auto-resolve the folder names for the linked modules
const LINKED_FOLDER_NAMES = ['my-dep']
const alias = LINKED_FOLDER_NAMES
  .map(linkedDependency => {
    const rawdata = fs.readFileSync(`../${linkedDependency}/package.json`);
    const json = JSON.parse(rawdata);
    return Object.keys(json.peerDependencies || {}) || [];
  })
  .flat()
  .reduce((acc, dependency) => ({
    ...acc,
    [dependency]: path.resolve(`./node_modules/${dependency}`)
  }));

```
Config for webpack
```
webpack: {
  alias,
},
```
Config for gatsby
```
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  actions.setWebpackConfig({
    resolve: { alias }
  });
};
```

**Comment by hayesmaker** [comment]
> @types/react in your devDependencies.

do you know how to fix this if you're not using typescript?

**Comment by LiuL0703** [comment]
> > lerna can cause this problem, as I've learned (lerned?) today.
> 
> > lerna users, if you are developing a component library, do not include react in your library's dependencies, put it in your
> > peerDependencies and @types/react in your devDependencies.
> > @types/react in your devDependencies.
> 
> do you know how to fix this if you're not using typescript?

@hayesmaker  try this way [stackoverflow](https://stackoverflow.com/questions/71464758/yarn-workspaces-and-lerna-cause-invalid-hook-call)

**Comment by namanSaxena500** [comment]
![image](https://user-images.githubusercontent.com/100254651/201912986-d4342ffe-05df-44fe-b96f-819a74169d36.png)

I am unable to get console of inside my useEffect but i am getting console outside my useEffect
