### ISSUE TITLE
Devtools scrollbars should be dark in dark mode

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#17084]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When Chrome Devtools are in "dark mode", all the standard panels have a dark scrollbar:
![](https://d.sb/2019/10/chrome_14-11.53.42.png)

However, the React Devtools still show a light scrollbar:
![](https://d.sb/2019/10/chrome_14-11.55.16.png)

**What is the expected behavior?**
Scrollbars should be styled similarly to the standard panels

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Any React version
Chrome 77.0
Windows 10, version 1903.

Note: How to enable dark mode:
![](https://d.sb/2019/10/chrome_14-11.58.25.png)
![](https://d.sb/2019/10/chrome_14-11.59.29.png)

**Comment by eoandersson** [comment]
I'd love to give this one a look. That is, if no one else is already working on it.

**Comment by Daniel15** [comment]
@eoandersson - Sure! I don't think anyone is working on this at the moment. The readme has some instructions on how to build the devtools: https://github.com/facebook/react/tree/master/packages/react-devtools-extensions. Let us know if you get stuck 😄

**Comment by eoandersson** [comment]
@Daniel15 - I've got a solution working using the `::-webkit-scrollbar` pseudo element. However, I have a few quick questions. 😄

1. I'm a little uncertain as to where I should place my new `::-webkit-scrollbar` CSS. I've  currently opted to place my new lines in `react-devtools-shared/src/devtools/views/DevTools.css`, though I've also considered the possibility of other locations, such as `react-devtools-shared/src/devtools/views/root.css`. What would be the ideal solution here?

2. In terms of styling, are there any guidelines to follow? For reference as to how the solution looks now, see the image below.

![Scrollbar-Themes](https://user-images.githubusercontent.com/24208371/66872404-34be3100-efa6-11e9-8d39-4e9b2138dfb4.png)

**Comment by Daniel15** [comment]
> I'm a little uncertain as to where I should place my new ::-webkit-scrollbar CSS.

I'm not familiar with the devtools code so I'm not sure which file is best. @bvaughn might have a suggestion here. Otherwise, just place it wherever you feel is a decent place, and we can comment on it during code review 😃 

> In terms of styling, are there any guidelines to follow?

IMO, make it look like the scrollbar on the regular Chrome devtools elements tab. It's quite dark when in dark mode.

**Comment by gejimayu** [comment]
Hi guys, since it's been more than a month and there is no progress, i will give this a try

**Comment by gejimayu** [comment]
I just checked it, apparently that it's been resolved by somebody else. The scrollbar is dark now on dark theme. I think can close this issue.

**Comment by Daniel15** [comment]
I'm not seeing dark scrollbars 😕  What OS are you on?

**Comment by eoandersson** [comment]
I apologize for the delay on this one. I ran into a rather long-term hardware failure and had to have my laptop fixed, which meant that I've been unable to submit a pull request for this issue. I just recently got it back though, so I submit an initial pull request today.

As for the scrollbar, I believe the fix you're experiencing is due to a Chrome update, not React, since I can't find any pull request specifically fixing this issue. It should also be noted that I've noticed others I know have a dark scroll bar, however like @Daniel15, I do not. In addition, when the dark scrollbar some people have gets clicked and dragged the scrollbar reverts to a light one. Due to this I believe a dedicated dark scrollbar would still be preferable. Any thoughts on this @Daniel15?

**Comment by eoandersson** [comment]
While the scrollbar appears to be correctly switching between dark and light for some Chrome/OS combinations, I think that it would be preferable to set a dedicated React scrollbar to ensure consistency. To that end, I opened a pull request (#17471) to resolve this issue. Note that I still have some questions regarding code placement, so I've started a code review in the PR.
