### ISSUE TITLE
[Shallow Renderer] Plan forward

### ISSUE THREAD

**Issue by gaearon** [facebook/react#17321]
Let's discuss what to do with the shallow renderer here. As I mentioned in https://github.com/facebook/react/pull/16168#issuecomment-518344985, we aren't using it much and don't consider it a best practice. So we aren't going to be very good stewards of its API going forward.

My proposal was for Enzyme or folks interested in it to copy the code into another repo, and continue maintaining it there under a difference package name. It would make sense to Enzyme to start depending on that fork. We would then deprecate `react-test-renderer/shallow` in favor of the community-maintained fork.

If you'd like to volunteer to set up a repo, please let us know in this issue!

cc @davidmarkclements regarding the proposed `react-shallow-renderer` package name.

**Comment by ljharb** [comment]
The main concern I have isn’t maintenance of the code - it’s how it might break with new react releases.

Given that most of what the dev tools does seems to overlap with what enzyme needs, i wonder if a better path might not be in sharing those components between enzyme and the dev tools?

**Comment by gaearon** [comment]
At least for shallow renderer, I wouldn't expect breakage with new React releases because the code itself is standalone. It can *lag behind* in features but it doesn't actually depend on React internals the way the more invasive introspection does. This is because it's completely implemented from scratch and doesn't use the real codepaths.

**Comment by gaearon** [comment]
I'm not sure I see how DevTools would be helpful given that DevTools introspect a real tree — but shallow renderer is a 100% custom implementation that doesn't use any of the real reconciliation mechanisms.

**Comment by kumar303** [comment]
This [comment](https://github.com/facebook/react/pull/16168#issuecomment-518686495) about shallow renderer's dependencies implies that forking it into a standalone module would require copying/pasting a lot of core code.

**Comment by gaearon** [comment]
This is not a lot of code. Each of these is a tiny utility and they probably don't add up to more than ~200 lines.

**Comment by gaearon** [comment]
Also you can replace `invariant` with `throw Error`, `warning` with `console.error`, and `objectIs` with `Object.is`.

**Comment by ljharb** [comment]
That's a fair point; it would still be preferable to avoid it lagging behind in new features if possible.

**Comment by tomstuart** [comment]
For clarification: what is the main reason that the regular test renderer can’t support a shallow mode where composite child components are left inline instead of recursively rendered into host components? Is it for reasons of API backward compatibility, a fundamental limitation of the test renderer, a design principle, or something else?

**Comment by robertknight** [comment]
If it wasn't for the need to support the very large number of tests that I presume already exist, I think I would advocate for Enzyme to deprecate (and maybe even eventually drop) its shallow rendering mode entirely and instead document methods for users to mock at the import level [as Dan described here](https://github.com/facebook/react/pull/16168#issuecomment-518344985). Anecdotally I observed that the differences in normal vs shallow rendering in Enzyme were the source of quite a lot of confusion for other devs on my team and that led us to [replace it](https://github.com/hypothesis/client/pull/1470) with normal rendering + import-level mocking instead.

**Comment by ljharb** [comment]
@robertknight That presumes that it's actually a better pattern to do explicit import mocking of each sub-component (it also presumes that a pattern that forces jest is a reasonable thing to recommend). This isn't the place for a longer writeup of why shallow rendering is critical, a good pattern, and required for robust testing, however.

**Comment by robertknight** [comment]
> That presumes that it's actually a better pattern to do explicit import mocking of each sub-component (it also presumes that a pattern that forces jest is a reasonable thing to recommend).

I agree that both of those things would be undesirable. We automatically mock imported components using some simple heuristics rather than requiring developers to remember to configure each one. We also use a Babel plugin, which is not tied to any particular test runner, rather than Jest, to do this.

> This isn't the place for a longer writeup of why shallow rendering is critical, a good pattern, and required for robust testing, however.

That's fair enough. Perhaps I can continue the discussion in an issue on the Enzyme repo?

**Comment by Sonic12040** [comment]
Would you be willing to speak more about the automatic mocking? I'd love to learn about the flow that you've found successful and the use-cases.

**Comment by thedanchez** [comment]
@gaearon @ljharb I'd like to volunteer setting up a repo if no else will -- appreciate any direction on the details of it. But I think it's important to keep the ball moving on this endeavor and not letting it go stale.

**Comment by thedanchez** [comment]
@gaearon @ljharb Just wanted to follow up on my volunteering around this plan forward.

**Comment by thedanchez** [comment]
@gaearon @ljharb Any updates on this? I'm still waiting, willing and trying to help here.

**Comment by ljharb** [comment]
I remain happy to take over the shallow renderer, but the work to maintain it would be prohibitive unless the react team was willing to commit to helping to keep its tests passing as a precondition for any React releases (whether submitting failing test cases or notifying about upcoming failed tests with sufficient advance notice that i can make fixes, or whether making the fixes themselves)

**Comment by perrin4869** [comment]
Does this mean the shallow renderer is practically abandoned?

**Comment by JimLynchCodes** [comment]
@gaearon Myself and other engineers are using `react-test-renderer/shallow` and do consider it a best practice. Unit testing is about "testing at the edges", and philosophically a parent component should only care that its children are rendered properly _without caring about the children components'_ implementation details, and this is exactly what shallow rendering is. Do you disagree with this?

**Comment by thedanchez** [comment]
@gaearon I have to say I'm very discouraged by the lack of activity on what I think to be a very important topic of discussion here. When will the React Core Team revisit this?

**Comment by gaearon** [comment]
@thedanchez 

As far as I'm aware, there is nothing that prevents you from creating a repository, moving the code there, and releasing a package. Shallow renderer has no dependencies on the actual React implementation, so you shouldn't need our permission or assistance to start working on this.

I'm sorry I haven't replied to you earlier — as you can see, there are 476 other open issues, and notifications occasionally get lost. I wasn't actively checking this issue because, again, there is nothing from our side that prevents you from starting on this.

Let me know if there's something else you want us to revisit!

**Comment by gaearon** [comment]
cc @NMinhNguyen who also expressed interest in setting up the repository and a package. He has a good understanding of how these are set up in general, so he can help you out if you're blocked on figuring this out.

**Comment by NMinhNguyen** [comment]
@gaearon I’ll start a new repo tomorrow (ish)

**Comment by ljharb** [comment]
@gaearon it's not just about setting up a package tho; is there any interest from the react team in https://github.com/facebook/react/issues/17321#issuecomment-569324476 ?

**Comment by NMinhNguyen** [comment]
@ljharb https://github.com/facebook/react/pull/16168#issuecomment-518634232

> We'd be happy to run some tests against a separate package fwiw. Similar to how we have integration tests with `create-react-class`.

**Comment by ljharb** [comment]
Specifically, this part:

> commit to helping to keep its tests passing as a precondition for any React releases

**Comment by ljharb** [comment]
With that commitment, I'll make a repo for it this week, and start moving towards using it in enzyme.

**Comment by gaearon** [comment]
I'm not sure I understand what this means. How would a React release be able to break the shallow renderer if the shallow renderer doesn't depend on React internals?

**Comment by gaearon** [comment]
Does this sound reasonable? We already publish `@next` builds so you can use them in the integration tests. If something breaks, you can let us know here. https://reactjs.org/blog/2019/10/22/react-release-channels.html#using-the-next-channel-for-integration-testing

**Comment by NMinhNguyen** [comment]
FYI I've begun work on extracting the shallow renderer and got all tests passing locally: https://github.com/NMinhNguyen/react-shallow-renderer. Will work on setting up builds and CI etc. later this week

**Comment by ljharb** [comment]
@gaearon by changing what "rendering" means such that the shallow renderer's output no longer mirrors the React's output (for the first level, ofc).

**Comment by NMinhNguyen** [comment]
Hey @davidmarkclements, I've now set up a [new repo](https://github.com/NMinhNguyen/react-shallow-renderer) for `react-shallow-renderer`, would you be able to transfer the npm package to my username, `minh.nguyen`?

**Comment by ljharb** [comment]
@NMinhNguyen if you're interested in making it work for enzyme, please add me on github and npm as well.

**Comment by robertknight** [comment]
I mentioned in an earlier comment that we replaced shallow rendering with a different approach that provides the same benefits, using semi-automatic mocking with a Babel plugin. I found some time to write up [a blog post](https://robertknight.me.uk/posts/shallow-rendering-revisited/) with details and links to real-world examples in a reasonably complex application. We are using Preact, but the approach works exactly the same way with React. I hope this is of use to anyone who is evaluating whether to continue using the shallow renderer or do something else.

**Comment by gaearon** [comment]
This is great. Want to add a link to this plugin to our testing page where we mention module mocking?

**Comment by NMinhNguyen** [comment]
@davidmarkclements has transferred the package name to me and I've just published the initial version of it, `v16.12.0`. @ljharb I've added you on both npm and GitHub.

**Comment by ljharb** [comment]
@NMinhNguyen i've invited you to the new `enzymejs` org on github ([announcement](https://medium.com/airbnb-engineering/phase-ii-enzyme-d9efa717e297)); it'd be great to transfer the shallow renderer repo there.

**Comment by dschinkel** [comment]
I'm very disappointed in @gaearon.  The fact that you folks like integration tests vs shallow and making the assumption that this is best practice is absurd.  Many of us use shallow rendering especially as we TDD and keep our tests still decoupled, lightweight, and fast. 

Just because you, Dodds and others haven't found benefits in shallow, many of us do and have.  For you to just diss it like that, because you haven't acknowledge others do prefer shallow rendering to me is a huge disappointment to the JS community as a whole for those who do not want the ice cream cone / trophy way of test driven development or just testing in general.  I think this is a huge misstep on your part.

**Comment by nielskrijger** [comment]
@dschinkel This seems a bit harsh.

Gaearon has discussed how to use jest.mock as if you'd shallow testing; https://github.com/facebook/react/pull/16168#issuecomment-518344985

By changing tests to explicitly mock any child components using `jest.mock('Button', () => 'button')` you still get the same snapshots and much the same behaviour as when using shallow. I've been doing TDD and unit testing just fine with this approach. Granted, having to migrate 1500 tests that relied on shallow took a while (and I wasn't happy about it!), but it took a few days, not weeks due to the ease of `jest.mock`.

> How much to mock: With components, the distinction between a “unit” and “integration” test can be blurry. If you’re testing a form, should its test also test the buttons inside of it? Or should a button component have its own test suite? Should refactoring a button ever break the form test?https://reactjs.org/docs/testing.html

I agree with that statement; sometimes it's blurry, even more so when using something like styled-components. With the tools that remain you can still do both approaches, shallow is just very convenient and guarantees you're never testing more than the unit under test. In that sense it's definitely useful; but not critical to do unit testing.

**Comment by dschinkel** [comment]
**I'll leave at this and this is my last comment (I know, Thank God right? ):**

- Many of us do not want to us Jest Mocks or just mocking frameworks at all.  They impost a learning curve, magic you have to learn, etc.  The simpler you can keep your tests, the better off you are.  Shallow, while yes it mocked under the hood, kept things very very simple and minimal

- Many of us do not prefer to test through the UI like you are when we test for several good reasons.  You can get enough safety without a ton of heavy integration tests, no really...you can

- Many of us do **not** prefer to test through buttons, through forms, through web driver, through trees of components.  We prefer **not** to test mostly through "imperative shell" so much and through webdriver. We don't want to have to litter our specs by plugging holes with mocks all over the place, making our test suite brittle and complex, setup more complex, etc.  Simplicity is important on the test side, not just prod code.

If you want to know who the "many of us" I'd be happy to start listing those I know who prerfer not to test through the browser or through trees of components via a heavy UI integration test way.  There are other ways to TDD the FE, not just what React tells you to do.

Those who TDD (I don't care if you don't, I am not here to stir you up), at least where I come from look for more than just "does it work".  

**When we write tests want:**

- **fast** feedback on **"does it work"**

- **lower** level **design feedback/pressure** that gives us smells when prod design is decoupled and not simple

-  **lower**-level **feedback** on "**where** did the problem happen and why"

-  **narrowly scoped** outside tests at the component level; keep components dumb even in containers or hooks, and we don't need to test the wiring "use it as a user" because in the past it's been shown that the ice cream cone really just leads to more pain
- "narrowly scoped" unit tests that sit below components (no this is not over testing) at _some_ (not all) layers that sit below UI components

So many are assuming everyone just wants to test that way. That is not the case which means a framework, any codebase should be flexible enough to invite and allow other approaches in testing to take place without a huge amount of friction.

The point here is that there are other approaches that the community is shunning and just carelessly discounting, and that's not good for the profession as a whole.

**Comment by Sonic12040** [comment]
I apologize, but I don't quite understand where you're coming from, and would like to obtain clarity.

The way I understand things, Dan was saying that because they are moving away from the shallow testing methodology, they would not be continuing work on the shallow renderer.

As a result, the shallow renderer has been spun into its own repository, and React will continue with their recommended approach. Also above is a blog on the semi-automated mocking approach employed.

I think this is a good compromise, with the shallow renderer moved into a package where teams using it can continue to receive support.

Can you help me understand the part I'm missing?

**Comment by dschinkel** [comment]
I just get tired of the discounting of shallow by some of the React maintainers and React team TBH.  Just wanted to speak out on it here.  They should be helping to support it IMO even if they don't write tests that way, their API needs to make things easier for those who do want to test other ways.  Instead we're having to continually work against the React API to keep that in place and the fact that the React team in general opposes shallow rendering doesn't help the cause.

**Comment by gaearon** [comment]
Over the years, the shallow tenderer has stagnated. This was partially because we don’t use it ourselves anymore. So it’s difficult for us to make any design decisions around it (how to represent context in it? how should it work with refs and effects?).

Some people, including you, clearly find it useful. That’s great. The point of moving it out of the repository was to **let folks who want to work on its design and implementation do exactly that without waiting for us**. Now it’s fully decoupled so you’re welcome to file issues on that repository and help maintain and design it. I’m not sure what you’re unhappy with — that seems like the outcome most aligned with your preferences.

You said that we design APIs with not enough regard for testing. I don’t believe this is true. But if you have any specific feedback you are always welcome to express it as a comment on the relevant RFCs: https://reactjs.org/blog/2017/12/07/introducing-the-react-rfc-process.html.

What I ultimately hear from your message is you’re unhappy with us not specifically *recommending* shallow rendering. That’s okay. We all have opinions informed by our experience, and we need to be accepting of these differences. If shallow renderer serves you well, you are always welcome to become more involved in its design and development. That’s what extracting the repo was for.

**Comment by dschinkel** [comment]
Thanks for understanding Dan.

**Comment by mikeborozdin** [comment]
@dschinkel ,

I'm a big fan of TDD and I use shallow rendering a lot. So I created a library that brings hooks, such as `useEffect()` to shallow rendering - [jest-react-hooks-shallow](https://github.com/mikeborozdin/jest-react-hooks-shallow).

That said, once the shallow renderer is a proper standlone library, it'll be possible to extend it. So that we don't even have to rely on my library.

**Comment by gaearon** [comment]
>So I created a library that brings hooks, such as useEffect() to shallow rendering - jest-react-hooks-shallow.

Btw I found this wording a bit confusing in announcements, since shallow renderer supports Hooks perfectly fine. It doesn't support *effects* specifically — not because it's hard to do, but as a design decision — just like it never supported running `componentDidMount/Update`. Those methods tend to use refs so we don't think it makes a lot of sense to run them with shallow rendering.

I know Enzyme has a different stance on this (partially stemming from a misunderstanding where folks working on it thought refs might be null in `*Did*` methods so good code would guard against null refs regardless). But it's a bit misleading to say shallow renderer "didn't support Hooks".

**Comment by dschinkel** [comment]
@gaearon 
>shallow renderer supports Hooks perfectly fine

What a lot of us want to do is test the public API directly on instance like we were able to with classes.  A lot of us **don't** care to test everything through button clicks or the DOM wiring and we have a way that does not test "implementation details" which seems to be a big catch-all term to kill conversations around not using heavy tests IMO.  

Anyway, Hooks does not let you do this.  It appears to literally prevent you from doing so, from accessing the actual hook in terms of specifying some internal subset of functions to be part of the public API that shallow or mount can try to access.  I don't want to get into this "testing implementation details" argument because that's a big conversation and that truly depends on how you are writing your tests and WHAT you deem as the public API.

**Comment by dschinkel** [comment]
@mikeborozdin @NMinhNguyen
Appreciate your efforts so far.

The way some of us test, and I know others are that we don't like testing through so much imperative shell, or in other words so much of the DOM wiring.  Contrary to popular belief, a lot of us bypass that and get enough confidence testing a small part of the public API (e.g. Domain methods in the component) as the "contract" and we don't view the full UI as the "contract".   So when we render we actually have a good approach to shallow rendering then calling instance methods (the public API that we do decide to expose without exposing implementation details) from our shallowed tests.  So right now I can't really use your contributions because it still blocks the approach of testing under the skin a little.

make sense?
