### ISSUE TITLE
[DevTools] Cannot type into search box in Firefox when browser find-as-you-type setting enabled

### ISSUE THREAD

**Issue by swrobel** [facebook/react#17719]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
1. Enable Firefox Preferences > Browsing > Search for text when you start typing
<img width="455" alt="Screen Shot 2019-12-26 at 10 56 15 AM" src="https://user-images.githubusercontent.com/157270/71487107-65a0ba80-27ce-11ea-967c-4e9271ae4c22.png">
1. Open React Devtools
1. Note that you can paste text into the search box, but keyboard input will not show any input
1. Disable above setting
1. Note that Devtools search accepts keyboard input

**What is the expected behavior?**
1. Components search works regardless of find-as-you-type setting

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Firefox 72.0b10 on macOS 10.14.6
Devtools 4.3.0

**Comment by swrobel** [comment]
Possible fix: Use `event.preventDefault()` as [recommended by FF developers](https://bugzilla.mozilla.org/show_bug.cgi?id=269516#c1) within [SearchInput.js](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/devtools/views/Components/SearchInput.js)

**Comment by bvaughn** [comment]
I'm not familiar with the "Search for text when you start typing" feature. Sounds kind of annoying 😅 I imagine a lot of input elements would break it?

Anyway since you seem to have the most context here, would you be willing to submit a PR with the change you're suggesting?

**Comment by victorkane** [comment]
I have this problem and don't understand concretely what to do as per @swrobel's recommendation. The inability to search components in the component view (which is happening to me in Mozilla but not in Chrome) is tantamount to not using the dev tools at all in Mozilla. Please take this report seriously, instead of snidely asking for PR's like @bvaughn

**Comment by bvaughn** [comment]
I'm not sure which part of my response above struck you as "snide", @victorkane :smile:

Literally millions of people use React DevTools and literally only one person (me) regularly contributes code to it. I can't keep up with bug reports and feature requests, and in some cases I rely on people who have more context to chip in and help fix/test things.

Encouraging users to submit PRs is a healthy part of open source.

**Comment by victorkane** [comment]
@bvaughn "Encouraging users to submit PRs is a healthy part of open source." Absolutely, absolutely, but in the appropriate context. If millions of people use react dev tools perhaps more should be done to encourage the formation of a community of developers... What I'm saying is that the bug (or lack of configuration) mentioned here should also be taken seriously, and perhaps an effort should be made to include more people capable of a solution. Not being able to use the search bar tool in Component view has an extremely high impact, and wastes the work being put into the extension (for Mozilla). Thanks for all your hard work on this.

**Comment by bvaughn** [comment]
I wouldn't characterize the impact of this bug quite that strongly. I'm under the impression that it only affects users who have enabled the "*Search for text when you start typing*" option. (It's disabled by default.)

I've added the "good first issue" tag just now to let folks know that we'd accept PRs for this. Beyond that, I'm not sure what more to do to encourage folks to look at this. I don't think we need to ping any browser vendors or anything, since a likely solution seems known. It's more just a matter of implementing it and testing it. :smile:

**Comment by victorkane** [comment]
@bvaughn So:

> I wouldn't characterize the impact of this bug quite that strongly. I'm under the impression that it only affects users who have enabled the "Search for text when you start typing" option. (It's disabled by default.)

* What about the users who want to enable "Search for text when you start typing" option??
* How would users, especially beginners, even know this???

**Comment by bvaughn** [comment]
I'm not sure how to respond to this thread, @victorkane. Would you be interested in contributing a PR for this? I'd be happy to review it promptly. Thoroughly testing it is the thing I'd need the most help with to be honest.

For some insight into how I (internally) prioritize bugs like this: React DevTools has a couple million active users, but the Firefox extension accounts for < 5% of them. And of that 5%, only people who have enabled the "*Search for text when you start typing*" option will be impacted by this bug. I understand that it's a poor user experience. I don't mean to be discounting that. I just don't think it invalidates the extension or the work put into it.

> How would users, especially beginners, even know this???

The same way you found this thread :smile:

**Comment by M-Izadmehr** [comment]
I would like to take a look at this issue, if possible:)
 @bvaughn

**Comment by bvaughn** [comment]
This issue is all yours, @M-Izadmehr 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by KevinKelbie** [comment]
Hi @bvaughn, there hasn't been much activity here in a few days and I was wondering if I could take on this issue. I have implemented a fix for it and tested it in Firefox and it seems to be working. One thing I'm not sure about is how I would go about adding a test for this because it requires enabling a setting in firefox.

**Comment by M-Izadmehr** [comment]
@bvaughn,
Hey, Thanks for the opportunity.
I am working on the issue right now, I got familiar with the code base, and @swrobel is right the issue is probably caused by the lack of `event.preventDefault`.
I was able to run the standalone electron devtools for debugging, I still don't know how I can use my own local devtools directly on firefox. 
Is there any docs that I can follow?:)

**Comment by M-Izadmehr** [comment]
@bvaughn I did dig a little bit about this issue.
It seems to be an internal bug in firefox itself, it bocks inputs (just in devtool extensions) to receive the following events/cases:
1. onchange
2. oninput
3. contenteditable elements

However, the following events are working fine:
1. onclick
2. oncut/onpaste
3. onKey events

Also, adding `event.preventDefault` does not solve the issue because the element does not receive the event in the first place to be able to run the callback function on that.
I also created a simple Firefox devtool extension to test it with vanillaJs, the problem also exists there too.

One probable solution is to write an eventlistener for keyDown, and simulate onChange, it is possible but I guess it will be an overkill.

I also reported this on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1610141)

**Comment by bvaughn** [comment]
Thank you for the detailed follow up @M-Izadmehr! and thanks for filing an issue on bugzilla! 🙇

Given what you said, let's wait and see what the Firefox folks say about this before making any changes on our end.

**Comment by bl00mber** [comment]
Thanks for the fun that I had reading this profound conversation! :joy:

**Comment by M-Izadmehr** [comment]
I have some news:)
The cause of this issue inside firefox was that the FindBar internals intercepted the events, and then they call [`event.preventDefault()`](https://searchfox.org/mozilla-central/rev/fca0be7e2cf2f922c9b927423ce28e8a04b3fd90/toolkit/modules/FindBarContent.jsm#95), and so the extension page never receives those events.

After a lot of discussions that you can follow [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1610141) the issue is now fixed and already deployed to the latest version of firefox nightly (as you can see in the gif, now both findbar and devTool search works).

I think now we can move on and close this issue.

![ezgif-7-b7d1719a6f22](https://user-images.githubusercontent.com/28848972/78253841-4f08ae80-74f5-11ea-8927-d2a573e902a7.gif)

**Comment by bvaughn** [comment]
Thanks for the update, @M-Izadmehr!

Closing!
