### ISSUE TITLE
`displayName` from memoized components should be taken into account in DevTools

### ISSUE THREAD

**Issue by CarlosGines** [facebook/react#18026]
If you create a component via `React.memo` and then explicitly provide it with a `displayName`, DevTools ignore this display name.

React version: 16.12.0
DevTools version: 4.4.0

## Steps To Reproduce

1. Create a component like:
```tsx
const FancyMemoComponent = React.memo(() => 'Check my name in DevTools')
```
2. Provide it with a `displayName`
```tsx
FancyMemoComponent.displayName = 'FancyMemoComponent'
```
3. Check its name in DevTools.

Link to code example: https://codesandbox.io/s/react-memo-display-name-vk7gv

## The current behavior

DevTools do not display the given `displayName`.

## The expected behavior

DevTools should display the given `displayName`.

## Comments

I am aware that the name can be picked from the function inside `React.memo`, but I prefer using anonymous functions.

I am using this workaround:
```tsx
FancyMemoComponent.type.displayName = 'FancyMemoComponent'
```

**Comment by moonrailgun** [comment]
Same problem in https://github.com/facebook/react/issues/17876

They dont recommand modify `type` . And its not support in `typescript`
I am try to persuade offical to think about it and have not reply yet

**Comment by moonrailgun** [comment]
I have a alternative solution to fix it by myself when React have not fix it

```typescript
import React, { PropsWithChildren, SFC } from 'react';

export const MyMemo = <P extends object>(
  Component: SFC<P>,
  propsAreEqual?: (
    prevProps: Readonly<PropsWithChildren<P>>,
    nextProps: Readonly<PropsWithChildren<P>>
  ) => boolean
) => {
  const memoized = React.memo(Component, propsAreEqual);

  Object.defineProperty(memoized, 'displayName', {
    set(v) {
      Component.displayName = v;
    },
  });

  return memoized;
};
```

Its easy to replace and not change any api

**Comment by drager** [comment]
Would be great if the displayName become something like: `Memo(ComponentName)`. At the moment memoized components will be displayed as `_c2`, `_c3`, etc in Chrome devtools when profiling which is somewhat cumbersome.

![image](https://user-images.githubusercontent.com/1957563/80678942-2f48b400-8abc-11ea-88e4-1b6ee0095bb2.png)

**Comment by idmadj** [comment]
The expectation that regular named functions should be used along with memo is less than ideal. Regular functions are not equivalent to arrow functions and a lot of us use arrow functions exclusively because they are more concise, more expressive and discourage the use of `this`. People shouldn't need to switch to regular functions only to be able to have the component names displayed in dev-tools .

This could be fixed by having memoized component look into the displayName property for their name as @CarlosGines suggests, or by adding an optional parameter to memo() to specify the name.

**Comment by idmadj** [comment]
#18495 will fix this.

**Comment by kerams** [comment]
@idmadj, still see this in 4.7.0 released the other day, so I assume it didn't.

**Comment by vasilii-kovalev** [comment]
I can see that when using `React.memo`, [why-did-you-render](https://github.com/welldone-software/why-did-you-render) library displays the component's name as `undefined`.
```jsx
const SignInFormPure: React.FC = React.memo(() => {
  ...
});
```
![image](https://user-images.githubusercontent.com/10310491/90565201-30a70500-e1af-11ea-9a81-70e06dc8bfd9.png)

Does #18495 fix this?

**Comment by eps1lon** [comment]
This issue is fixed in the latest release candidate for React 17. You can try it out with by installing `react@next` and `react-dom@next`. I created a [codesandbox using displayName on React.memo](https://codesandbox.io/s/react-17-memo-displayname-23qrs) to showcase the fix.

**Comment by lishoulong** [comment]
> This issue is fixed in the latest release candidate for React 17. You can try it out with by installing `react@next` and `react-dom@next`. I created a [codesandbox using displayName on React.memo](https://codesandbox.io/s/react-17-memo-displayname-23qrs) to showcase the fix.

Hi, This bug is not fixed in your codesandbox.

**Comment by skmohammadi** [comment]
Not working

**Comment by Scalahansolo** [comment]
This is still an issue as outlined by the linked sandbox. Not solved.

**Comment by easyTree** [comment]
> This issue is fixed in the latest release candidate for React 17. You can try it out with by installing `react@next` and `react-dom@next`. I created a [codesandbox using displayName on React.memo](https://codesandbox.io/s/react-17-memo-displayname-23qrs) to showcase the fix.

The App memo shows as "_c [Memo]" ([] are my attempt to simulate a block with background-color set)
