### ISSUE TITLE
React retains component references to old renders causing browser memory to increase

### ISSUE THREAD

**Issue by tsjohns9** [facebook/react#18116]
React version: 16.12.0

## The current behavior
React appears to retain references to old renders of components which prevents the browser from running the garbage collector on unused memory.

## The expected behavior
React should release the memory of components from previous renders

## Description
I have a web app that imports an OAS 3/Swagger 2.0 json spec file, and renders the file using the swagger-ui component, https://github.com/swagger-api/swagger-ui.

These json files can be very large. If I upload a file that is 350mb and pass it into the swagger-ui component the heap snapshot in chrome will show about 32.6 MB being used to render the app.

At some point during the lifecycle of this component the spec file may be updated by a user. When this happens the swagger-ui component will re-render. Between re-renders I can see from my heap snapshot that about 15 more mb are added to the heap. 

I would expect that after a re-render the heap size would be about the same, and the old references would be released for garbage collection.

I have come here with this issue and not swagger-ui because based on the heap snapshots the detached DOM elements are being retained by React directly.

The spec file that I have used is about 350 mb. Unfortunately it is a proprietary file and I cannot share it here. Instead, I have provided a spec file from swagger-ui. This file is much smaller, but it will serve the purpose of showing how react is retaining references to old component renders. In my situation since the file is so large this becomes much more apparent to the user that there is a problem than with a much smaller json file.

![Screen Shot 2020-02-24 at 1 17 42 PM](https://user-images.githubusercontent.com/24981281/75188107-c97d2c00-5708-11ea-95dd-7320d75cbf99.png)
![Screen Shot 2020-02-24 at 1 21 30 PM](https://user-images.githubusercontent.com/24981281/75188095-c2eeb480-5708-11ea-9ede-c6f29452dde5.png)

## Steps To Reproduce
1. Download the sample github repo here: https://github.com/tsjohns9/react-memory-leak
2. Run the app
3. Open the console, and take a heap snapshot
4. Press the Update Spec button in the top left of the app
5. Take another heap snapshot.
6. You will see that the heap size has increased
7. Compare the two heap sizes and check to see how many new detached objects there are. Here is a screenshot as an example
![Screen Shot 2020-02-24 at 1 26 19 PM](https://user-images.githubusercontent.com/24981281/75188470-6c35aa80-5709-11ea-956b-61022e80fa4b.png)

Link to code example: https://github.com/tsjohns9/react-memory-leak

**Comment by jddxf** [comment]
Does https://github.com/facebook/react/issues/18066 help?

**Comment by tsjohns9** [comment]
That issue seems similar. I downloaded the version that was linked for the fix [here](https://codesandbox.io/s/naughty-kalam-qg096) as part of #17666, but I am still seeing the memory leak.

**Comment by jddxf** [comment]
Did you open it in standalone [app](https://qg096.csb.app/) view? In my test, there was almost no leak.
![image](https://user-images.githubusercontent.com/11155177/75268769-eada3700-5832-11ea-98cf-ffb65c98a15f.png)

**Comment by tsjohns9** [comment]
The issue I have seems different than the one you have linked too. I am still working to more closely identify what is happening. I will post back here when I know more about what is happening.

**Comment by tsjohns9** [comment]
I am still seeing a problem with detached dom elements. If you download the github repo I linked to start the app. Take a snapshot. Press the mount button. Take another snapshot. Then unmount and take another snapshot. You will see that the component is no longer in the dom, and yet the memory hardly went down. It looks to me like React is holding onto these elements and is the source of the leak. Please correct me though if I am wrong on that.
![Screen Shot 2020-02-28 at 11 44 42 AM](https://user-images.githubusercontent.com/24981281/75577783-f63e8580-5a1f-11ea-9cfb-44ec84ac194c.png)

**Comment by tsjohns9** [comment]
I have deployed the demo [here](https://tsjohns9.github.io/react-memory-leak/) for your convenience,

**Comment by jackple** [comment]
Is there any solutions?

**Comment by shenzekun** [comment]
I also encountered this problem

**Comment by jianfenkezhan** [comment]
react@16.13.1
react-dom@16.13.1

 I am still seeing the memory leak.

**Comment by Regaddi** [comment]
Here is a minimal reproduction demonstrating the issue on a `HTMLVideoElement`:

https://codesandbox.io/s/upbeat-butterfly-vchn2?file=/src/App.js

Using react and react-dom 17.0.2.

I was testing in Chrome 92.0.4515.107 on macOS Big Sur 11.4 (20F71).

**Comment by vespasianvs** [comment]
Just wondered if there had been any progress on this issue? Also experiencing it as an issue on our app which eventually causes the browser to run out of memory. Is there even a temporary workaround?

**Comment by gaearon** [comment]
React 18 clears up memory more aggressively. Can somebody please check if this is still as severe?

**Comment by miklosme** [comment]
@gaearon We had a memory leak bug report. Although I couldn't reproduce a crash, I saw a lot of uncollected FiberNodes in the memory profiler. After a 17.0.2 -> 18.2.0 upgrade it looks significantly cleaner now:

17.0.2
<img width="999" alt="Screen Shot 2022-09-13 at 6 07 40 PM" src="https://user-images.githubusercontent.com/8769273/190172785-1c7f4f5e-2f4c-4cfb-80d8-9b99c6703d47.png">

18.2.0
<img width="986" alt="Screen Shot 2022-09-13 at 6 21 27 PM" src="https://user-images.githubusercontent.com/8769273/190172795-8743a825-e7c7-4da6-a636-43bfa9dd6a23.png">

**Comment by James-Hill-Fox** [comment]
Eventually figured out our issue that was presenting like this was solved by disabling react-dev-tools chrome extension when running the profiler.
