### ISSUE TITLE
Bug: React devtools shows "Unable to find React on the page" Incorrectly

### ISSUE THREAD

**Issue by Eddie-CooRo** [facebook/react#18705]
React version: 16.12.0
Devtools version: 4.6.0

## Steps To Reproduce

Don't know.

## The current behavior
React devtools shows "Unable to find React on the page" in the inspector Components pane. The website is a plain CRA app and the devtools is able to detect that the website is using a development build of the react when I click on the devtools icon in the browser extensions bar. I'm able to see the Components when I use devtools on a website other than mine (like reactjs.org). My app is served using the default `react-scripts start` command.
I don't know what exactly is causing the issue but I can share logs or whatever that help to pinpoint the issue as you request.
![Screenshot from 2020-04-23 00-51-25](https://user-images.githubusercontent.com/20463083/80030112-01cc9b00-84fd-11ea-90ac-220e5bb2eed4.png)

**Comment by Eddie-CooRo** [comment]
Update: everything works without problem on the standalone app

**Comment by Nilomiranda** [comment]
Is your project in a public repository?

**Comment by Eddie-CooRo** [comment]
Hey @Nilomiranda 
Unfortunately, its not.
Is there any specific part that you want to check?

**Comment by bvaughn** [comment]
Not sure how to reproduce this. Can't say I've seen it.

Can you share a minimal repro? Just start ripping things out of your app until the behavior no longer reproduces, and share just the code necessary for it? (Shouldn't require you to share anything secret that way.)

**Comment by Eddie-CooRo** [comment]
Ok. it seems to be working fine after restarting my system :joy: thank god I have a screenshot to prove that the issue existed at some point in time :joy:
I'm going to close this issue for now and reopen a new one if I found any new data about it (I'll try checking out some previous commits tomorrow) :(
but at least now we know that this issue can probably be fixed by restarting the OS :)

**Comment by bvaughn** [comment]
Ah, well that's interesting 🤔 

Glad restarting stuff fixed it for you!

**Comment by balazs31** [comment]
I'm having exactly the same issue. Unfortunately restarting the system does not fix it. Using Chrome for Developers on MacOS Catalina.

**Comment by fridaystreet** [comment]
same here, and since the recent chrome update debugging in inspect is completely screwed. Suspecting latest chrome update has broken things

**Comment by Eddie-CooRo** [comment]
@fridaystreet Yeah it happened to me again too. But I haven't re-opened this issues since I wasn't able to find a way to reproduce it so far :(
Every time I come across the issue and try to find the root cause of the problem, after the first reload the extension starts working correctly again.

**Comment by krnlde** [comment]
Same here in Chromium Edge 84.0.508.0 on Windows 10.
It randomly disconnects when the BrowserSync reloads the page. I will then have to close and reopen the browser.

**Comment by Eddie-CooRo** [comment]
I was using the unstable channel of the chrome on Linux when I reported the issue. I'm suspicious that maybe that's the root cause of the issue because I also had some other issues and bugs on the Spotify and codesandbox websites that have got fixed since I changed to the stable channel.
@balazs31 I'm seeing that you are using Chrome for Developers and @fridaystreet has said something about the latest chrome update. are you getting your updates from the unstable channel too?

**Comment by franjorub** [comment]
Same issue here with mozilla firefox 76.0 windows 10, stop working in incognito mode

**Comment by franjorub** [comment]
Same issue here with mozilla firefox 76.0 windows 10, stop working in incognito mode
the extension read that I'm in a development site 
![imagen](https://user-images.githubusercontent.com/24401350/81485817-312e1800-921e-11ea-8132-3c672fc5717f.png)
but displays this in the developer tools
![imagen](https://user-images.githubusercontent.com/24401350/81485822-3a1ee980-921e-11ea-8a3f-663b9cc86d87.png)

**Comment by crazyrabbitLTC** [comment]
I am also having this problem. 

Version 83.0.4103.61 (Official Build) (64-bit)

OSX 10.151 Catelina

**Comment by krnlde** [comment]
Maybe re-open this issue?

**Comment by jraut** [comment]
I have had the same issue during past two weeks. Restarting the browser fixed it.

Chrome Version 85.0.4183.83 (Official Build) (64-bit)
OSX 10.14.6 Mojave

**Comment by damiannmm** [comment]
I think this problem is reproducible using Firefox's Private Window.


<img width="1440" alt="Screen Shot 2020-12-08 at 5 58 17 PM" src="https://user-images.githubusercontent.com/1107336/101475460-073cff80-397f-11eb-9157-17656de375dd.png">

**Comment by bernardogarza** [comment]
I have the same problem with private windows on Firefox and Firefox Developer Edition, the extension works on Vivaldi (chromium) private window tho.

I'm running Ubuntu 20.04 and everything is up to date.

**Comment by darelover** [comment]
I am facing the same issue with firefox private window on macos catalina

**Comment by vinodcg2** [comment]
I was also having same issue, I removed the addon and add again fixed for me. 

For removing and adding path : https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/related?hl=en

[](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/related?hl=en)

**Comment by kevireilly** [comment]
Closing the affected tab and/or opening a new tab worked for me.

**Comment by DennisHuallanca** [comment]
Same issue with Microsoft Edge, Versión 91.0.864.48

**Comment by kc-beard** [comment]
osx 10.15.7 / chrome 94.0.4606.81

closing/reopening tab worked for me

**Comment by ZT-UC** [comment]
None of the above solved the issue for me.
macOS 11.6 / firefox browser 94.0.1

Any idea what to try next?

**Comment by Aniganesh** [comment]
Having the same issue on MacOS12.2.1 98.0.1
Quitting firefox and opening it again didn't solve the issue for me.

**Comment by nathan-jahn** [comment]
Having the same issue, using Firefox Developer Edition. An example website that produces this issue is https://www.airbnb.com Firefox Dev Edition does not detect React while Chrome does.

**Comment by rasmusParkering** [comment]
I have this issue often. Happens like 30% of the time. Then i can close Edge, open my enviroment again, and then it will work again. But it will still happen shortly afterwards..

**Comment by SilenceMonk** [comment]
> I have this issue often. Happens like 30% of the time. Then i can close Edge, open my enviroment again, and then it will work again. But it will still happen shortly afterwards. Its un-useable for me in this state

same here with chrome, restarting browser seems to solve the issue
