### ISSUE TITLE
Bug: Input minLength not working after type changed

### ISSUE THREAD

**Issue by Vandoct** [facebook/react#20161]
I have an input with type password with minLength 8, and i have a toggle to change the type to text (password toggle).
when i type with length < 8 and press submit, it prevent to submit. but, when i toggle the password so it change the type to text and submit the form, it can submitted. btw i using useRef()

React version:
react: ^17.0.1
react-dom: ^17.0.1

## Steps To Reproduce

1. type character < minLength
2. submit form
3. toggle form type
4. submit form

Link to code example: [DEMO](https://codesandbox.io/s/young-shape-4tciw)

## The current behavior
The form get submitted even when it under minLength

## The expected behavior
The form not get submitted when it under minLength

**Comment by eps1lon** [comment]
Thanks for the report.

I can spot two issues:
1. your demo uses `minLength="3"` not 8.
   Typing less than 8 characters is fine as long as you type more than 2
1. `minLength` is not supported in IE 11: https://caniuse.com/input-minlength
   I tested your demo in Chrome 85 and could not submit when I entered less than 2 characters

**Comment by Vandoct** [comment]
I'm using browser Safari 13.0.5 (14608.5.12)

i forgot something, don't type any characters after toggle it

## Steps To Reproduce 1
1. type character < minLength
2. submit form
3. toggle form type
4. dont type anything after toggle
5. submit form
6. the form will submitted

## Steps To Reproduce 2
1. type character < minLength
2. submit form
3. toggle form type
4. type anything after toggle
5. submit form
6. the form will not submitted

**Comment by eps1lon** [comment]
Thanks!

Generally any validation is ignored if the input is pristine. If you submit the form without typing anything the `minLength` is ignored.

Safari properly marks the form as invalid if you typed something that doesn't pass all constraints. However, when the `type` changes Safari seems to consider the input pristine. Therefore an invalid value is submitted if the `type` changed after typing is complete.

The question is if React can or should fix this quirk or whether Safari should fix this.

**Comment by o-dubrovskyi** [comment]
I reproduced issue in Safari Version 15.5 (17613.2.7.1.8).

This behaviour is reproducible with native javascript so i feel like this case should seen by Safari

**Comment by Piotr-Kniaz** [comment]
This bug still reproducible in Safari 17.6 (19618.3.11.11.5)! I think the problem is related to WebKit.
