### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by burhanbvk** [facebook/react#22214]
When you make a nested ReactDOMServer.renderToString call (i.e. call ReactDOMServer.renderToString from within a component rendered using ReactDOMServer.renderToString), you can not use any hooks after the second call. Custom hooks work, but React hooks throw a invalid hook call error.
Not sure if this is an acceptable use case for ReactDOMServer, this is how a current project is setup, I am just making some additional hook calls and encountered this error. I have replicated the issue on a fresh React app with nothing else.

React version: 17.0.2

## Steps To Reproduce

1. Createa a component, ComponentA
2. In ComponentA make a call to ReactDOMServer.renderToString, and then use a React hook (useState, useContext etc.)
3. In the main app render ComponentA via ReactDOMServer.renderToString (ReactDOMServer.renderToString(<ComponentA />)

Link to code example: https://codesandbox.io/s/sweet-kate-etr68
## The current behavior
Throws an invalid hook call exception

## The expected behavior
Work as usual, hooks working as normal.

**Comment by bvaughn** [comment]
IMO bug reports without titles are less likely to be looked at. You might want to update it.

**Comment by burhanbvk** [comment]
Thanks!

**Comment by gaearon** [comment]
Do you want to send a fix? We're probably not restoring the "current dispatcher" somewhere.

**Comment by burhanbvk** [comment]
That was my initial suspicion as well but it doesn't seem to be case. It is the `resetHooksState` being called and setting the `currentlyRenderingComponent` to null, triggering this error. I am still figuring out the exact lifecycle of the `renderToString` function, but I should be able to come up with a fix.

**Comment by burhanbvk** [comment]
I can provide a fix, but I couldn't create a test case for it. I couldn't replicate the issue on the test environment, it didn't cause an exception there.

The fix involves using a `renderingComponentStack` array to store `currentlyRenderingComponent` variables at each nested call.

**Comment by burhanbvk** [comment]
I can fix this by directly modifying the built `\react-dom\cjs\react-dom-server.browser.development.js` file, but can't add these changes to the repo. I have modified the `packages\react-dom\src\server\ReactPartialRenderer.js` and the `packages\react-dom\src\server\ReactPartialRendererHooks.js` files to add these changes, and then did a `yarn build`, but these changes didn't show up in the built files. I tried clearing the cache, deleting node_modules folder etc. But the built files never change. I haven't contributed to React repo before, probably doing a very simple mistake.

**Comment by gaearon** [comment]
Where are you looking for the build output?

**Comment by burhanbvk** [comment]
`build\node_modules\react-dom\` folder

**Comment by burhanbvk** [comment]
My first clone of repo had some issues, I started over with a fresh clone. And it appears that this issue is now fixed in the main branch. Is there a schedule for the next release (v 17.0.3 or 17.1.0)=

**Comment by dan-newscorp** [comment]
+1 I'm getting this error in my project too. Is there an update on when it'll be released please?

**Comment by gaearon** [comment]
I don’t think this is fixed.

**Comment by Shal31** [comment]
+1 , I am using react 18.2.0 and still getting this error . Is there any fix available for same or any alternative way to implement?

**Comment by m-a-r-c-e-l-i-n-o** [comment]
I can also attest that this continues to be an issue in `react-dom/server` v19.1.1
