### ISSUE TITLE
[DevTools Bug] Children cannot be added or removed during a reorder operation.

### ISSUE THREAD

**Issue by HamaydaGabsi** [facebook/react#25007]
### Website or app

https://github.com/HamaydaGabsi/Color-Project

### Repro steps

1. Select a palette
2. Select to color to view shades
3. Go back to the colors with the navigation arrow

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.25.0-336ac8ceb

### Error message (automated)

Children cannot be added or removed during a reorder operation.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26848:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24626:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24795:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54959:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Children cannot be added or removed during a reorder operation. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! I tried to test out your project, but I only see the create react app logo.
![image](https://user-images.githubusercontent.com/2735514/181801984-f8cef477-bece-4c21-a781-87fd82ef40e9.png)

could you upload a version of your app on github or codesandbox so we can debug further? Thanks!

**Comment by hanswang123456** [comment]
Is your app something that resembles this? https://reactjsexample.com/create-a-make-your-own-color-palette-app-using-react-framework/--->github:https://github.com/Colt/react-colors

**Comment by j56xie** [comment]
I've runned into the same issue recently and mine was caused by duplicate keys when mapping a list of items into renders function. Fixed the issue by update keys to use unique identifier.

**Comment by MidnightTinge** [comment]
Just had this pop on our codebase while refactoring some old code. This seems to be an issue with rendering sub-components with duplicate keys in the devtools.
I've uploaded an MRE here: https://github.com/MidnightTinge/gh-react-25007

The way to trigger the error is to flip the `<Item/>` component's `key` prop value from `key` to `value`. This should trigger the error, and the button on the page automates this process.

After re-reading I realized my naming was probably confusing. To trigger the specific error, the keys need to go from duplicate to non-duplicate while the devtools are open.

**Comment by hrasekh** [comment]
I had the same issue and it was because I had multiple list item with the same key value, so during the update it was behaving incorrectly and throwing this error.

**Comment by navneetMukrah** [comment]
I also had the same issue i fixed it by giving unique id to key .

**Comment by ChichebeDarlington** [comment]
unique id is the solution, just fix mine now

**Comment by HamaydaGabsi** [comment]
> I've runned into the same issue recently and mine was caused by duplicate keys when mapping a list of items into renders function. Fixed the issue by update keys to use unique identifier.
This is the solution

**Comment by MidnightTinge** [comment]
not having duplicate keys is react 101 (and an easy mistake to make, I still oppsie that one myself sometimes while prototyping 😁) so while it may mask the underlying issue, this is technically not resolved until devtools specifically don't report it as a problem. this doesn't appear to be anywhere on the team's radar, but the ticket should probably stay open until that happens

**Comment by NSENGIYUMVA-Christian** [comment]
I'm having the same, error but even when I use unique ID with uuid package still it doesn't work. I'm trying to map the list

**Comment by NSENGIYUMVA-Christian** [comment]
Oh

> I'm having the same, error but even when I use unique ID with uuid package still it doesn't work. I'm trying to map the list

Oh, later it worked. Just by using unique ID
