### ISSUE TITLE
Stoped working on chrome 102 please fix it (DevTools version: 4.27.0-bd2ad89a4).

### ISSUE THREAD

**Issue by estivensm** [facebook/react#25818]
![Captura de pantalla de 2022-12-06 03-18-26](https://user-images.githubusercontent.com/37088485/205857556-41cc8c65-2e0e-4492-aaeb-0bcbaef60463.png)

**Comment by Konigj** [comment]
Same, it is not working since a few days. Works fine in other browsers. 
I tried reinstalling the extension several times and it didn't help.
![image](https://user-images.githubusercontent.com/84586440/206455186-a2356d60-3210-42e7-94d2-a16e044d45fc.png)

**Comment by Konigj** [comment]
To fix this problem, you can update Chrome browser.
I could not update it from the Settings > About Chrome page, so I just downloaded Chrome again, then installed it and it was fixed.

**Comment by johnhunter** [comment]
Seeing this with Chrome 110.0.5481.100, DevTools version: 4.27.2-1a88fbb67

**Comment by johnhunter** [comment]
Various combinations of close/open dev tools, Toggle extension on/off sometimes help. I can also reproduce with Edge 110.0.1587.50 (both MacOS 12.6.3)

**Comment by hoxyq** [comment]
We have recently released version 4.27.6 of the extension with some fixes for this problem. Closing this issue, but please reopen if you consistently facing similar problems with 4.27.6.

**Comment by johnhunter** [comment]
With Chrome 113 and extension 4.27.6 I still have the hanging "Loading element tree..." issue.

**Comment by johnhunter** [comment]
> Remove the extension and install it again.

This did not resolve the problem. Still happening with fresh install of extension 4.27.8 and Chrome 114.0.5735.133

**Comment by megha8191** [comment]
same issue , why this is closed without any solution
