### ISSUE TITLE
Bug: Regression in event handling with ReactDOM.createRoot

### ISSUE THREAD

**Issue by Vinorcola** [facebook/react#26002]
Hi there,

I've had a regression in one of my app by migrating from React 17 to React 18, and more specifically, by switching from `ReactDOM.render` to `ReactDOM.createRoot`.

Now, I know that this switch has some breaking changes. So I'm not sure if this is a real bug (meaning maybe it's an acceptable bug due to an accepted breaking change). But in that case, maybe the documentation could be enhance with that example.

Basically, I have a Popup component that is using some event listenenr on window in order to react to global clicks (and close). By switching from `render` to `createRoot`, it looks like the rendering of the popup is done before the end of the processing of the event opening that same popup (hence, creating an issue of not showing the popup because it closes right after opening).

React version: 18.2.0

## Steps To Reproduce

Reproduce repository link (with explaination in README): https://github.com/Vinorcola/React-18-event-issue

## The current behavior

The popup does not shows because it closes right after opening.

## The expected behavior

The popup opens on the button click.

**Comment by sundaram2021** [comment]
It sounds like the issue you're experiencing is related to the timing of when the event listener is added and when the Popup component is rendered. When you switch from ReactDOM.render to ReactDOM.createRoot, the order of these operations may change and cause the behavior you're seeing.

One possible solution to this problem would be to use the useEffect hook to add the event listener after the Popup component has been rendered. This way, you can ensure that the listener is not added until after the component has been rendered, and the issue of the popup closing immediately after opening should be resolved.

Additionally, you could try to use the useLayoutEffect instead of the useEffect to ensure the DOM is updated before the event listener is added.

It is also worth noting that since React 18, there is a new way of handling the lifecycle of a component with the new concurrent mode, so it's possible that this issue is related to that.

I would recommend you check the React documentation regarding the new concurrent mode and useEffect hooks, as well as checking the Github repository you've provided, especially the Popup component and the App component.

`import { useEffect } from 'react';

function Popup() {
  useEffect(() => {
    // add event listener here
    window.addEventListener('click', handleClick);

    // cleanup function to remove the event listener
    return () => {
      window.removeEventListener('click', handleClick);
    };
  }, []); // empty dependency array to only run this effect once on mount

  function handleClick() {
    // handle global click here
    console.log('global click');
  }

  return (
    <div>
      {/* Popup content */}
    </div>
  );
}
`

**Comment by Vinorcola** [comment]
Hi, thanks for your answer

> One possible solution to this problem would be to use the useEffect hook to add the event listener after the Popup component has been rendered. This way, you can ensure that the listener is not added until after the component has been rendered, and the issue of the popup closing immediately after opening should be resolved.

I think this is exactly what I'm doing in my repository: https://github.com/Vinorcola/React-18-event-issue/blob/ecb18730c7f1a22c081c4131b65bd43493b6ffd5/src/index.tsx#L64-L84

The listeners are added in a `useEffect` hook.

**Comment by sundaram2021** [comment]
Hey, If you issue is solved you can close it .

Thanks

**Comment by Vinorcola** [comment]
I think there is a misunderstanding. The initial issue is still here...

I did use `useEffect` on my repro repository and the issue is there. What I meant to say was that what you suggested was already implemented that way on my repro repository.

**Comment by sundaram2021** [comment]
Hey I have gone through your code and seems every thing fine but there is a behaviour issue with click handling

The problem is that the click event is being propagated to the global click handler even when it is stopped from propagation in the button click handler. This is because the `event.stopPropagation()` in the button click handler only affects the event handling in the React component tree and not the event handling in the global scope.

This causes the 'popup' to close immediately after it opens, because the same click event is being detected by the global click handler, which in turn calls `props.onClose()`.

To resolve this issue, the code should keep track of which event caused the popup to open, and check if it's the same event that's being handled by the global click handler before calling `props.onClose()`.


`let currentEvent: Event | null = null;

function App() {
    const [displayPopup, setDisplayPopup] = useState<boolean>(false);

    return (
        <div style={{ margin: 48 }}>
            <button
                type="button"
                onClick={(event) => {
                    console.log("Button click handler (React)");
                    currentEvent = event.nativeEvent;
                    event.preventDefault();
                    setDisplayPopup(true);
                    console.log("Opening popup");
                }}
            >
                Display the popup, please
            </button>
            {displayPopup && (
                <Popup
                    onClose={() => {
                        setDisplayPopup(false);
                        console.log("Closing popup");
                    }}
                >
                    <p>Popup content here</p>
                </Popup>
            )}
        </div>
    );
}

function Popup(props: PopupProps) {
    console.log("Rendering Popup");

    useEffect(() => {
        function handleCloseByClick(event: Event) {
            if (event === currentEvent) {
                return;
             }
            console.log(
                `Popup click handler: %c${event === currentEvent ? "Same event" : "Different event"}`,
                event === currentEvent ? "color: #00aa00" : "color: #dd0000"
            );
           
            event.preventDefault();
            props.onClose();
        }

        window.addEventListener("click", handleCloseByClick);
        window.addEventListener("contextmenu", handleCloseByClick);

        return () => {
            window.removeEventListener("click", handleCloseByClick);
            window.removeEventListener("contextmenu", handleCloseByClick);
        };
    }, []);

    return (
        <div
            style={{
                position: "absolute",
                top: 68,
                left: 100,
                width: 300,
                minHeight: "2em",
                backgroundColor: "#e6e6e6",
                border: "1px solid #9b9b9b",
                zIndex: 1,
            }}
        >
            {props.children}
        </div>
    );
}`

**Comment by Vinorcola** [comment]
Here is a live codepen for ease: https://codepen.io/Vinorcola/pen/BaPMyJe

**Comment by gaearon** [comment]
This sounds like the same as https://github.com/facebook/react/issues/24657#issuecomment-1150119055. See also comments below.
