### ISSUE TITLE
[DevTools Bug]: Source map error: URL: react_devtools_backend_compact.js.map

### ISSUE THREAD

**Issue by Et7f3** [facebook/react#27938]
### Website or app

https://github.com/avenida714/alec-synth/blob/dccf984d89ae44558c70ff93dfa03b1227d5df5b/src/App.jsx#L63-L64C17

### Repro steps

⚠️ This is not my code (not public) ⚠️. While I searched for this error I stumble upon this repo. I had this issue when adding the plugin for first time.

1. Open the website
2. Open console
3. See the error

### How often does this bug happen?

Every time

**Comment by Nathan-Roberts123** [comment]
I opened the https://github.com/avenida714/alec-synth/blob/dccf984d89ae44558c70ff93dfa03b1227d5df5b/src/App.jsx#L63-L64C17 project and ran it. The only error i saw was "Oscillator node error: cannot call start more than once" when ever i clicked on start button more than once, and i fixed it like like this:
![Screenshot (148)](https://github.com/facebook/react/assets/138929167/ee722bf1-0611-45db-81e8-6aa42492c092)

**Comment by Et7f3** [comment]
Thanks for testing but I still have the error:

go on this page: https://github.com/avenida714/alec-synth/tree/dccf984d89ae44558c70ff93dfa03b1227d5df5b
![image](https://github.com/facebook/react/assets/29592775/3decf471-3de7-4e16-b1b8-5ed332f8170d)
wait one minute that codespace setup
![image](https://github.com/facebook/react/assets/29592775/07f2cf60-1485-49ba-b4ac-5f7859919c54)
![image](https://github.com/facebook/react/assets/29592775/c3b7fccf-7a5a-413c-befe-356b907ba8ca)
open console
go on react components tab touch some components (I don't know if it is because I touched or because I waited ~ 1 minute)
return to the console
![image](https://github.com/facebook/react/assets/29592775/3ddb79f3-c710-465e-9e9c-8bcd3adf11bd)

**Comment by ramast** [comment]
you just need to install react-devtools

**Comment by MasterRedStorm** [comment]
same here, iam not sure how to fix that

**Comment by jasperdunn** [comment]
Also happening for me on a Remix app

It [effects Next.js](https://stackoverflow.com/questions/78486305/nextjs-passing-internal-files-as-url-params) as well. I assume it effects vanilla React too.

**Comment by jasperdunn** [comment]
Okay, so I just uninstalled the react devtools extension and reinstalled it, the errors have stopped 🤷🏼

**Comment by SanariSan** [comment]
> Okay, so I just uninstalled the react devtools extension and reinstalled it, the errors have stopped 🤷🏼

Worked for me!
