### ISSUE TITLE
Bug: creation reactjs new project latest so v19 

### ISSUE THREAD

**Issue by Productivix** [facebook/react#31701]
React version:19.0.0

## Steps To Reproduce

1.npx create-react-app module
2. wait 

Link to code example:

## The current behavior
Creating a new React app in /..../module

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

added 1315 packages in 10m

261 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: module_loginweb_reactjs@0.1.0
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"^19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.0.0" from @testing-library/react@13.4.0
npm error node_modules/@testing-library/react
npm error   @testing-library/react@"^13.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /.../.npm/_logs/2024-12-08T06_26_18_730Z-eresolve-report.txt
npm error A complete log of this run can be found in: ..

## The expected behavior
no error

**Comment by Productivix** [comment]
I solved that by : 
yarn create react-app module

**Comment by avida-1906** [comment]
> I solved that by : yarn create react-app module

The issue has solved finally.  thank you very much.

**Comment by Productivix** [comment]
yes but it not quite solved by a "documented command"  , but I am not on the right package name in fact . I will propagate

**Comment by avida-1906** [comment]
> yes but it not quite solved by a "documented command" , but I am not on the right package name in fact . I will propagate

When things are settled, that's it.

**Comment by sankalpie** [comment]
Who is this issue marked as closed?
Using yard instead of npx is not an excuse for fixing this bug

**Comment by MagicFame** [comment]
Agree, we should fix this instead of accepting a problem

**Comment by Productivix** [comment]
hi, in fact I recreated it there : https://github.com/facebook/create-react-app/issues/13726

**Comment by lcrespilho** [comment]
> I solved that by : yarn create react-app module

This is not a solution. Definitely not.

The [official documentation](https://create-react-app.dev/) recommends `npx create-react-app my-app` as the way to create a project. And that is not working anymore. It seams to me that we have a major bug.

**Comment by galuhalifani** [comment]
Did not solve `npx create-react-app app_name` but manually changing the `@testing-library/react` to version `16.1.0` works for me. Seems like it's the compatible version with react 19

`rm -rf node_modules package-lock.json`

```
"dependencies": {
    "@testing-library/react": "^16.1.0",
    "cra-template": "1.2.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-scripts": "5.0.1",
  },
```

`npm install`

no errors on this

**Comment by avithe1** [comment]
I wanted to create-react-app with typescript template and RTL but ran into this same issue.

Had to install RTL manually with types using command : 

`npm install --save-dev @testing-library/react @testing-library/dom @testing-library/jest-dom @testing-library/user-event  @types/react @types/react-dom @types/jest @types/node --legacy-peer-deps`

**Comment by petervn** [comment]
I have same issue

**Comment by volodymyrd** [comment]
The same issue for me with npx (npx create-react-app my-app --template typescript), 
but it works with yarn (yarn create react-app my-app --template typescript)

**Comment by iltan987** [comment]
Having the same issue

**Comment by cresporm** [comment]
Same issue and using Yarn is not a fix, this shouldn't be closed.

**Comment by Muhammad-Taif-Khan** [comment]
After upgrading from react 18.3 to v19 i am facing the same issue.

**Comment by IftekharulAlam** [comment]
having same issue

**Comment by sankalpie** [comment]
Guys I use this trick to fix this issue:

npx create-react-app .
npm uninstall react react-dom
npm install react@18.2.0 react-dom@18.2.0
npm install --legacy-peer-deps
npm install web-vitals

**Comment by Kajanan02** [comment]
> Guys I use this trick to fix this issue:
> 
> npx create-react-app . npm uninstall react react-dom npm install react@18.2.0 react-dom@18.2.0 npm install --legacy-peer-deps npm install web-vitals

It's install React 18 but default version is 19.

**Comment by njoro-njoroge** [comment]
I have been facing the same issue for the last two weeks. React v19 is making the process of creating a React app difficult and frustrating. I wonder what new learners must be going through.

**Comment by villanuevadani** [comment]
Hey people, anyone found a solution for this? When using `typescript` template, I do not manage to solve the issues

**Comment by MelissaTrimarco** [comment]
Use:
npm config set legacy-peer-deps true

I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.

**Comment by SakuraHoshizaki** [comment]
Completely new to React and facing the same issue now, and this just work for me!

> Use: npm config set legacy-peer-deps true
> 
> I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.

**Comment by yuridicarlo** [comment]
> Completely new to React and facing the same issue now, and this just work for me!
> 
> > Use: npm config set legacy-peer-deps true
> > I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.

also for me, but I got this new problem, not related to the precedent... 

> yooppie-app@0.1.0 start
> react-scripts start

Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\definitions\typeof.js
- c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\typeof.js
- c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\index.js
- c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\index.js
- c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\validate.js
- c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\index.js
- c:\Users\yuri1\yooppie-app\node_modules\webpack-dev-server\lib\Server.js
- c:\Users\yuri1\yooppie-app\node_modules\react-scripts\scripts\start.js

**Comment by SakuraHoshizaki** [comment]
> > Completely new to React and facing the same issue now, and this just work for me!
> > > Use: npm config set legacy-peer-deps true
> > > I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.
> 
> also for me, but I got this new problem, not related to the precedent...
> 
> > yooppie-app@0.1.0 start
> > react-scripts start
> 
> Cannot find module 'ajv/dist/compile/codegen' Require stack:
> 
> * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\definitions\typeof.js
> * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\typeof.js
> * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\index.js
> * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\index.js
> * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\validate.js
> * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\index.js
> * c:\Users\yuri1\yooppie-app\node_modules\webpack-dev-server\lib\Server.js
> * c:\Users\yuri1\yooppie-app\node_modules\react-scripts\scripts\start.js

Also for me, and I ran
`npm list ajv`
To check for the version then
`npm install --save-dev ajv@^8 ` (replace 8 with the version it shows)
and fixed it.

**Comment by yuridicarlo** [comment]
> > > Completely new to React and facing the same issue now, and this just work for me!
> > > > Use: npm config set legacy-peer-deps true
> > > > I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.
> > 
> > 
> > also for me, but I got this new problem, not related to the precedent...
> > > yooppie-app@0.1.0 start
> > > react-scripts start
> > 
> > 
> > Cannot find module 'ajv/dist/compile/codegen' Require stack:
> > 
> > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\definitions\typeof.js
> > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\typeof.js
> > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\index.js
> > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\index.js
> > * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\validate.js
> > * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\index.js
> > * c:\Users\yuri1\yooppie-app\node_modules\webpack-dev-server\lib\Server.js
> > * c:\Users\yuri1\yooppie-app\node_modules\react-scripts\scripts\start.js
> 
> Also for me, and I ran `npm list ajv` To check for the version then `npm install --save-dev ajv@^8 ` (replace 8 with the version it shows) and fixed it.

my story is that I ran

`npm install ajv --save-dev`

then a bulk update for everythying

`npx npm-check-updates -u`
PLUS
`npm install`

and with another
`npm start`

...magically, everything was resolved and wrked so fine! now, ready for the next battle :-D

**Comment by killermountain** [comment]
> npm start

this solved it for me

**Comment by killermountain** [comment]
> my story is that I ran
> 
> `npm install ajv --save-dev`
> 
> then a bulk update for everythying
> 
> `npx npm-check-updates -u` PLUS `npm install`
> 
> and with another `npm start`
> 
> ...magically, everything was resolved and wrked so fine! now, ready for the next battle :-D



THis worked for me

**Comment by Akshit0703** [comment]
> > > > Completely new to React and facing the same issue now, and this just work for me!
> > > > > Use: npm config set legacy-peer-deps true
> > > > > I got this from https://www.youtube.com/watch?v=glM8CBthVVg and is working for me now.
> > > 
> > > 
> > > also for me, but I got this new problem, not related to the precedent...
> > > > yooppie-app@0.1.0 start
> > > > react-scripts start
> > > 
> > > 
> > > Cannot find module 'ajv/dist/compile/codegen' Require stack:
> > > 
> > > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\definitions\typeof.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\typeof.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\keywords\index.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\ajv-keywords\dist\index.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\validate.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\schema-utils\dist\index.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\webpack-dev-server\lib\Server.js
> > > * c:\Users\yuri1\yooppie-app\node_modules\react-scripts\scripts\start.js
> > 
> > 
> > Also for me, and I ran `npm list ajv` To check for the version then `npm install --save-dev ajv@^8 ` (replace 8 with the version it shows) and fixed it.
> 
> my story is that I ran
> 
> `npm install ajv --save-dev`
> 
> then a bulk update for everythying
> 
> `npx npm-check-updates -u` PLUS `npm install`
> 
> and with another `npm start`
> 
> ...magically, everything was resolved and wrked so fine! now, ready for the next battle :-D

yes it works

**Comment by IbrahimZawra** [comment]
> > I solved that by : yarn create react-app module
> 
> The issue has solved finally. thank you very much. ![1](https://github.com/user-attachments/assets/186c886a-ca84-44d0-a73b-8a2af7d5f917) ![2](https://github.com/user-attachments/assets/80e6aab0-8e92-43c5-aada-002ab5c1d083)

The only one worked for me

**Comment by IbrahimZawra** [comment]
this bug appeared again when tried to install axios. pretty annoying.
