### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by ecobanoglu** [facebook/react#34128]
### Website or app

localhost

### Repro steps

messages

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

6.1.5-5d87cd2244

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1236392
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1203447)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1205054
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1620565)
```

### Error component stack (automated)

```text

```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by hpAnalytics** [comment]
?????

**Comment by eps1lon** [comment]
Is this in an app that is using Server-side rendering and hydration? This particular bug may have been fixed in https://github.com/facebook/react/pull/34209

**Comment by apuatcfbd** [comment]
> Uncaught Error: Cannot add node "13" because a node with that id is already in the Store.

What is the Issue?

**Comment by chanzer0** [comment]
I am also running into this issue when trying to run the Profiler tab.

### Website or app
localhost

### Repro steps
Open the "Profiler" tab and click the "Reload and start profiling" icon.

### How often does this bug happen?
Every time

### DevTools package
react-developer-tools Chrome extension 

### DevTools version
6.1.5 (7/4/2025) - 5d87cd2244

### Chrome version
Version 140.0.7339.186 (Official Build) (64-bit)

### React version
19.1.1

### Error message
`Uncaught Error: Cannot add node "13" because a node with that id is already in the Store.`

Error call stack (automated)
```
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1236392
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1203447)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1205054
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1620565)
```

**Comment by hoxyq** [comment]
Anyone who is still seeing this issue, could you please upgrade to React DevTools v7 and check it it is still reproducible?

**Comment by Juanjo4U** [comment]
> Anyone who is still seeing this issue, could you please upgrade to React DevTools v7 and check it it is still reproducible?

I'm still facing that error on latest version

**Comment by hoxyq** [comment]
> I'm still facing that error on latest version

Is there a reproducer that you could share?

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
