### ISSUE TITLE
Bug: Massive memory allocations using React dev build under frequent updates (prod build unaffected)

### ISSUE THREAD

**Issue by dokugo** [facebook/react#34770]
React dev build has a memory issue where under frequent updates memory footprint grows from ~100 MB to 1 GB within 5 minutes in a simple reproduction app. The JS heap remains stable at ~50 MB. Production builds are unaffected.

## Reproduce

1. Run: https://github.com/dokugo/react-dev-memory-leak
This repo replicates behavior I have in one of my apps. It's a virtualized table with 400 rows and 10 cols. Every second the last row is removed and one new row is prepended. Also a random 50% of total cells are updated and re-rendered (increased the amount for faster reproduction).

2. Do nothing and wait a few minutes, see "memory footprint" in Chrome task manager, or "memory" in Firefox about:processes grow from ~100MB to 1GB in a few minutes, while actual JS memory heap stays lean and stable.

3. While app is running: Chrome DevTools > Memory > Allocation instrumentation on timeline (Allocation stack traces checked). Allocation timeline points to React internals, probaby their allocations aren't promptly GC'd. Perhaps some dev mode instrumentation? Or maybe has something to do with detached nodes?

4. See top offenders (all from react-dom-client.development.js):
- addValueToProperties > addObjectDiffToProperties: 20 million objects allocated, +610MB
- logComponentRender > commitPassiveMountOnFiber, recursivelyTraversePassiveMountEffects: 3.9M obj, 186MB
- repeat > addValueToProperties > addObjectDiffToProperties: 8.9M obj, 156MB

All of them showing tiny Live Size, but the actual memory footprint of the tab actively grows with them allocating more, until we hit OOM.

Screenshot of what happens in 5 min of running dev server:

<img width="1173" height="572" alt="Image" src="https://github.com/user-attachments/assets/a403c96c-8c15-4446-b7e2-fbd8ccc50699" />

Profile of memory allocations over 5 minutes screenshotted above:
https://drive.proton.me/urls/300AVT1D3R#obxPg3RRxZQE

Notes:
- I use React Compiler with a bit of manual memoization, using fully manual memoization still reproduces the bug
- Reproduces using `PlainTable.tsx` (no TanStack Table and Virtualizer)
- Reproduces with disabled React Scan and React DevTools
- Reproduces with and without StrictMode
- Reproduces in incognito with extensions disabled and DevTools closed
- Production build works without issues
- React 19.2.0 with Vite
- In my app I have 2 tables with sometimes 1000+ rows in each one (with 15-20 cols), consuming 100-1000 WebSocket updates per second, batching them and applying mutation to TanStack Query cache once per second. Memory allocation grows from 300MB to 3GB unacceptably fast, making development difficult. Yet in production no issues, small and stable memory footprint, no lags, while my cells have a lot inside them, including frequent animations, images...

**Comment by huberty89** [comment]
@dokugo is the problem still occurs when you add
```
    <script>
        console.timeStamp = undefined;
    </script>
```
before you load `main.tsx` in yours `index.html` ?

**Comment by hoxyq** [comment]
Thanks for the report, this seems to related to https://github.com/facebook/react/issues/34693.

Possibly fixed with https://github.com/facebook/react/pull/34742, which will end up in 19.2.1 at some point.

**Comment by dokugo** [comment]
@huberty89
Works great, thanks! The only downside is that it breaks the new custom performance tracks added in React 19.2, but I can live with it for now. Hoping we get a cleaner fix soon.


@hoxyq
Tried this with `react@canary`, but unfortunately I can still reproduce the issue.

**Comment by hoxyq** [comment]
> Tried this with `react@canary`, but unfortunately I can still reproduce the issue.

This change is not in canary. Can you try using `react@experimental`?

**Comment by dokugo** [comment]
> This change is not in canary. Can you try using `react@experimental`?

Tested two scenarios in my private app:

- Default: 2 tables with 100 rows each
- More pages loaded via infinite scroll: 2 tables with 500 rows each

Both the stable and experimental builds showed similar memory growth: ~1.5 GB after 5 minutes with 1 page open, and ~2.5 GB with 5 pages.

Using `console.timeStamp = undefined` keeps the memory footprint at ~500 MB in 2x500 rows scenario.

**Comment by hoxyq** [comment]
> Using `console.timeStamp = undefined` keeps the memory footprint at ~500 MB in 2x500 rows scenario.

This is weird, this shouldn't work. Based on my understanding of the memory profile that you've shared, expensive allocations happen when we copy changed props objects, which could be wide / deep, this is what we've fixed in https://github.com/facebook/react/pull/34742. We use `performance.measure` in DEV there, not `console.timeStamp`, which doesn't buffer anything and shouldn't do any expensive allocations.

Just to confirm, you've tested it with both `react` and `react-dom` upgraded to experimental?

**Comment by huberty89** [comment]
Maybe I will explain from where `console.timeStamp = undefined` comes from. This is quick hack to disable performance tracks.

https://github.com/facebook/react/blob/8454a32f3cacdcb11465cfd14d68fb3eb613815f/packages/react-client/src/ReactFlightPerformanceTrack.js#L30

**Comment by hoxyq** [comment]
> Maybe I will explain from where `console.timeStamp = undefined` comes from. This is quick hack to disable performance tracks.
> 
> [react/packages/react-client/src/ReactFlightPerformanceTrack.js](https://github.com/facebook/react/blob/8454a32f3cacdcb11465cfd14d68fb3eb613815f/packages/react-client/src/ReactFlightPerformanceTrack.js#L30)
> 
> Line 30 in [8454a32](/facebook/react/commit/8454a32f3cacdcb11465cfd14d68fb3eb613815f)
> 
>  typeof console.timeStamp === 'function' &&

Oh, I see, you are right. I completely missed the fact that we gate it also based on `console.timeStamp` presence.

I suspect the root cause is the fact that we don't clear measures, so if there is a large subtree being re-rendered with expensive objects being passed down as props, they end up being cloned and buffered.

Could someone please remove `console.timeStamp = undefined` patch, and then call `performance.clearMeasures()` once you see that the memory footprint reaches some high levels? Does it lead to successful memory deallocation?

Using this as a fix in https://github.com/facebook/react/pull/34803.

**Comment by dokugo** [comment]
> Could someone please remove `console.timeStamp = undefined` patch, and then call `performance.clearMeasures()` once you see that the memory footprint reaches some high levels? Does it lead to successful memory deallocation?

Did a little test with manual `performance.clearMeasures()`, seems like it's working. But I'm not sure if it leads to memory freeing up to a stable baseline, need to test further with patched `ReactFiberPerformanceTrack.js`. Anyway, it might be that I will just end up with increased load due to my app's specific nature, with `logComponentRender` being called every second on every fiber render and doing deep prop diffing.

**Comment by hoxyq** [comment]
Should be fixed with https://github.com/facebook/react/pull/34803, could you please pull latest `experimental` release and try again?

Please re-open the issue, if it still reproduces.

We should be able to release a new patch version with all fixes in the next 1-2 weeks.

**Comment by AbhaysinghBhosale** [comment]
I tested version 19.2.1 of react in app, which includes a page with 10-12 trend charts built using 'recharts'. In development mode, the page becomes unresponsive, but there are no issues in the production build. Interestingly, setting console.timeStamp = undefined resolves the performance problem.

**Comment by houmark** [comment]
I'm confused about if this fix is actually fully fixed in React v19.2.3 or not. Can someone confirm?

I still have the workaround in place locally but I would of course like to clean that up if this is actually fully fixed.

**Comment by mio-moto** [comment]
I'm having the same issue on React 19.2.3.
On a page with a large amount of nodes, I can reliably crash Firefox by GC pressure alone:

<img width="2512" height="696" alt="Image" src="https://github.com/user-attachments/assets/ece051bd-f0dc-4c90-bd6a-a68fb6995776" />

Looking a second time on it, we're currently doing something like that:
```
console.timeStamp = () => {}
// @ts-expect-error
Performance.prototype.measure = () => null
```
In Firefox we're having the same problem but much worse, where the incremental GC starts hanging for prolonged times. This seems to be a problem in any `19.2.x` version. Up until `19.1.4` everything looks alright.
The performance regressions are not (so much) noticeable, but I would need to follow up on profiling for any reasonable details.

**Comment by fmal** [comment]
Run into the same issue in dev. This clearly hasn't shipped yet. In v19.2.4 the compiled output has zero `clearMeasures` calls anywhere in `react` or `react-dom` packages..

**Comment by houmark** [comment]
Makes no sense. This was [merged into main on October 13, 2025](https://github.com/facebook/react/commit/b9ec735de248f46da181afbc12aa906422be0dba), but I guess it wasn't a complete fix then?

**Comment by laug** [comment]
@houmark It seems 19.2.4 is not built from the main branch. I guess main is the unstable/canary branch.

For example the merged fix adds `performance.clearMeasures(entryName);` on [line 400 (old) / 409 (new) of ReactFlightPerformanceTrack.js](https://github.com/facebook/react/pull/34803/changes#diff-7b1688942314b3fdaaf66f03f536bdc9353bcc2fc420cfce4de7f87c4a928ca1).

But if you check the code in 19.2.4 in [ReactFlightPerformanceTrack.js line 400](https://github.com/facebook/react/blob/90ab3f89f4824ac763b6f877c6f711200d1338d2/packages/react-client/src/ReactFlightPerformanceTrack.js#L400) you can see `performance.clearMeasures(entryName);` has not been added yet.

So the fix is not yet available in official releases, but should become available in React 19.3.

**Comment by houmark** [comment]
@laug Thanks for clarifying that. I had a nagging feeling or something like that but didn't get around to taking it more in depth. So I really appreciate you giving this extra insight. 

I don't understand why they don't treat this as a more important hotfix to push in a patch release though, because this must be affecting many developers on a daily basis.

**Comment by lucasbryant1222-png** [comment]
Thanks for clarifying I also had a feeling it was the main branch

**Comment by AHDR3** [comment]
Same problem with v19.2.7

**Comment by laug** [comment]
@AHDR3 we probably need to wait for 19.3 for this fix to be included in a release

**Comment by valek-zp** [comment]
We hit what looks like exactly this in a telemetry dashboard (WebSocket-driven state updates → frequent re-renders) and root-caused it on our side: the growth is **retained User Timing entries** from the dev build's Performance Tracks.

`react-dom.development.js` (19.2.3) emits a `performance.measure()` per component render (entry names are component names prefixed with `​`). The browser retains every User Timing entry until explicitly cleared, and the entries are Blink-side objects — so the JS heap stays flat while process memory grows, and GC can never reclaim them. That matches the "allocation timeline points to React internals / JS heap stable" observation here.

Measurements (Chromium memory-infra tracing of the renderer while it ballooned 389 MB → 1.8 GB in ~45 s):

- `blink_objects/blink_gc/main/PerformanceMeasure`: 0 → **1,613,690** live objects (~35k/s), plus matching `PerformanceMeasureOptions` / `V8UnionPerformanceMeasureOptionsOrString` argument objects
- allocator deltas: `partition_alloc` **+602 MB**, `malloc` **+582 MB**, `blink_gc` **+208 MB** — V8 only +26 MB
- `performance.getEntriesByType('measure').length` reached **619,585** after 20 s on the page
- a single `performance.clearMeasures()` dropped renderer RSS **982 → 647 MB** within seconds

Production builds emit no measures and are flat, as in the OP.

Workaround we're shipping for dev builds until this is fixed:

```js
if (import.meta.env.DEV) {
  setInterval(() => { performance.clearMeasures(); performance.clearMarks() }, 5000)
}
```

Entries emitted while a DevTools Performance recording is active still reach the trace, so the React performance tracks remain usable with the sweeper in place.
