### ISSUE TITLE
mouseenter fires on disabled inputs whereas mouseleave does not

### ISSUE THREAD

**Issue by jquense** [facebook/react#4251]
There is an asymmetry to EnterLeave event plugin. Since `mouseenter` is created from the relativeTarget of the `mouseout` event it fires even though the target is disabled. Since the `mouseleave` is the inverse, i.e requires that the disabled element fire a mouseout, it doesn't fire a `mouseleave` for the disabled element.

I am pretty sure the correct behavior here is that neither event should fire if its target is disabled, since this mirrors `mouseout`. No idea if none-chrome browsers have the same behavior for which mouse events fire on disabled elements.

Additional caveat I just realized, React is probably also not firing `mousenter` events in the case where the mouse leaves a disabled element into a non disabled element

**Comment by jquense** [comment]
So here is an initial attempt at a fix but I can't figure out how to properly use `EventPropagators` here. Is there a way I am missing to listen for child events (i.e mouseout/over) but also return an event that doesn't bubble itself?

```js
var EventConstants = require("./EventConstants");
var EventPropagators = require("./EventPropagators");
var SyntheticMouseEvent = require("./SyntheticMouseEvent");
var containsNode = require("./containsNode");

var ReactMount = require("./ReactMount");
var keyOf = require("./keyOf");

var topLevelTypes = EventConstants.topLevelTypes;
var getFirstReactDOM = ReactMount.getFirstReactDOM;

var eventTypes = {
  mouseEnter: {

    registrationName: keyOf({ onMouseEnter: null }),
    dependencies: [topLevelTypes.topMouseOut, topLevelTypes.topMouseOver]
  },
  mouseLeave: {
    registrationName: keyOf({ onMouseLeave: null }),
    dependencies: [topLevelTypes.topMouseOut, topLevelTypes.topMouseOver]
  }
};

var extractedEvents = [null, null];

var EnterLeaveEventPlugin = {

  eventTypes: eventTypes,

  /**
   * For almost every interaction we care about, there will be both a top-level
   * `mouseover` and `mouseout` event that occurs. Only use `mouseout` so that
   * we do not extract duplicate events. However, moving the mouse into the
   * browser from outside will not fire a `mouseout` event. In this case, we use
   * the `mouseover` top-level event.
   *
   * @param {string} topLevelType Record from `EventConstants`.
   * @param {DOMEventTarget} topLevelTarget The listening component root node.
   * @param {string} topLevelTargetID ID of `topLevelTarget`.
   * @param {object} nativeEvent Native browser event.
   * @return {*} An accumulation of synthetic events.
   * @see {EventPluginHub.extractEvents}
   */
  extractEvents: function (topLevelType, topLevelTarget, topLevelTargetID, nativeEvent) {

    if (topLevelType !== topLevelTypes.topMouseOut && topLevelType !== topLevelTypes.topMouseOver) {
      // Must not be a mouse in or mouse out - ignoring.
      return null;
    }

    var win;
    if (topLevelTarget.window === topLevelTarget) {
      // `topLevelTarget` is probably a window object.
      win = topLevelTarget;
    } else {
      // TODO: Figure out why `ownerDocument` is sometimes undefined in IE8.
      var doc = topLevelTarget.ownerDocument;
      if (doc) {
        win = doc.defaultView || doc.parentWindow;
      } else {
        win = window;
      }
    }

    var eventType;

    var target = getFirstReactDOM(nativeEvent.target) || win;
    var related = getFirstReactDOM(nativeEvent.relatedTarget || nativeEvent.toElement);

    //console.log('hii!!')
    if (!related || related !== target && !containsNode(target, related)) {

      related = related || win;

      if (topLevelType === topLevelTypes.topMouseOut) {
        eventType = 'mouseLeave';
      } else {
        eventType = 'mouseEnter';
      }

      var event = SyntheticMouseEvent.getPooled(eventTypes[eventType], topLevelTargetID, nativeEvent);

      event.type = eventType.toLowerCase();
      //event.target = target;
      event.relatedTarget = related;

      // this isn't right!~!!
      EventPropagators.accumulateDirectDispatches(event);

      return event;
    }

    return null;
  }

};

module.exports = EnterLeaveEventPlugin;
```

**Comment by jimfb** [comment]
@syranide @sebmarkbage

**Comment by rogchap** [comment]
> I am pretty sure the correct behavior here is that neither event should fire if its target is disabled.

An example of when you *would* want `mouseleave` to fire on a disabled element is if you disabled the button `onclick`.

Think of a payment button: `mouseenter` is called changing the hover state  ```{hover:true}```  then `onclick` sets state to disabled ```{disabled:true}```, meanwhile, user moves mouse away from button and the button state is changed back to enabled ```{disabled:false}```. The button now is in a state that is incorrect as it currently has the state ```{hover:true}```.

**Comment by jquense** [comment]
Ping @jimfb @sebmarkbage 

Got bit by this again, I'd be happy to PR something, but the current mouseleave/enter code seems really deeply integrated (has its own event propagator?). My current stumbling block is just the below:

>Is there a way I am missing to listen for child events (i.e mouseout/over) but also return an event that doesn't bubble itself?

The problem is that I need to emit an event that does not fire when the dependent DOM events (out/leave) fire. tests seem using other examples seem either to emit for every child event, or not respond to bubbled child events at all.

**Comment by jimfb** [comment]
adding @spicyj.

@syranide and @spicyj: either of you know of a good example where we normalize in this way?  Can either of you provide some tips here?

**Comment by spicyj** [comment]
No, I'm not sure. I would be inclined to think that both mouseenter and mouseleave should fire. It's a little weird to me that click doesn't but I can kind of justify that one in my mind.

**Comment by jquense** [comment]
@spicyj I tend to agree with you, the problem though is that both mouseout and mouseover do not fire on disabled elements. I am not sure why...all spec stuff I've seen suggests that just click events shouldn't, but browsers seem to go with "all mouse events". In that context it is might more consistent to also not allow mouse enter/leave as well. But to be honest its all a moot discussion unless there is an implementation that doesn't rely on either mouseout or mouseover, which i'm may be possible but not common it seems.

**Comment by andykog** [comment]
There is also a problem for elements, containing disabled element.
`onMouseEnter` works, `onMouseLeave` doesn't.
```jsx
<div onMouseEnter={e => console.log("ok")}
     onMouseLeave={e => alert("doesn't work")}
>
    <button disabled={true} style={{ width: "100%" }}>Test</button>
</div>
```
Native `mouseleave` event [works as expected](https://jsfiddle.net/Sl1v3r/f43oqgby/) in the same situation.

**Comment by chicoxyzzy** [comment]
A have same issue. I expect to get `onMouseLeave` event on disabled button but in doesn't work

**Comment by chicoxyzzy** [comment]
More on this: it works proper in Firefox but doesn't work in Chrome and Safari

**Comment by attilaaronnagy** [comment]
After react 15, onClick on disabled elements does not fire. That makes me a ton of trouble. Should I open an other issue?

**Comment by jquense** [comment]
@attilaaronnagy fairly certain it's not a React issue, but a browser one.

**Comment by attilaaronnagy** [comment]
I'm using the latest chrome on the latest mac and with react 0.14.4 this worked perfectly... So I don't think so. Just create an <input type="text" onClick={this.whatever} disabled />, and the onClick won't fire.

**Comment by spicyj** [comment]
@attilaaronnagy I believe this is expected and matches the HTML/DOM spec. @gaearon Did we miss this in the changelog?

**Comment by attilaaronnagy** [comment]
@spicyj and if I need an input, select etc. that is disabled, but has an onClick event what can I do now? (we made a graphical html editor, and I would like to select the components with onClick, but when the edit mode active I would like to disable the component so I can't 'use' it can just 'select' it)

**Comment by attilaaronnagy** [comment]
@spicyj even if I try this:

`    this.refs.textbox.addEventListener(
      'click',
      clickEvent,
      true
    );
<input ref="textbox" />
`

it's still not working. I don't know what kind of magic you have guys cooked up, but when it's disabled, you are blocking every possible thing no matter whatever I do. I'm thinking about puting a global click event listener on the body and backward calculating which one of the components has been clicked from the coordinates, but that is absurd... Common...

**Comment by spicyj** [comment]
@attilaaronnagy Browsers don't support click events on inputs. We don't do anything that would affect how addEventListener works.

**Comment by attilaaronnagy** [comment]
@spicyj if the element is not disabled: this code works and the "normal" onClick is also working on an input.

I just tried with the same browser in a jsbin, with the older react (0.13) and it's working with the disabled input also. So if the only difference is the react version number... but whatever I gave up.

**Comment by spicyj** [comment]
@attilaaronnagy This jsbin using React 0.13.3 doesn't work for me:

http://react.jsbin.com/qesulefepu/edit?html,js,output

Let me know if you're seeing otherwise.

**Comment by attilaaronnagy** [comment]
https://jsfiddle.net/97cjyh0h/

**Comment by attilaaronnagy** [comment]
@spicyj https://jsfiddle.net/qfLzkz5x/

works for me...

**Comment by spicyj** [comment]
https://jsfiddle.net/qfLzkz5x/ doesn't have a disabled input; if you disable it then you see the behavior I posted. That is the browser's doing, not React's.

If you want to capture the onClick event on a disabled input, you have to put a wrapper node around it (or listen to it at the top level, if you prefer). This matches the standard DOM behavior. I personally think this behavior is surprising and not desirable, but we find it valuable to match the DOM spec for this so we're planning to leave it this way.

**Comment by CoryDanielson** [comment]
Any updates on this mouseLeave issue? I'm having the same issue with almost identical code to what @andykog posted.

https://jsfiddle.net/qfLzkz5x/1/

**Comment by andykog** [comment]
There is also a css workaroud:
```css
button[disabled] { pointer-events: none; }
```
Updated @CoryDanielson's fiddle: https://jsfiddle.net/Sl1v3r/sLsut3cy/

**Comment by A11oW** [comment]
More experiments http://www.webpackbin.com/VJeejto1Kf

**Comment by everdimension** [comment]
Any updates?

There still seems to be an inconsistency with the browser behavior.

Here's the demonstration which shows the differences between adding the `mouseenter` / `mouseleave` listeners with react and with plain js:
https://jsfiddle.net/everdimension/Lkgapb3t/

In chrome:
*React triggers a `mouseenter` event on the disabled button when it shouldn't.*
*React doesn't trigger a `mouseleave` event on the parent node when it should.*

In safari:
*React triggers a `mouseenter` event on the disabled button when it shouldn't.*

In firefox:
*behavior is consistent with the expected browser behavior*

**Comment by gaearon** [comment]
If there were updates they would be on this issue 😉 
Would you like to look into why this happens?

**Comment by everdimension** [comment]
Yeah, well, finding out why this happens is not the hardest part.

Basically react doesn't listen to `mouseleave` / `mouseenter` events at all (probably because they do not bubble) and instead listens only to the `mouseout` event (and in one special case to the `mouseover`, too) on the document.
And uses the reverse logic (the element you moved "out" from is sent a synthetic mouseleave event and the element you're entering (`e.relatedTarget`) is sent a synthetic mouseenter event).

Mouseout event is typically fired when you move the cursor from any element to any element (or out of the viewport).

It also fires when you move the cursor into a `disabled` button, this butting becoming the `e.relatedTarget` of the native event. That's why react consistently sends the `mouseenter` event when you enter a disabled button, even if the browser doesn't consider it a mouseenter.

But when you leave the disabled button, no browser except firefox sends a mouseout event. So react doesn't send it and we're left with this asymmetry.

The next subtle difference is that if you wrap a disabled button with another element, chrome still doesn't fire any mouseout events, but safari does fire a mouseout event for the wrapper element.


---

#### possible solutions?

1. When we move the cursor away from disabled button, all browsers fire a mouseover event. The disabled button becomes the `e.relatedTarget` again in this case, and again using the "reverse" logic we can consistently send the mouseleave event. Therefore obtaining consistent (and probably expected) behavior in all browsers.

   React already uses the `mouseover` event for one special case — when mouse enters the viewport. One more special case for disabled form elements will be the least invasive solutions.

   But it has the following cons:

   * (–) You have detect the user agent and do this only where needed to avoid sending duplicate events.
   * (–) You have to keep a list of node elements which have this problem when they are disabled. In chrome, for example, disabled textarea doesn't suffer from this problem and according to mdn, some input types don't, either.
   * (–) In chrome (and probably IE), we will still miss the `mouseleave` event on a parent element if it has the same size as the button, because chrome doesn't send a mouseover event for it.


2. We should attach `mouseenter` / `mouseleave` listeners to the node directly. I don't know if this is possible with current Event System, but I think I remember there were talks about this concerning the `scroll` events, because delegating scroll events to the document can sometimes actually be worse for performance.
   I personally think this solution would be the best one — it would directly reflect native browser behavior.


---

In any case, this is basically a bug and produces inconsistency with the browser behavior.
May be at least let's decide which path to take in fixing it?

**Comment by gaearon** [comment]
Thanks for the analysis! I don't have enough context on this but this will be helpful to the next person who visits. I'll try to compile a list of issues we need to fix, and this will be on it.

**Comment by JasonBerry** [comment]
This seems to be related to https://bugs.chromium.org/p/chromium/issues/detail?id=120132

**Comment by lyleunderwood** [comment]
In Chromium 68.0.3440.106 mouseleave fires for disabled elements, in Chrome 73.0.3683.20 it does not. `pointer-events: none;` workaround works for me.

**Comment by anyexinglu** [comment]
Any progress or solution?

**Comment by pitops** [comment]
So it seems `pointer-events: none` actually helps trigger the onMouseLeave event which seems counterintuitive to me but it works.

**Comment by LordSeb** [comment]
Guys, any progress please? Just came over it in real situation when I have text explaining functionality of some actions user can make. However In one case (in compare mode) the download mode of CSV is disabled. Then OnMouseEnter shows the text correctly but the text stays there even user scroll away because the OnMouseLeave doesn't work. Very inconsistent for sure a bug without a doubt. Hoping for quick fix! Thanks.

`<button
            onMouseEnter={() => setHoveredText(dataToCompare ? advices.csvDisabled : advices.csv)} // works
            onMouseLeave={() => setHoveredText(null)} // doesn't work !!!
            onClick={() => exportTableToCSV('TIL-table-data.csv')}
            disabled={dataToCompare}
          > ICON </button>`

![Snímek obrazovky 2020-02-25 v 9 09 11](https://user-images.githubusercontent.com/26337117/75228082-ba04ee00-57af-11ea-8c02-8d2b453b323e.png)
![Snímek obrazovky 2020-02-25 v 9 09 29](https://user-images.githubusercontent.com/26337117/75228085-bc674800-57af-11ea-96cc-361c2a69402f.png)

**Comment by lyleunderwood** [comment]
As this seems to be caused by an underlying chrome bug, I'm not sure if a solution is forthcoming.

**Comment by gaearon** [comment]
Should be fixed in 16.13.
https://reactjs.org/blog/2020/03/02/react-v16.13.0.html

If not please create a new issue with a reproducing example.

**Comment by lyleunderwood** [comment]
To be clear, the change in 16.3 seems to be that `mouseenter` will no longer fire for disabled inputs.

**Comment by RithikaChowta** [comment]
onMouseOut still works on disabled elements though, so it can be used as an alternative to onMouseLeave

**Comment by jquense** [comment]
This is still broken: https://github.com/facebook/react/issues/19419 opened a new issue for it
