### ISSUE TITLE
Warning for defining propTypes in production

### ISSUE THREAD

**Issue by brigand** [facebook/react#6402]
A production only warning for having propTypes defined as a non-empty object could spark a change in the community to have propTypes conditional on NODE_ENV. This could be automated with a babel plugin, or similar for other build systems.

This would result in all react apps being significantly smaller in production.

> Warning: you have defined propTypes on the {ComponentName} component in a production build. If this is your own code, consider using a plugin such as babel-plugin-{plugin-name}. If it's a third party library, open an issue.

Or alternative save-all-bytes text.

> Warning: propTypes defined on {ComponentName} http://fb.me/react-prod-proptypes

**Comment by mijamo** [comment]
Naive question here: why should it trigger a warning ? As far as I know propTypes have no influence in production so there is no negative consequence of having them, except that it takes some lines of code.

So I really don't see why a warning should be triggeredfor something that cannot possibly have any impact at all.

**Comment by brigand** [comment]
Just to warn people that there's unneeded code in their production builds. I only suggest it because impacts almost every react app in existence. Maybe it's a stupid idea, but I wanted to bring it up in case other people agree.

It follows the general rule of warnings in that they indicate something that should be fixed. I imagine it'd be hard to find someone arguing that propTypes should take up space in production builds.

**Comment by jimfb** [comment]
This would put a pretty heavy burden on component authors.  They would need to distribute two versions of their components (prod vs. dev).  It's also not super actionable if you're using a third-party component that defines proptypes.  An automated transform wouldn't necessarily be able to eliminate all proptypes (eg. on stateless function components) without making a bold assumption that assigning proptypes to a function means that function must be a React component.

Anyway, I'm not actually oppose to the idea, but I think we'd need to have the transforms in existence before we could enable such a warning.  My guess is that it's not worth the headache.  But if someone writes such a transform, and people start using it and find that the byte savings justify the complexity, we could consider enabling such a warning.  Let's re-evaluate if/when such a transform becomes mainstream.

**Comment by brigand** [comment]
Thanks for the good feedback; those are some issues I didn't think of.

**Comment by mijamo** [comment]
@brigand You will be pleased by https://github.com/facebook/react/pull/6401. After this pull (for v16), Uglify should delete the proptypes for production :)

**Comment by jimfb** [comment]
@mijamo Yeah, that solves some of, but not all of, the overhead that @brigand mentioned.  React components will still have a proptype object defined with a bunch of empty function references.  But yes, it's an improvement :).
