### ISSUE TITLE
Error: performUpdateIfNecessary: Unexpected batch number ...

### ISSUE THREAD

**Issue by brotzky** [facebook/react#6895]
I am getting a strange error I've never come across. Googling it doesn't help at all.
`Error: performUpdateIfNecessary: Unexcpeted batch number (current 36, pending 31)(...)`
It has caused me a lot of headaches. I've reverted to 2 days ago and the error persists, even though 2 days ago everything was running smoothly and all tests were passing.

I would appreciate any sort of direction as to how I can begin to resolve this bug. My guesses are that it's an error with Redux, Webpack, Redux-Form, or React itself. I know, not that precise, but I'm quite lost. 

---

Example redux logger information: 
![screen shot 2016-05-26 at 11 18 43 am](https://cloud.githubusercontent.com/assets/8007686/15585614/f6ef14e8-2334-11e6-9c44-a9380b028707.png)

Max OS X, El Capitan 10.11.5
React v15.0.1 (error persists on v15.1.0)

_I'm sorry if this isn't specific to React. I did look into the error message code and it appears to be coming from the Facebook/React code._

Thanks!

**Comment by gaearon** [comment]
If you scroll up, are there any earlier errors before these ones? You can see them in the `error` field in Redux logger.

**Comment by brotzky** [comment]
No, those are the first errors.

I'm using react hot loader 3-beta.1 and when I hide and show the side logger I can reproduce the same error over and over.

![screen shot 2016-05-26 at 12 07 27 pm](https://cloud.githubusercontent.com/assets/8007686/15586702/99b5850e-233a-11e6-9c12-a11c3452311c.png)

I think it's an error with one of my dependencies, but not sure which one. Postcss/autoprefixer and redux-form are back on my list of guesses.

**Comment by gaearon** [comment]
Does `npm ls react` show only one copy of React? Can you create a minimal project reproducing the problem?

**Comment by brotzky** [comment]
```
└── UNMET PEER DEPENDENCY react@15.1.0

npm ERR! peer dep missing: react@^0.14.8, required by react-addons-css-transition-group@0.14.8
npm ERR! peer dep missing: react@^0.14.8, required by react-addons-test-utils@0.14.8
npm ERR! code 1

```

**Comment by gaearon** [comment]
Ugh, `npm ls react` breaks because of peer deps. What’s confusing though is you seem to have `react-addons-css-transition-group@0.14.8` and `react-addons-test-utils@0.14.8`. Can you please update these packages to `15.1.0` as well and make sure they don’t contain `node_modules/react` inside themselves?

**Comment by brotzky** [comment]
Okay, I've upgraded both packages and checked their respective folders in `node_modules `to see if they contain their own `node_modules/react` (which they don't).
```
"react-addons-css-transition-group": "^15.1.0",
"react-addons-test-utils": "^15.1.0",
```

npm ls react now returns
`└── react@15.1.0`

**Comment by gaearon** [comment]
Cool. Still having the same issue? At this point only a reduced example would help.

**Comment by brotzky** [comment]
I reverted back even further and it finally works. The major package changes were redux-form (v5 vs v6) and some smaller stuff. 

Going to keep trying out different packages until I find out what was throwing the issue. Hopefully I post back here soon with the solution for the rare chance someone else has a similar problem.

**Comment by jimfb** [comment]
This sounds like it is probably a bug in React.  That invariant is new; it was added in 15.1.0, which was released six days ago.

@brotzky If you can provide a reproducible test case, that would be super helpful.  Even if it is part of a larger codebase that you can share (my guess is it is going to be super hard to isolate that example).

cc @spicyj

**Comment by spicyj** [comment]
Yes, if you can post something that reproduces the problem it would be very helpful.

**Comment by brotzky** [comment]
Yes, we updated to 15.1.0 yesterday, May 25th.

I will see if I can isolate the issue, but it's very hard to track down. That's the only error message I get. This doesn't break all components, only ones on a specific view. For example, it's the only view that uses `<ReactCSSTransitionGroup />`. 

Here's the entire log I get from start to finish. 
![screen-shot-2016-05-26-at-1 54 02-pm](https://cloud.githubusercontent.com/assets/8007686/15589938/ef72786c-2349-11e6-9baa-e6defad3b2fb.jpg)

**Comment by brotzky** [comment]
Ive just removed the `redux-form` component from the page and it loads fine.
`redux-form@6.0.0-alpha.13`

Will continue looking into this. It seems my original suspicion was correct.

**Comment by gaearon** [comment]
@erikras Ever seen this?

**Comment by brotzky** [comment]
@erikras, when I specifically remove the      
```javascript
<Field
    name="inputName"
    component={inputName => 
     ...
}/>
```
Everything works as expected.

**Comment by gaearon** [comment]
This is definitely a React but though. There's definitely nothing Redux Form is doing that would be wrong. So if you can repro, please share a case!

**Comment by brotzky** [comment]
I'm not sure it was React. Sure, the errors were thrown by React but it's possible that those errors were thrown correctly. Having said that, I've never seen those specific batch errors until upgrading to the newest version 15.1.0 (they're not very descriptive errors). The issue I had was with redux-form -- I had a slightly improper setup that was causing issues. 

To resolve my specific errors I had to alter my `mapStateToProps` function in my redux-form container.

Before:
```javascript
const mapStateToProps = (state) => ({
  fieldValue: state.form && state.form.quote.values.value,
});
```

After:
```javascript
const mapStateToProps = (state) => ({
  fieldValue: state.form && state.form.field && state.form.field.values && state.form.quote.values.value,
});
```

Overall, if you're using redux-form v6.x and need to get your form fields value on props I recommend using `formValueSelector() ` instead of how I approached the issue. http://redux-form.com/6.0.0-alpha.13/docs/api/FormValueSelector.md/. This will be much cleaner and less prone to issues.

**Comment by jimfb** [comment]
> I'm not sure it was React. Sure, the errors were thrown by React but it's possible that those errors were thrown correctly.

This is highly unlikely, unless code is reaching deep into the internals of React, it should not be possible for a user to trigger this error message.  The error message is for internal debugging/sanity-check purposes.

This is probably a bug, but we're going to need some sort of repro from someone experiencing the bug.  As I mentioned before, it's probably going to be really hard to isolate the bug, so even full-app repros are acceptable in this case.

**Comment by jimfb** [comment]
If anyone else is experiencing the bug, please feel free to post!  We'd like to collect as much data on this one as possible!

**Comment by brotzky** [comment]
If I have time, I will see what I can do over the weekend. 🎱

**Comment by realbugger** [comment]
I also saw this error yesterday, and I just upgraded to react 15.1.0 the day before yesterday! In my case, I use redux-form as well except it's v5.2.4. 

Eventually I found out the error was triggered by a line of code destructing an object, like `const { foo } = bar;`, but `bar` was `undefined` during certain rendering cycles. It's weird that I didn't get the usual `cannot read property ”foo" of undefined` error, though. And this only happened after upgrading to react 15.1.0.

**Comment by gaearon** [comment]
@realbugger Can you try to extract a minimal case reproducing this?

**Comment by brotzky** [comment]
@gaearon I was able to recreate it. It took me a while to set everything up as I initially tried to reduce our application to the single bug, but that didn't work well. I then went to go look for decent boilerplates but all were overly complicated. Ended up using your ToDo example and added in `redux-form`, `react-router` and upgrading it to `react@15.1.0`

https://github.com/brotzky/react-issue-6895

1. clone the repo
2. npm install
3. open http://localhost:3000/

To recreate the bug:

1. Focus the example input
2. Type into the example input

You should get errors in your console. I've also commented out a line that fixes the bug. Everything should be contained in `Header.js`. 

Let me know if you have questions.

**Comment by gaearon** [comment]
>Downgrading to react@15.0.1 removes the batch errors and only the undefined error stays.

Thank you so much! So do you mean that you see an *earlier* error from your code before that invariant?

**Comment by erikras** [comment]
> @erikras Ever seen this?

No.

**Comment by brotzky** [comment]
@gaearon. Yes, looks like the redux `connect()` method fails due to an undefined value in `mapStateToProps()`. But you can also get the batch error after typing into the input field.

<img width="1674" alt="screen shot 2016-05-29 at 1 12 02 pm" src="https://cloud.githubusercontent.com/assets/8007686/15635836/1bfaa86c-259f-11e6-8f49-feb455336fd6.png">

**Comment by gaearon** [comment]
@brotzky 

This is what I was asking in the beginning of the thread:

>If you scroll up, are there any earlier errors before these ones?

The reason I asked is that if your code threw (e.g. in `mapStateToProps`), then it’s pretty much expected that React gets into an inconsistent internal state. So this is not a bug in React, because the error didn’t appear out of the blue: it appeared after *another* error was thrown in the user code.

**Comment by brotzky** [comment]
Damn, sorry for the misunderstanding. It appears in my original example there was no previous error like the one I linked. I agree it's probably not a React bug.

**Comment by gaearon** [comment]
Hmm. So we’re still after something like your original example I’m afraid 😞 .
Unless... could it be that the error there was swallowed by a Promise? 😄

**Comment by brotzky** [comment]
You got it 👌

**Comment by gaearon** [comment]
We might want to look if it’s possible to have the invariant see correct numbers even if user code throws.

**Comment by brotzky** [comment]
Exactly, see my edited comment above.

**Comment by spicyj** [comment]
15.1.0 added this error; previously React didn't notice which would cause other problems (see #2410). Proper error boundaries for updates could also help (@jimfb).

**Comment by brotzky** [comment]
If anyone's reading this through search or the like, the error seems to come up when you're improperly destructing variables with an undefined value in it. It could also be an issue with your redux `connect` function. More specifically, my error was mapping (`mapStateToProps`) an undefined value to props with redux-form.

To solve my issue, I had to remove entire components to see if my app would render correctly with or without them. Turned out to be a pretty good strategy after a few hours of headaches.

Overall, React is behaving correctly and you've overlooked a different possible issue. Good luck 💆

**Comment by paulinthought** [comment]
I'm experiencing the same bug but only in my development build and it has only begun since I started using redux-devtools. I can reproduce it by not committing the state changes while I click around my app until I hit a debugger breakpoint in chrome devtools (like an uncaught exception in my own code). Then if I try to commit state changes again I have this error.

**Comment by maxkostow** [comment]
I recently saw this error in production. I've tried to make a minimal reproduction case, but don't have a good enough understand of react internals to recreate the situation. I think what happens is an error is thrown during reconciliation (couldn't figure out the right order here), before the `dirtyComponents` array is emptied, an element can get left over with an old `updateBatchNumber` and on the next update, it's considered "stale".

**Comment by gaearon** [comment]
We don’t really support recovering from user errors thrown in the reconciliation so in this case it seems expected.

**Comment by mnpenner** [comment]
I'm getting this error when I call `this.setState` a whole bunch in rapid succession using the function variant. I *am* getting an error before the "Unexpected batch number" errors, but it doesn't make sense to me.

Here's a condensed version of the code, with the irrelevant bits pruned out:

```js
const update = require('react-addons-update');

export default class PhsaDocToolbar extends React.Component {

    state = {
        dialogOpen: false,
        files: {},
    };

    uploadFile = file => {
        console.log('Uploading file',file);

        let fileData = new PhsaFileUploadData({
            filename: file.name,
        });

        this.updateState({
            dialogOpen: {$set: true},
            files: {
                [fileData.key]: {$set: fileData},
            }
        });


        let xhr = new XMLHttpRequest();

        xhr.open('POST', '...');

        xhr.addEventListener('load', ev => {
            this.updateState({
                files: {
                    [fileData.key]: {
                        percent: {$set: 1},
                    }
                }
            });
        });

        xhr.upload.addEventListener('progress', ev => {
            if(ev.lengthComputable) {
                let percent = ev.loaded / ev.total;
                console.log(fileData.percent,percent);
                this.updateState({
                    files: {
                        [fileData.key]: {
                            percent: {$set: percent},
                        }
                    }
                });
            }
        });

        xhr.send(file);

    };

    updateState = updates => {
        this.setState(state => update(state, updates));
    };

    ...
}
```

The error I see first is:

> Uncaught TypeError: Cannot read property 'percent' of undefined

Followed by dozens or hundreds of:

> Warning: performUpdateIfNecessary: Unexpected batch number (current 12, pending 10)

The "Cannot read property 'percent' of undefined" error doesn't make sense because (a) my component seems to work fine if I only upload one file at a time. It's only when I try uploading multiple files at a time that the error *might* occur. The error occurs inside of `react-addons-update` which is called from inside `xhr.upload.addEventListener('progress'`, which (b) can't fire until after I've initialised the 'percent' to 0.

It's as though the deferred setStates are firing out of order. I thought the whole idea behind the function variant of `setState` was that it always passed in the previous state so that you could batch up lots of calls to `setState` and have them guaranteed to run in order, with a "fresh" state every time.

However, if the call to `setState` inside the 'progress' event were to fire before the one several lines up, I could see how this error would occur.

Maybe I'm overlooking something. Going to keep debugging.

**Comment by jkomyno** [comment]
I'm having the same bug. What is strange, though, is that it happens only if I move the subcomponents of my custom Dashboard components from a place to another, in a way that just doesn't make sense to me at all.
The error that I get is:

main.js:2982 Warning: performUpdateIfNecessary: Unexpected batch number (current 7, pending 1)printWarning @ main.js:2982warning @ main.js:3006performUpdateIfNecessary @ main.js:15682runBatchedUpdates @ main.js:15289perform @ main.js:16572perform @ main.js:16572perform @ main.js:15228flushBatchedUpdates @ main.js:15311closeAll @ main.js:16638perform @ main.js:16585batchedUpdates @ main.js:25400enqueueUpdate @ main.js:15339enqueueUpdate @ main.js:24382enqueueSetState @ main.js:24567ReactComponent.setState @ main.js:3435handleChange @ main.js:30391handleChange @ main.js:10196dispatch @ main.js:30773dispatch @ VM82326:1(anonymous function) @ main.js:112547dispatch @ main.js:31239(anonymous function) @ main.js:47872

I'm using React@15.3.1, redux@3.5.2, axios@^0.13.1 (for AJAX requests) and redux-thunk@^2.1.0, and in two months working on this project for my agency I've never seen anything like this.

**Comment by duncanfinney** [comment]
@jkomyno @gaearon: I experienced this issue as well. 

What was happening was the `initialValue` I was pulling from state was `undefined`

```
VenueForm = reduxForm({
  form: 'venue',
  enableReinitialize: true
})(VenueForm);

VenueForm = connect(
  (state, props) => {
    const venue = _.find(state.resources.venues.items, i => i.id === id);
    return {
      initialValues: venue
    }
  }
  }))(Venue);
```

Changed one line to:

```
const venue = _.find(state.resources.venues.items, i => i.id === id) || {};
```

and everything worked again.

**Comment by jkomyno** [comment]
My issue was pretty similar, same undefined stuff, even though it was a
prop correctly initialized in the reducer. I suppose the only workaround
here would be patching the debugger a little bit to make the developers
realize where the error comes from. Or, even better, find a way to tunnel
the reducer initialization to the component at the first render

Il 30/set/2016 18:08, "Duncan Finney" <notifications@github.com> ha scritto:

**Comment by zjjott** [comment]
I have this error when I use ref method in batch Component update like this:
```jsx
scrollIntoView(element){
   //this function raise some other exception when element is null
  //and then Unexpected batch number will raise
},
render(){
    return <ul >{this.state.data.map((row)=>{
           if(row.id==this.state.id){
               return <li ref={this.scrollIntoView}>{row.data}</li>
           }
           else{
                   return <li>{row.data}</li>
           }
        })
        }
        </ul>
}
```


I fixed it when scrollIntoView then no longer raise Exception,so maybe this error in the issue is cause by error during render

**Comment by giuseppeg** [comment]
fwiw I got this error when I tried to override `PureComponent.shouldComponentUpdate` like so:

```javascript
export default class extends PureComponent {
  shouldComponentUpdate(nextProps, nextState) {
    console.log(typeof super.shouldComponentUpdate) // > undefined
    /* some user code */
    return super.shouldComponentUpdate(nextProps, nextState)
  }

  render() {
    // ...
  }
}
```

Probably this is not optimal but it should be allowed and working right?
Would appreciate any help/hint.

cc @spicyj

**Comment by mgnrsb** [comment]
I got this error when trying to access `e.target.value` from an event that bubbles up from an input element into a custom element. By the time I want to consume it, the event has already been reset to null.

`const GeneralInput = ({ name, onChange }) => ( <input name={ name } onChange={ onChange } /> )`

```
export default class OtherComponent extends Component {
  constructor (props) {
    this.state={}
    this._handleChange = this._handleChange.bind(this)
  }
  _handleChange (event) { this.setState({ [event.target.name]: event.target.value }) }
  render () { 
    return (
      <form onChange={ this._handleChange }>
        <GeneralInput name='firstname' value={this.state.firstname} />
      </form>
    )
  }
}
```

I solved it by calling `e.persist()` on the input element itself:
`const GeneralInput = ({ name, onChange }) => ( <input name={ name } onChange={ (e) => e.persist(); onChange(e) } /> )`

**Comment by gaearon** [comment]
@mgnrsb and everyone else:

If you only saw this error but didn't see the original error (for example in @mgrnsb's case it would be something like "Cannot read target property of null") then you still have a problem, and some part of your code swallows exceptions.

The most common way to get this problem is when you use Promises and have a catch() block after you're attempting to update the UI. If a component throws an error (due to mistake in your code) your catch() handler gets this error and tries to render the error in the UI, assuming it is a network error. However the UI is already broken at this point because of the earlier error (which you never surface) and this is why you get a confusing second error.

Be careful catching errors especially when dealing with Promises. It is very easy to accidentally catch errors in your own code.

**Comment by viz** [comment]
I'm seeing this too. Seems to be related to redux-form and or it's interaction with react.

Current versions are: redux-form v6.2.0, react v15.4.0

Seems like this problem started occurring after upgrading to redux-form 6.x.

![developer_tools_-_http___localhost_3000_](https://cloud.githubusercontent.com/assets/12402/20412782/e9752a32-ad7c-11e6-9436-d13352d38bf5.png)

**Comment by gaearon** [comment]
I'm afraid additional comments on this thread won't be helpful without examples reproducing this issue.

**Comment by brotzky** [comment]
@viz We're using redux-form v6.2.0 and react v15.4.0 with no issues at the moment.

I would go over and try to identify the exact source of the issue. Try removing components until you narrow it down. Then I'd advise checking all the variables you're using in that component and making sure you're not passing around `undefined` anywhere.

Or as @gaearon mentioned, provide an easy to follow example reproducing the issue.

**Comment by wking** [comment]
Here's a fairly minimal project which reproduces this error in the test suite (shortly before it the test legitimately errors out):

```
$ node --version
v4.4.6
$ npm --version
2.15.5
$ git clone git://github.com/wking/performUpdateIfNecessary-bug.git bug
$ cd bug
$ npm install
npm WARN optional dep failed, continuing fsevents@1.0.14
react@15.4.1 node_modules/react
├── object-assign@4.1.0
├── loose-envify@1.3.0 (js-tokens@2.0.0)
└── fbjs@0.8.6 (ua-parser-js@0.7.12, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

react-dom@15.4.1 node_modules/react-dom
├── object-assign@4.1.0
├── loose-envify@1.3.0 (js-tokens@2.0.0)
└── fbjs@0.8.6 (ua-parser-js@0.7.12, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

react-scripts@0.7.0 node_modules/react-scripts
$ npm test
…a…
…
  console.error node_modules/react-dom/node_modules/fbjs/lib/warning.js:36
    Warning: performUpdateIfNecessary: Unexpected batch number (current 2, pending 1)
```

**Comment by gaearon** [comment]
The [reproducing code](https://github.com/wking/performUpdateIfNecessary-bug/blob/master/src/Bug.js) is a bit convoluted but doesn't seem like there's any good reason for it to fail.
Reopening and tagging as a bug.
Help investigating why the error happens is welcome.

Note that it's not an error, as it was relaxed to be a warning. Still it's weird it happens.

**Comment by wking** [comment]
On Thu, Nov 24, 2016 at 04:50:27AM -0800, Dan Abramov wrote:
> The reproducing code is a bit convoluted…

It makes a bit more sense before you boil it down that far ;).  The
full version of that code is a graph of issues for each requested
slug, so there's a recursive slug-fetcher.  The nested atomic state
pivots allow me to avoid duplicate parallel calls [1].

[1]: https://github.com/wking/depviz/blob/f6a6915afbc73daf9ad4fd64a09dfcd708a4adfa/webapp/src/DepGraph.js#L32-L60

**Comment by romansky** [comment]
Was able to "reproduce" this issue by simple:
```
componentWillUnmount(){
        throw "bbbb";
}
```
There was no other indication for the generated exception, OP's error ensured.

**Comment by zargold** [comment]
I got this issue with react-redux-form + React Autocomplete by setting the initial state for a form to be `null` rather than `''`. (Which I really wanted... but it didn't work... oh well set it back to `''` and everything "fixed".

**Comment by mcku** [comment]
I can reproduce a case, likely similar to the original.

OnsenUI 2.0.5 Lazylist does not render and gives the "performUpdateIfNecessary: Unexpected batch number" error after upgrading to **Leaflet 1.0.2** & React-Leaflet 1.1.0.

Going back to legacy Leaflet 0.7.7 alleviates the error, and the Lazylist component functions correctly. 

In both cases react version was 15.4.2.

**Comment by ivks** [comment]
This may be out of context, but I came to this issue, because this message popped up while I did a stupid mistake in my React Native code
Inside the view for an onPress event I did this 
`onPress={methodName} `
instead of 
`onPress={methodName()} `
Posting this just in case help anyone else save some time.

**Comment by osilvaa** [comment]
This message popped up when I was working with a SELECT on Redux-Form. Initially, my SELECT was initialised with an empty array as options. But, accidentally, on my action creator I made this:
`**let staticData = {}**;
  switch(Number(countryId)) {
    case 1:
      staticData = [
        { id: 1, name: 'XPTO1'},
        { id: 2, name: 'XPTO2'}      
      ];
      break;
  }

return {
      type: FETCH_KEY,
      payload: {
        data: staticData
      }
  };`

This was changing the initial type from Array to Object which was unexpected by my reducer & view.  After changing the highlighted line to
`**let staticData = []**;`
It started working fine.

**Comment by oklas** [comment]
This error

>  Error: performUpdateIfNecessary: Unexpected batch number

appears at some component after error  (see #4026)

> Uncaught TypeError: Cannot read property '_currentElement' of null

appears in another component if it have crash at `render()` method (for example caused by `(undefined).x` code)

both components is not parent of each other

**Comment by gaearon** [comment]
In this thread, everybody seems to be enumerating all the different possible errors in JavaScript apps. However they are not relevant to solving the issue, and are not helpful to others. This thread focuses on symptoms, but the underlying cause has been explained several times in this and other threads. I'm going to lock this thread to reduce the noise and help people finding this on Google focus on the solution rather than the symptom.

I have explained the solution in https://github.com/facebook/react/issues/7617#issuecomment-247710003 so please read that comment. This problem most commonly occurs with Promises, but can occur in any code where you `catch` exceptions and don't log them.

**If you see a cryptic error like this it always means there is an earlier error from your component code that causes React to break**. You need to scroll your console up and find the original error.

**If you don't see an earlier error in your own components, it means that your code is swallowing errors.** This is very common [if you use `catch()` with Promises and accidentally swallow errors inside React](https://github.com/facebook/react/issues/7617#issuecomment-247710003). Some third party libraries may also swallow your errors. I recommend to enable "Break on All Exceptions" in your debugger, and then when the error throws, check the call stack to find who's silently catching your error.

Again, **this error itself is just an irrelevant symptom**.
You need to figure out why your code crashes in a component, and which `catch` swallows the crash.

The fact that React produces cryptic errors on next updates after a component crash is unfortunate, and we'll fix this in next versions of React. However, in any case, you need to fix the underlying problem (your code crashing) first.

If you're sure it's a bug in React please file a new issue with a minimal reproducing test case.

**Comment by gaearon** [comment]
A small update on this. We just released [React 16 beta](https://github.com/facebook/react/issues/10294) which shouldn’t emit cryptic errors like this one. Even if the application code swallows an error, React 16 will still print it to the console. It might be too early for you to try React 16 (since ecosystem is still preparing for it), but this error should never occur in the future after you switch to it.
