### ISSUE TITLE
JSX conditionals requires a lot of workarounds a lot of the time

### ISSUE THREAD

**Issue by syranide** [facebook/react#690]
# The one good example

Conditionals are currently solved with the ternary `?:` or `&&` + `||` and actually works surprisingly well. However, what can be returned by them is another story.

The academic textbook example works great:

```
<div>
  {condition ?
    <span></span>
  : null}
</div>
```

or

```
<div>
  {condition &&
    <span></span>
  }
</div>
```

Looks pretty good, works great.
# Any other is a disaster

But in order to return 2+ tags you need to return an array, which also requires that you separate them by commas (good bye beautiful JSX):

```
<div>
  {condition ?
    [
      <span></span>,
      <span></span>
    ]
  : null}
</div>
```

If you want a text-node instead then you have to actually rewrite your JSX-style code to pure JavaScript instead, which is perhaps even worse:

```
<div>
  {condition ?
    'My name is ' + name + '!'
  : null}
</div>
```

Let's also do the complete version, a text-node surrounded by tags, whitespace rules fly out the window and it no longer looks anything like JSX:

```
<div>
  {condition ?
    [
      <span></span>,
      'My name is ' + name + '!',
      <span></span>
    ]
  : null}
</div>
```

And while we're at it, if there are nested ifs then it looks like this, so let's go all out ugly, despite how simple it really should be:

```
<div>
  {condition ?
    [
      (condition ?
        [
          <span></span>,
          'My name is ' + name + '!',
          <span></span>
        ]
      : null),
      'Hello ' + name + '!'
    ]
  : null}
</div>
```

That is barely even understandable code. When without conditionals it would look like this:

```
<div>
  <span></span>
  My name is {name}!
  <span></span>
  Hello {name}!
</div>
```

So in my opinion, something is clearly wrong here, adding a conditionals should never require you to be working with arrays and rewriting inline text to use JavaScript string literals instead, or in general require you to massacre your code.
# The problem(s)
## Multiple tags

The easy part problem is simply that we currently cannot return more than one tag before having to resort to arrays. Intuitively this should be relatively easy to fix in JSX by simply automatically wrapping such as arrays. Simple, intuitive and good output?
## Conditionals

While it may not be a big deal, it's weird that the syntax for an if-statement `<tag>{cond ? true : false }</tag>` is different from a nested if `<tag>{cond ? (cond ? true : false) : false}</tag>` (braces replaced with parenthesis, because we're already in an expression) and it's back to braces if it's inside a tag `<tag>{cond ? <tag>{cond ? true : false}</tag> : false}</tag>`.
## Text and expressions

The last big issue is that we can transition from JS to JSX-HTML by adding a root tag `<tag></tag>`, but we cannot transition directly to JSX-text and JSX-expressions `My name is {name}!` without it being wrapped in a tag `<tag>My name is {name}!</tag>` or without being rewritten to plain JavaScript `'My name is ' + name + '!'`. Which is necessary because conditionals are currently implemented as expressions.
# Solutions
## New conditional syntax

So it seems to me like the root of the problem is that conditionals are implemented as JSX expressions, which also causes the problem with having to rewrite JSX text/expressions when adding conditionals unless they are wrapped by tags. If they did not piggyback on JSX expressions then everything but non-parented JSX text/expressions would be solved, and really, that's not an issue at all.
## Nesting of JSX expressions

Another solution is to allow JSX-expressions to be nested `<tag>{cond ? {cond ? true : false} : false}</tag>`, JSX text/expressions inside conditionals will still be a problem, but that could reasonably be solved by backtick strings `<tag>{cond ? `My name is {name}!` : null}</tag>`.
## Or...

Or do you think there are better ways one should use to structure the code? Am I missing something?

I realize that this perhaps is approaching it from the perspective of old-style templates, but from where I'm standing now, these things seem to make it quite cumbersome in more complex situations... there are a lot of situations in which one has to change surrounding code simply because one added a tag, or because one removed a tag... or moved a conditional.

PS. We had some discussion in the chat, and I agree that most of this is probably just "old-school template habits", however, returning multiple tags is biting me in the ass a lot. While everything content inside conditionals could be wrapped in divs/spans to make it play nice, it seems weird to have to add markup just to be able to write reasonable JSX.

**Comment by JulianLeviston** [comment]
frag would be absolutely awesome to have...

**Comment by AlexGilleran** [comment]
If you're used the condition/looping constructs of traditional templating languages and would prefer to use them like me, you might consider https://www.npmjs.com/package/jsx-control-statements. Basically  it turns neater `<If condition={condition></If>`-style syntax into the ternary syntax described above.

**Comment by jquense** [comment]
If anyone is annoyed by this as I was and uses babel, I wrote a plugin to implement (in part) the `<frag>` syntax mentioned above.

https://github.com/jquense/babel-plugin-jsx-fragment

**Comment by stoeffel** [comment]
If anyone is interested, I just released a module for conditional rendering. Feedback is more than welcome.
https://github.com/stoeffel/react-cond

**Comment by rymohr** [comment]
@stoeffel looks like a great solution. Thanks for sharing!

**Comment by gfdev** [comment]
If anyone is interested yet, there is another solution for conditional rendering.
https://github.com/gfdev/javascript-react-if-component

**Comment by jimfb** [comment]
@gfdev et al: If statements can not be implemented as a react component for reasons: https://github.com/AlexGilleran/jsx-control-statements/wiki/Why-Transform

Alex has done a great job maintaining a transform that implements various control statements:
https://www.npmjs.com/package/jsx-control-statements

**Comment by ajwhite** [comment]
I've seen a lot of React components that aim to introduce control flow behavior, but I personally prefer to keep those pieces functional. 

I just published a really simple function that can be used to compose conditional render blocks. https://github.com/ajwhite/render-if


### As an in-line expression

```jsx
class MyComponent extends Component {
  render() {
    return (
      {renderIf(1 + 2 === 3)(
        <span>The universe is working</span>
      )}
    );
  }
}
```

### As a named function

```jsx
class MyComponent extends Component {
  render() {
    const ifTheUniverseIsWorking = renderIf(1 + 2 === 3);
    return (
      {ifTheUniverseIsWorking(
        <span>The universe is still wroking</span>
      )}
    )
  }
}
```

### As a composed function
```jsx
const ifEven = number => renderIf(number % 2 === 0);
const ifOdd = number => renderIf(number % 2 !== 0);

class MyComponent extends Component {
  render() {
    return (
      {ifEven(this.props.count)(
        <span>{this.props.count} is even</span>
      )}
      {ifOdd(this.props.count)(
        <span>{this.props.count} is odd</span>
      )}
    );
  }
}
```

**Comment by jimfb** [comment]
@ajwhite This suffers from the same problems I just mentioned one post prior.  This can't be solved without at transform, as per https://github.com/AlexGilleran/jsx-control-statements/wiki/Why-Transform

**Comment by ajwhite** [comment]
@jimfb thank you for these links. Terrific points, my approach promotes the idea that the block will not be evaluated if the predicate fails, yet it certainly will. :warning: :warning: :warning: 


Mentioned a thought on using a callback to avoid evaluation on our other thread https://github.com/reactjs/react-future/issues/35#issuecomment-180434194. Will keep discussion moving there. Ty for feedback!

**Comment by milesj** [comment]
Wouldn't this be easily circumvented through stateless components?

```
<div>
  <listSpans condition={condition} />
</div>

function listSpans(props) {
    if (!props.condition) return null;

    return  [  
        <span></span>,
        <span></span>
    ];
}
```

It's a little more syntax, but it solves the issue at hand.

**Comment by jimfb** [comment]
@milesj That is a LOT of syntax for an `if` statement.  Also, it means your nodes are no longer in the same place (you have to scroll to a different file, or at least a different part of the file) to see what is going to get rendered there if the condition is true.  Also, stateless components can't return a list.  Bottom line: no, it doesn't solve it.

**Comment by milesj** [comment]
IMO, if you're returning multiple tags, or complex conditionals like this:

```
<div>
  {condition ?
    [
      (condition ?
        [
          <span></span>,
          'My name is ' + name + '!',
          <span></span>
        ]
      : null),
      'Hello ' + name + '!'
    ]
  : null}
</div>
```

It's probably better to just extract this into a component. More syntax isn't necessarily bad.

**Comment by shaedrich** [comment]
```
<If condition={this.isUserLoggedIn()}>
  <UserPanel /> 
</If>
````

is a nice approach, but it would be even more if JSX could support something like this natively as it is used in Ruby:

```
[1, 2, 3].each do |n|
  puts "Number #{n}"
end
```

in templates:

```
<% if build? %>
    <%= partial "test" %>
<% end %>
```

so in JSX it could look like this:
```
{if true}
    <Component />
{end}
```

**Comment by gaearon** [comment]
See https://github.com/facebook/jsx/pull/98 and https://github.com/facebook/jsx/pull/99.
I’ll lock this issue because it is more about JSX than React. Hopefully the above links are helpful.
