### ISSUE TITLE
A number input will always have left pad 0 though parseFloat value in onChange

### ISSUE THREAD

**Issue by HaydnChen** [facebook/react#9402]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have a number input with defalut value 0 and in onChange function I'll parse value to float to avoid invalid input, but I'll always get left pad 0 on input UI. But in previouse version, my code works.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
<input type="number" value={this.state.value} onChange={e=>this.setState({value: parseFloat(e.target.value)? parseFloat(e.target.value) : 0})}

**What is the expected behavior?**
Should not have left pad 0.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 15.5.3, all browser / all OS. It works in 15.4.2

**Comment by gaearon** [comment]
cc @aweary

**Comment by aweary** [comment]
Thanks for the report @HaydnChen, I verified the bug issue with https://jsfiddle.net/84v837e9/ and have found the root cause.

**Comment by aweary** [comment]
To give some insight, the issue is caused by [ReactDOMInput.js#L192-L200](https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L192-L200)

```js
// Simulate `input.valueAsNumber`. IE9 does not support it
var valueAsNumber = parseFloat(node.value, 10) || 0;
// eslint-disable-next-line
if (value != valueAsNumber) {
  // Cast `value` to a string to ensure the value is set correctly. While
  // browsers typically do this as necessary, jsdom doesn't.
  node.value = '' + value;
 }
```

If the input has the default of `0` and then, for example, the number `4` is entered `node.value` is updated to `'04'`.  Since `'04'` is parsed as `4` it is not considered differnet and  `node.value` is never updated. This check is meant to prevent issues with values like `0.00`.

I'm not sure how we can address this just yet. We may have to do string-based comparisons on top of the existing check to determine if there are other cases like this where the `node.value` should be updated.

**Comment by nhunzaker** [comment]
This is really tricky. It looks like the standard browser behavior is to allow `04` as a value. We need to be careful to not make users feel like control is being taken away from them. The code @aweary points to also addresses the case of being typing `4e` into a number input, which technically reports as '4' until you type another number after the `e`. 

In Chrome, the number input reports values as follows:

- `04`: `"04"`
- `4e`: `""`
- `4.`: `"4"`
- `-`: `""` (like before you type a negative number)

So it's tough, but I think there's something to doing a string comparison for left-hand zeroes.

@aweary I'd be happy to help dig into this. Or at least please let me know if I can answer any questions.

**Comment by aweary** [comment]
@nhunzaker I've got some work towards this locally so I'm happy to keep working on it. I'm hoping we could avoid relying on string comparisons but it's looking like the only way to fix this soundly 🤔

**Comment by antoaravinth** [comment]
@aweary I was trying to look into this issue, it sounded interesting to me. But looks like the jsfiddle link given in the issue seems to be down: https://jsfiddle.net/84v837e9/. Also, I wanted to check if the same issue is present in the current version.

**Comment by antoaravinth** [comment]
@aweary I'm trying to fix this issue, looks like the `node.value` update is happening over here (after the fiber changes): https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L185

However, I couldn't see anywhere we are parsing it to the Number like you have said above (like `parseFloat` etc). If the state of a input is `0`, can't we add checks on this line: https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L125

where the `initialValue` is set? May be a wrong idea. But shouting my thoughts.

**Comment by nhunzaker** [comment]
@antoaravinth Just for some background, there was a change in December of last year:
https://github.com/facebook/react/pull/11751/files

Parsing was removed, because we don't need it. A loose equality check (with some guards) is sufficient, because it parses string values into numbers for comparison.

**Comment by antoaravinth** [comment]
@nhunzaker Thanks. I had found a way to fix this issue, the block of code now looks like the following:

```
if (value != null) {
  if (props.type === 'number') {
    if (
      (value === 0 && node.value === '') ||
      // eslint-disable-next-line
      node.value != value
    ) {
      node.value = '' + value;
    } else if (value !== 0 && node.value !== '' + value) {
      node.value = '' + value;
    }
  } else if (node.value !== '' + value) {
    node.value = '' + value;
  }
}
```

I would say this handles the case and fix the issue. No other test cases got failed and the issue was resolved. Yes, it sounds bit hacky, but I saw similar check was added for handling changes on `0.00` etc. May be @aweary can answer this. Thanks for your time on this.

**Comment by nhunzaker** [comment]
Interesting. It might be a bit hacky, but, given what some browsers give us to work with, it's the situation we're in.

This might be unit testable. I'd like to take these next steps:

1. [ ] Attempt to create a unit test for this. 
2. [ ] Create a DOM test fixture
3. [ ] Do browser testing. If it turns out browser behavior is consistent, we can probably remove the manual fixture.

**Comment by antoaravinth** [comment]
@nhunzaker Sure, will do that. Actually I have done the browser testing. After this change, ran build and used the dist version of react.js and seems to be working fine with chrome. May be will test in other browsers also, update the test cases.

**Comment by nhunzaker** [comment]
Awesome. Just to make sure it's surfaced, our DOM Test Fixtures are here:
https://github.com/facebook/react/tree/master/fixtures/dom

We have a section specifically for number inputs, if that helps testing. Once we move forward on a fix, my plan is to test it against those fixtures.

@antoaravinth: do you mind if I assign you on this issue?

**Comment by antoaravinth** [comment]
@nhunzaker Never, you can assign me the issue. Will get it done :)

**Comment by nhunzaker** [comment]
Ah I can't assign you formally. But consider it yours.

**Comment by antoaravinth** [comment]
@nhunzaker Sure, thanks!

**Comment by nhunzaker** [comment]
Just checking in! No rush in progress, but anything I can do to help move things along?

**Comment by antoaravinth** [comment]
@nhuzaker: Hey, here is the update:

1. Create a DOM test fixture
2. Do browser testing. If it turns out browser behavior is consistent, we can probably remove the manual fixture.

For the above two points, I guess its taken care. After the change, I ran a sample app against the build and the issue is fixed (tested in chrome and firefox). I will write a unit test case for the same, so that we have test in place for this use case and raise a PR. What say? Sorry for the delay btw. 

Mostly will close this by weekend.

**Comment by nhunzaker** [comment]
No need to apologize! Thanks for the update!

**Comment by nhunzaker** [comment]
@antoaravinth's fix in #12451 definitely addresses the concern of this issue. However I didn't fully understand the ramifications of this change until I tried it for myself:

### Change in behavior

#### Before

![before](https://user-images.githubusercontent.com/590904/38031617-9937ba4e-3269-11e8-8310-65477b91ec8c.gif)

Number inputs respect values if they parse to the same numeric value. So `00001` is the same as `1`, maintaining the existing leading zeros in the UI.

#### After

![after](https://user-images.githubusercontent.com/590904/38031621-9d4979f6-3269-11e8-8cb5-79581f41b760.gif)

Number inputs always use the reduced value. So if you typed `00000` then `1`, the number input would reduce the text value to `1`.

### Concerns

This change makes it easier to control the absolute value sent into a number input, but I am concerned that it results in a confusing user experience. The key strokes a user enters into a text box do not align with what they see on the screen. Additionally, number inputs do not give us a text selection API, causing text selection to jump very easily. For example:

**Deleting the leading zero in `0.*` causes a cursor jump**

1. Type `0.01`
2. Delete the leading zero
3. Cursor jumps to end because the input's value is replaced from `.01` to `0.01`, inserting a character.

![cursor-jump](https://user-images.githubusercontent.com/590904/38031759-0022e1a2-326a-11e8-9c93-0d728ab1be39.gif)

**Inserting a number before the decimal place on `0.01` causes a cursor jump**
1. Type `0.01`
2. Move text selection to after the first 0 (`0` [cursor] `.01)
3. Type `1`
3. Cursor jumps to end because the input's value is replaced from `01.01` to `1.01`, deleting a character

### So what do we do?

**Personally, I think we should optimize for avoiding character deletion while the user is typing.** It might be possible that we could apply this behavior only when the number input is not in focus. That would allow you greater control over the value if changing it outside of user text entry, while avoiding confusion during typing.

What do you think?

**Comment by fiedlr** [comment]
Something similar happens with parseInt when your default value (for an empty input) is 0. It doesn't let you erase the zero, which would be natural if it was erased on its own when you start typing some other digits, but it isn't erased: it just stays there and you have to manually remove it ([jsfiddle](https://jsfiddle.net/fiedlr/kb7sevhc/)).

Isn't it a general problem with having numbers in the model? Since they are interpreted as strings when put into an input field (no matter its type it seems), it is perfectly valid for a browser.

A solution might vary depending on how you'd like it to behave. I've fixed it by interpreting an empty string in the view as 0 in the model (and vice versa):

```jsx
<input type="number" value={this.state.value || ''} onChange={this.handle.bind(this)} />
```

Although it's still possible to have leading zeros with it when you try hard (first typing non-zeros and then typing leading zeros), that's not really an issue since in the model it's always interpreted correctly as long as it's parsed by parseInt. The only disadvantage is that you can't really type 0 in, because it always falls back to '', which can be confusing.

**Comment by fiedlr** [comment]
Something similar happens with `parseInt` when your default value is `0`. It doesn't let you erase the zero, which would be natural if it was erased on its own when you start typing some other digits, but it isn't: it just stays there **even though it isn't present in the model** ([jsfiddle](https://jsfiddle.net/fiedlr/kb7sevhc/)).

I see now that was already referenced here too, but it hasn't been fixed so if somebody is still looking for a quick solutions that don't have to parse through the val, I've fixed it for integers by interpreting an empty string in the view as 0 in the model (and vice versa):

```jsx
<input type="number" value={this.state.value || ''} onChange={this.handle.bind(this)} />
```

Although it's still possible to have leading zeros this way when you try hard (first typing non-zeros and then typing leading zeros), that's not a real issue with integers. The number is saved correctly as long as it can be parsed by parseInt. The only disadvantage I see is that you can never type 0 as the first digit because then the value falls back to `''`, which can be confusing for the user.

**Comment by Towerss** [comment]
Hi guys, any updates about this issue? I am testing in Google Chrome and I still cannot delete the 0. Once I change the focus from the numeric input the state of the application is updated to 0. If I type more numbers to the right of the 0 the number is saved as the integers > 0 that I entered, but the numeric input still shows the number with a 0 preceding, which is confusing for the user.

**Comment by JHanLu** [comment]
I change `type = "number"` to `type="text"` and solved the problem.

**Comment by crimson11** [comment]
My solution to this is now quite simple:
If I do have a `<Input type='number'>` and the property of my object, which backs the `value` attribute of the `Input` has a js type of `number`, I simply add a second property, which returns the value of the original property as a `string` type, which I then use in JSX.

```
class SampleFormData {
   constructor() {
      this.myNumberProperty = 0;
   }
   get myNumberPropertyAsString() {
      return this.myNumberProperty + '';
}

<Input type="number"  value={formData.myNumberPropertyAsString}/>
```
In the onChange-handler, I make sure, to update my source object property (SampleFormData.myNumberProperty) with a number-type.

With this approach I am in total control:
I can use `type="number"` (and get browser validation for that) and also get removal of weird stuff like leading zeros, if I don't like it (and can accept cursor jumps on insertion).

**Comment by cassina** [comment]
This is a little weird workaround:

```tsx
<input id={id}
       value={getValueFromState}
       onChange={e => {
           const { value } = e.target;
           const strVal = value.toString();
           if (strVal.startsWith('0')) {
               setValue(strVal.substring(1))
           } else {
               setValue(Number(value))
           }
       }}
       type="number"></input>
```
