### ISSUE TITLE
touchstart preventDefault() does not prevent click event.

### ISSUE THREAD

**Issue by benwiley4000** [facebook/react#9809]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Calling `e.preventDefault()` on a synthetic `onTouchStart` event fails to prevent the `click` event. I also tried `e.nativeEvent.preventDefault()`, but this didn't make any difference.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Here's a div which is supposed to handle a hover case but **not** process a click the first time is is tapped via touch (click on desktop is fine).

[jsfiddle](http://jsfiddle.net/69z2wepo/79757/)
```javascript
const style = {
  background: 'red',
  width: 100,
  height: 100,
  // to ensure `touchstart` `preventDefault()` is allowed on mobile
  touchAction: 'none'
};

class SomeButton extends React.Component {
  constructor (props) {
    super(props);

    this.state = {
      hover: false,
      click: false
    };
  }

  render () {
    return (
      <div
        style={style}
        onMouseEnter={() => this.setState({ hover: true })}
        onClick={() => this.setState({ click: true })}
        onTouchStart={e => {
          if (!this.state.hover) {
            e.preventDefault(); // doesn't work!
            this.setState({ hover: true });
          }
        }}
      >
        {this.state.hover && 'hover!'}
        {this.state.click && 'click!'}
      </div>
    );
  }
}
```

However if I move the `touchstart` listener to `componentDidMount` and use the normal DOM API, everything works:

[jsfiddle](http://jsfiddle.net/69z2wepo/79759/)
```javascript
// ...
class SomeButton extends React.Component {
  constructor (props) {
    // ...
  }
  
  componentDidMount () {
    this.elem.addEventListener('touchstart', e => {
      if (!this.state.hover) {
        e.preventDefault(); // WORKS!
        this.setState({ hover: true });
      }
    });
  }

  render () {
    return (
      <div
        ref={elem => this.elem = elem}
        { /* ... (removed onTouchStart) ... */}
      >
        {/* ... */}
      </div>
    );
  }
}
```

**What is the expected behavior?**
The first time a `touchstart` is processed, we only treat it as a hover, and wait to process the `click` event until the next `touchstart`. If the pointer is a mouse, both events can be processed at once.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.15.4. Not sure about previous React versions. Chrome for Android, Chrome for Mac emulating touch, Firefox for Mac emulating touch.

**Comment by EnoahNetzach** [comment]
Just for completeness, it works as expected on Firefox 53.0.2 on Android 6.0.1, while on chromium based browsers I still get the issue.

**Comment by benwiley4000** [comment]
@EnoahNetzach I became curious after your comment so I tested again...

What I'm finding that is peculiar now is that in Chrome for Mac (58.0.3029.110) emulating touch, the second example solves the issue... but in Firefox for Mac (53.0.3) emulating touch, neither example works as desired!

For the record, the [Touch Events spec](https://w3c.github.io/touch-events/#h-note5) is clear about what *should* happen.

**Comment by EnoahNetzach** [comment]
Adding to the list, in safari on iOS 10.3 (simulated) works as expected..

**Comment by nhunzaker** [comment]
Hmm. Bummer. Thanks everyone for digging into this. We should do the following:

1. Produce a test case that does not use React.
2. Produce a test case for our [DOM fixture manual test suite](https://github.com/facebook/react/tree/master/fixtures/dom)

Additionally, I have a PR out that attaches touch listeners local to an element. I am curious if this might have an unexpected side-effect of fixing this issue (assuming it's a React issue):

https://github.com/facebook/react/pull/9333

**Comment by benwiley4000** [comment]
@nhunzaker: thanks! Based on the findings so far I suspect that PR might solve the issue (except for Firefox for Mac [not mobile] where it appears to persist regardless).. Would there be an easy way to test it with my code?

**Comment by nhunzaker** [comment]
I have a custom build up for that branch, you could pull in React and ReactDOM from:

**React:**
https://nh-dom-fixtures-scroll.surge.sh/react.development.js

**ReactDOM:**
https://nh-dom-fixtures-scroll.surge.sh/react-dom.development.js

I've forked and updated your gist with those scripts here:
http://jsfiddle.net/69z2wepo/79803/

Though I won't be able to dig into testing it myself until later today or tomorrow.

**Comment by benwiley4000** [comment]
@nhunzaker thank you.

I tested just now (using Chrome for Android and Chrome with emulated touch for Mac). Unfortunately the behavior seems to be the same.

**Comment by benwiley4000** [comment]
@nhunzaker here is the non-React comparison case you asked for. https://jsfiddle.net/a2k4whf0/2/

**Comment by gaearon** [comment]
@nhunzaker What's the next step here?

**Comment by OZhurbenko** [comment]
It would be great if this was fixed at some point.
I was very confused about this behavior, especially after I saw Chromium [response](https://bugs.chromium.org/p/chromium/issues/detail?id=119216) saying that everything works as expected, but it clearly didn't.

> if I move the touchstart listener to componentDidMount and use the normal DOM API, everything works

Thanks, that worked for me.

**Comment by OZhurbenko** [comment]
Hmm.. actually "normal DOM API" solution didn't work.
Apparently it didn't fix it for mobile Firefox, there's probably a bug there. Nothing can prevent Firefox from triggering mousedown-mousemove-mouseup events following touchstart 😕 

Had to work around that and add a flag to the touchStart handler:

```
handleTouchStart(event) {
  this.hasBeenTouchedRecently = true;
  setTimeout(() => { this.hasBeenTouchedRecently = false; }, 500);
  ...
}
```

And a simple return from mouseDown handler:

```
  handleMouseDown(event) {
    if(this.hasBeenTouchedRecently) {
      return;
    }
  ...
```

In this case it doesn't matter how you add "touchstart" event listener, I did it via standard React way.

**Comment by RandScullard** [comment]
Any update on this? It's been nearly eight months and this is still an issue. I was able to work around it with a solution similar to the one suggested by @OZhurbenko, but it would be really nice to see this fixed.

**Comment by benwiley4000** [comment]
@seanmadsen that works, and is a less obtrusive workaround! But it shouldn't be necessary according to the spec. Preventing default on `touchstart` should cancel a click event, since it requires both a pointer start and pointer end.

Any updates, React folks? 🙂 @nhunzaker?

**Comment by nhunzaker** [comment]
Sorry... I let this slide. :( I wonder if there is an event plugin that is getting in the way. I'll investigate what event plugins fire on touch.

**Comment by benwiley4000** [comment]
Thanks!

**Comment by nhunzaker** [comment]
What fun!

It looks like `event.defaultPrevented` is only set on the SyntheticEvent, not the native event:

![image](https://user-images.githubusercontent.com/590904/43176671-9778bb00-8f79-11e8-9a58-c0f94fde5d89.png)

So for some reason, this synthetic event.preventDefault event implementation isn't working:

https://github.com/facebook/react/blob/master/packages/events/SyntheticEvent.js#L115-L128

```
preventDefault: function() {
    this.defaultPrevented = true;
    const event = this.nativeEvent;
    if (!event) {
      return;
    }

    if (event.preventDefault) {
      event.preventDefault();
    } else if (typeof event.returnValue !== 'unknown') {
      event.returnValue = false;
    }
    this.isDefaultPrevented = functionThatReturnsTrue;
  },
```

Now to figure out why...

**Comment by nhunzaker** [comment]
I think I see the issue.

React attaches (most) events to the document:
https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ReactBrowserEventEmitter.js#L128

It looks like, in Chrome, anyway, that setting `event.preventDefault()` does not set `event.defaultPrevented` on the event when attached to the document:
https://jsfiddle.net/a2k4whf0/18/

This is also true of `document.body`, and `window`.

Maybe this is another reason to revisit "Attach event per react container root, rather than on the document" https://github.com/facebook/react/issues/2043.

A change like that is serious. I wonder if there's another way we could achieve this.

/cc @philipp-spiess

**Comment by philipp-spiess** [comment]
@nhunzaker I think the problem here is that React adds event listeners as [passive](https://developers.google.com/web/updates/2016/06/passive-event-listeners) (the new default) and that passive event listeners do not allow calling `preventDefault()` (also check out #6436).

Checking out your example makes this pretty clear by the following line in the console (you have to tap a few times for the message to pop up):

> (index):44 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

If I update your example and and mark the event listeners as `{ passive: false }` it works like expected: https://jsfiddle.net/dL4obakf/5/ (am I overlooking something?)

A simple workaround in React) is to add a native event listener using the `{ passive: false }` option:

```js
document.addEventListener(
  "touchstart",
  function(e) {
    e.preventDefault();
  },
  { passive: false }
);
```

It's also possible to feature-detect passive-event listener support:

```js
let supportsPassiveOption = false;
const opts = Object.defineProperty({}, "passive", {
  get: function() {
    supportsPassiveOption = true;
  }
});
try {
  window.addEventListener("test", null, opts);
} catch (e) {}
```

**Comment by gaearon** [comment]
Got some feedback this wasn't clear enough.

The problem is that Chrome made a breaking change and **`e.preventDefault()` in document-level `touchstart` listeners doesn't work anymore**. React binds events at document level for better performance. This is why `e.preventDefault()` in React `onTouchStart` doesn't currently work.

You can work around this by attaching a listener **at the individual node level** with refs. I showed how to do this in the previous comment.

Longer term, we plan to change React to attach events at the root container level instead of document level anyway. This is what #2043 is about. So when we implement #2043 the problem will go away by itself. Until then, the workaround with a ref and manual `ontouchstart` listener should work fine.

**Comment by philipp-spiess** [comment]
@mseddon My fix is not practical to be applied at the framework level. There are a number of arguments why Chrome made some events passive by default and why we don't want to revert that decision. You can read up on that here: https://github.com/facebook/react/issues/6436

The recommended approach is to only add non-passive events if you're certain that you will need to call `event.preventDefault()` and you can do this within React as well by manually adding event listeners (as Dan and I pointed out in the comments above). 

That said, we would really like a declarative way to add passive/non-passive event listeners within the framework but changing that would break numerous React applications in subtle ways which is why we need to be especially careful here. We're working on a large scale revamp of React DOM called [React Fire](https://github.com/facebook/react/issues/13525) which should give us what's needed to address this issue though.

**Comment by kadamska** [comment]
> I had this same problem and was able to eliminate the superfluous `mousedown` event by calling `preventDefault()` from within `onTouchEnd` like this:
> 
> ```js
> render() {
>   return (
>     <div
>       onMouseDown={e => this.handleMouseDownOrTouchStart(e)}
>       onTouchStart={e => this.handleMouseDownOrTouchStart(e)}
>       onTouchEnd={e => e.preventDefault()}
>     >
>       Foo
>     </div>
>   );
> }
> ```
> 
> Reference: https://developers.google.com/web/updates/2017/01/scrolling-intervention
> 
> > To suppress the default behavior of a tap (such as the generation of a click event), call `preventDefault()` inside of a `touchend` listener.

This works, most of the time. But when I have a nested element and implement double handlers on both a parent and a child, the child's `e.preventDefault()` only prevents the touch event, but the mouse event is still called on the parent.

**Comment by craigkovatch** [comment]
@gaearon is it safe to assume this old issue is fixed in React 17, via the changes to where event listeners are bound?

**Comment by sneakyfildy** [comment]
Still doing preventDefault in touchstart handler does not suppress any following mouse event. Latest React. Handler attached using onTouchStart. (so passive, I presume)

**Comment by nz-chris** [comment]
I get the following error when trying to invoke `preventDefault` on a touch event (from `onTouchStart`).
`react-dom.development.js:6202 Unable to preventDefault inside passive event listener invocation.`

Therefore, with the latest version of React, this issue's title (**touchstart preventDefault() does not prevent click event.**) is still an issue.
@gaearon Can this issue be re-opened?

**Comment by gpoole** [comment]
I'm seeing this in React 18, so it seems like it isn't fixed by #2043 which I think went out with 17? I've made a reproduction of the problem with 18.2: https://4hrliz.csb.app/ 

In Chrome with touch device emulation I get an error in the console same as @nz-chris:

```
Unable to preventDefault inside passive event listener invocation.
```
